export {
  type ArmGeometry,
  type ArmInput,
  type ArmState,
  type ArmTerminal,
  type BranchingLayout,
  type BranchingLayoutOptions,
  type ForkMarker,
  GLYPH_HEIGHT_MAX,
  GLYPH_HEIGHT_MIN,
  layoutBranching,
  type Point,
  SYNTHETIC_DASH,
  strandsOf,
  type TrunkGeometry,
} from './geometry.js'
