import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { isInside } from './paths/containment.js'

/**
 * prd-54's law — `.swarm/coupling.txt` checks itself (issue #367, wave 2).
 *
 * `.swarm/coupling.txt` is prose asserting facts about other files: that a law pins an
 * exact count, that a spelling occurs verbatim elsewhere, that a path exists. Nothing
 * checked any of that before this file — `scripts/dev/coupling.test.sh` runs in no
 * workflow, no `package.json` script and not in `scripts/gate.sh`, and
 * `doc-citation-law.test.ts` cannot reach a `.txt`. Every ruling this law implements is in
 * `docs/prds/prd-54-the-registry-that-checks-itself.md`; only the ones that changed the
 * law's behaviour, not the ones that only explained why, are repeated here.
 *
 * Lives under `packages/server/` for the reason every sibling law here already gives: the
 * root vitest config globs `packages/*`, so a root-level test would never run.
 *
 * ## What is checked, and by which ruling
 *
 * - **Ruling 10, presence.** Every entry's leading path exists, and its reason, trimmed,
 *   is non-empty and not a restatement of the leading path — by EQUALITY against both
 *   spellings of the path (the one `xargs` would produce and the one as typed), after one
 *   matched layer of a backtick/single/double quote is stripped from the reason. This is
 *   `scripts/dev/coupling.test.sh`'s own check, ported rather than re-derived — see
 *   `isUnexplained` below, and the test that runs both engines over the same file to prove
 *   they agree.
 * - **Ruling 7 (which is ruling 2's check).** A backticked span containing `.toBe(`,
 *   `.toHaveLength(` or `.toEqual(` is an assertion span. The **whole span**, whitespace
 *   included, must occur as an exact substring of the entry's leading-path file — not
 *   normalised, not parsed, and not reduced to the assertion call alone.
 * - **Ruling 8 (which replaces ruling 5's Extent, and is the whole path selector).** A
 *   backticked span is a path citation when it carries no glob metacharacter, every
 *   character is in `[A-Za-z0-9._/-]`, it does not begin with `/`, and it either contains
 *   `/`, or (not beginning with `.`) its final dot-separated segment is a tracked
 *   extension, or it is exactly a tracked file's basename. The extension and basename
 *   sets are derived from `git ls-files`, never written down (`trackedFileSets` below).
 *   The population is every backticked span in an entry's reason text; the freestanding
 *   `# ── section ──` comments between entries are not scanned, because they are never
 *   entered into `entries` in the first place — the same skip `coupling.test.sh` and
 *   `scripts/fence-lint.sh` both make.
 * - **Ruling 5's verdict (unchanged).** An admitted citation resolves repo-relative, or —
 *   only if the entry's own leading path lies inside a package source root — relative to
 *   that one root, and nowhere else. The root list is derived from the workspace's own
 *   `package.json` (`packageSourceRoots` below), never hardcoded. "Resolves" is existence
 *   (`-e`, ruling 8's Extent part two): a directory citation resolves.
 * - **Ruling 10, generated declarations.** The one form —
 *   `` `<generated>` is GENERATED by `<generator>` `` — exempts every occurrence of that
 *   generated-path text **within the same entry** from resolution (not merely the one
 *   span inside the declaration phrase: ruling 3 declares a path generated, not a single
 *   mention of it, and ruling 8's own amendment already counted both of
 *   `scripts/gate.sh`'s two `` `.swarm/timing-count` `` occurrences as "the declared
 *   occurrences" before ruling 10 existed to give the declaration a syntax). The generator
 *   must itself resolve under ruling 5's two attempts, and the generator file's text must
 *   contain the generated path.
 * - **Ruling 9.** Not separately enforced — a grep target, a family glob, or a
 *   second-hand shorthand spelled differently from its first mention all surface as a
 *   plain unresolved citation, which is the right verdict with the wrong message on its
 *   own; this law's failure text for an unresolved citation names ruling 9 so the reader
 *   is not sent to "the path moved" when the real fix is "quote it the way ruling 9 asks".
 *
 * ## Collection must not throw
 *
 * `gate-honesty-law.test.ts`'s anchor lookups run at module scope and throw when a search
 * matches zero lines, which takes every assertion in that file out of service at once for
 * one reworded line. Nothing here runs at module scope except reading the registry text
 * itself (parallel to every other law's `const SOURCE = readFileSync(...)`, safe because
 * the file is required to exist by `scripts/fence-lint.sh` already). Every filesystem read
 * that depends on what a given entry's reason actually says — resolving a citation,
 * reading a cited file's text — happens inside a test body, gated on `existsSync` first,
 * so a bad entry fails that one test rather than the whole file.
 */

const REPO_ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
const COUPLING_PATH = '.swarm/coupling.txt'
const COUPLING_SCRIPT_PATH = 'scripts/dev/coupling.test.sh'

// ── parsing — must agree exactly with scripts/fence-lint.sh:79-81 and scripts/dev/coupling.test.sh ──

interface RegistryEntry {
  readonly lineNo: number
  /** `${line%%#*}` — everything before the first `#`, unprocessed. */
  readonly rawField: string
  /** `rawField`, trimmed only (bash parameter-expansion trim, no quote/backslash handling). */
  readonly rawTrimmed: string
  /** `$(echo "$rawField" | xargs)` — the path fence-lint.sh and coupling.test.sh both compute. */
  readonly path: string
  /** `${line#*#}` — everything after the first `#` (the whole line, if there is no `#`). */
  readonly reason: string
  /** `reason`, trimmed only. */
  readonly reasonTrimmed: string
}

/**
 * `xargs`' own word-splitting: unquoted whitespace separates tokens, a matched pair of
 * single or double quotes groups one, a backslash escapes the next character, and the
 * result is the tokens rejoined with single spaces — exactly what
 * `$(echo "$raw" | xargs)` does to a registry line's leading field. Every path in the
 * registry today is a single unquoted token, so this only changes behaviour for a
 * hypothetical quoted or multiply-spaced path — which `coupling.test.sh`'s own comment
 * says is "unreachable on today's registry" and is exactly why it is ported rather than
 * approximated.
 */
function xargsNormalize(s: string): string {
  const tokens: string[] = []
  let current = ''
  let inToken = false
  let i = 0
  while (i < s.length) {
    const c = s[i]!
    if (c === ' ' || c === '\t' || c === '\n' || c === '\r') {
      if (inToken) {
        tokens.push(current)
        current = ''
        inToken = false
      }
      i++
      continue
    }
    inToken = true
    if (c === '\\') {
      i++
      if (i < s.length) {
        current += s[i]
        i++
      }
      continue
    }
    if (c === "'") {
      i++
      while (i < s.length && s[i] !== "'") {
        current += s[i]
        i++
      }
      i++
      continue
    }
    if (c === '"') {
      i++
      while (i < s.length && s[i] !== '"') {
        if (s[i] === '\\' && i + 1 < s.length && ['"', '\\', '$', '`'].includes(s[i + 1]!)) {
          current += s[i + 1]
          i += 2
        } else {
          current += s[i]
          i++
        }
      }
      i++
      continue
    }
    current += c
    i++
  }
  if (inToken) tokens.push(current)
  return tokens.join(' ')
}

/** Parses registry text with the same rules as `scripts/fence-lint.sh:79-81` and `scripts/dev/coupling.test.sh` — blank lines and lines starting with `#` are skipped, everything else is one entry. */
function parseRegistry(text: string): RegistryEntry[] {
  const entries: RegistryEntry[] = []
  const lines = text.split('\n')
  lines.forEach((line, idx) => {
    if (line === '' || line.startsWith('#')) return
    const hashIdx = line.indexOf('#')
    const rawField = hashIdx === -1 ? line : line.slice(0, hashIdx)
    const reason = hashIdx === -1 ? line : line.slice(hashIdx + 1)
    const entryPath = xargsNormalize(rawField)
    if (entryPath === '') return
    entries.push({
      lineNo: idx + 1,
      rawField,
      rawTrimmed: rawField.trim(),
      path: entryPath,
      reason,
      reasonTrimmed: reason.trim(),
    })
  })
  return entries
}

const DELIMITERS = ['`', "'", '"'] as const

/** Strips at most one matched layer of a backtick, single, or double quote from both ends — the shell's `for d in '`' "'" '"'` loop, which `break`s on the first member that matches. */
function stripOneDelimiterLayer(s: string): string {
  for (const d of DELIMITERS) {
    if (s.length >= 2 && s.startsWith(d) && s.endsWith(d)) {
      return s.slice(1, -1)
    }
  }
  return s
}

/**
 * `scripts/dev/coupling.test.sh`'s "no reason given" check, ported exactly (prd-54 ruling
 * 10): EQUALITY, not containment, against both spellings of the leading path — the
 * canonical one `xargs` would produce and the one as typed — with at most one matched
 * delimiter layer stripped from the reason first.
 */
function isUnexplained(entry: RegistryEntry): boolean {
  const bare = stripOneDelimiterLayer(entry.reasonTrimmed)
  return (
    entry.reasonTrimmed === '' ||
    entry.reasonTrimmed === entry.path ||
    entry.reasonTrimmed === entry.rawTrimmed ||
    bare === entry.path ||
    bare === entry.rawTrimmed
  )
}

// ── ruling 8's derived sets, and ruling 5's derived package roots ──

interface TrackedSets {
  readonly extensions: ReadonlySet<string>
  readonly basenames: ReadonlySet<string>
}

let trackedSetsCache: TrackedSets | undefined

/** Every tracked file's basename, and every tracked (non-dotfile) basename's final dot-segment — derived from `git ls-files`, never written down (ruling 8's own requirement of its own extension list, applied to itself). */
function trackedFileSets(): TrackedSets {
  if (trackedSetsCache) return trackedSetsCache
  const files = execFileSync('git', ['ls-files'], { cwd: REPO_ROOT, encoding: 'utf8' })
    .split('\n')
    .filter((f) => f.length > 0)
  const extensions = new Set<string>()
  const basenames = new Set<string>()
  for (const f of files) {
    const base = path.basename(f)
    basenames.add(base)
    if (!base.startsWith('.') && base.includes('.')) {
      extensions.add(base.slice(base.lastIndexOf('.') + 1))
    }
  }
  trackedSetsCache = { extensions, basenames }
  return trackedSetsCache
}

let packageRootsCache: readonly string[] | undefined

/** Every workspace package's source root (`packages/<name>/src`), derived from root `package.json`'s own `workspaces` globs plus which of those directories actually carry a `package.json` — never a hardcoded list (ruling 5's own requirement). */
function packageSourceRoots(): readonly string[] {
  if (packageRootsCache) return packageRootsCache
  const rootPkg = JSON.parse(readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')) as {
    workspaces?: readonly string[]
  }
  const roots: string[] = []
  for (const pattern of rootPkg.workspaces ?? []) {
    const m = /^(.*)\/\*$/.exec(pattern)
    if (!m) continue
    const baseDir = m[1]!
    const absBase = path.join(REPO_ROOT, baseDir)
    if (!existsSync(absBase)) continue
    for (const name of readdirSync(absBase).sort()) {
      if (existsSync(path.join(absBase, name, 'package.json'))) {
        roots.push(`${baseDir}/${name}/src`)
      }
    }
  }
  packageRootsCache = roots
  return roots
}

// ── ruling 7's assertion spans, and ruling 8's path-citation clauses ──

interface BacktickSpan {
  readonly start: number
  readonly text: string
}

/** Every backtick-delimited span in `text`, in order — the population ruling 8's clauses and ruling 7's selector both draw from. */
function extractBacktickSpans(text: string): BacktickSpan[] {
  const spans: BacktickSpan[] = []
  const re = /`([^`]+)`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text))) {
    spans.push({ start: m.index + 1, text: m[1]! })
  }
  return spans
}

/** Ruling 7's selector, widened to any assertion call: `.toBe(`, `.toHaveLength(`, or `.toEqual(`, whatever its argument. */
function isAssertionSpan(span: string): boolean {
  return span.includes('.toBe(') || span.includes('.toHaveLength(') || span.includes('.toEqual(')
}

const GLOB_CHARS = new Set(['*', '?', '[', ']', '{', '}'])
const PATH_CHAR_CLASS_RE = /^[A-Za-z0-9._/-]+$/

type PathClause = '4a' | '4b' | '4c'

/** Ruling 8's four clauses. Deliberately disjoint from `isAssertionSpan`: clause 2's character class rejects every span an assertion call selects, because an assertion span always carries parentheses. */
function pathCitationClause(span: string, sets: TrackedSets): PathClause | undefined {
  for (const ch of span) if (GLOB_CHARS.has(ch)) return undefined
  if (!PATH_CHAR_CLASS_RE.test(span)) return undefined
  if (span.startsWith('/')) return undefined
  if (span.includes('/')) return '4a'
  if (!span.startsWith('.') && span.includes('.')) {
    const ext = span.slice(span.lastIndexOf('.') + 1)
    if (sets.extensions.has(ext)) return '4b'
  }
  if (sets.basenames.has(span)) return '4c'
  return undefined
}

interface GeneratedDeclaration {
  readonly generated: string
  readonly generator: string
}

/** Ruling 10's one declaration form: `` `<generated>` is GENERATED by `<generator>` `` — the literal text between two backticked spans, and nothing looser. */
function extractGeneratedDeclarations(text: string): GeneratedDeclaration[] {
  const out: GeneratedDeclaration[] = []
  const re = /`([^`]+)` is GENERATED by `([^`]+)`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text))) out.push({ generated: m[1]!, generator: m[2]! })
  return out
}

interface Resolution {
  readonly resolved: boolean
  readonly resolvedAbsPath?: string
  readonly attempted: readonly string[]
}

/**
 * Is `entryPath` (repo-relative) `root` itself or somewhere beneath it?
 *
 * Delegates to `paths/containment.ts`'s `isInside` rather than a raw
 * `entryPath.startsWith(root + '/')` — not for symlink safety (both sides are
 * workspace source directories, not caller-supplied paths), but because that
 * shape is exactly what `paths/prefix-comparison-law.test.ts` hunts, and
 * `containment.ts` is the one file that law's own sweep excludes by name.
 * Reaching for the shared primitive here is what that law's own registry
 * entry recommends instead of growing its known-debt count by one.
 */
function isOwnPackageRoot(entryPath: string, root: string): boolean {
  const absEntry = path.join(REPO_ROOT, entryPath)
  const absRoot = path.join(REPO_ROOT, root)
  return absEntry === absRoot || isInside(absRoot, absEntry)
}

/**
 * `existsSync(absPath)`, AND `absPath` resolves inside the repository — never merely
 * "some file on this machine happens to exist at the joined string".
 *
 * `path.join(REPO_ROOT, candidate)` happily walks a `../`-shaped `candidate` out of the
 * repo, and a bare `existsSync` on the result cannot tell a real registry citation from a
 * citation that escaped to the operator's home directory, the filesystem root, or anywhere
 * else a real file or directory happens to sit. Ruling 5's two attempts are both
 * REPO-RELATIVE by definition — resolving outside the repo is not a third attempt, it is a
 * wrong answer to the first two. This is the one predicate every existence check in this
 * file goes through, rather than a `../` string-match bolted onto each call site
 * separately (see the predicate table in the commit body: three ad hoc guards would have
 * been the same defect three times over, not three fixes).
 */
function existsInsideRepo(absPath: string): boolean {
  if (!existsSync(absPath)) return false
  return absPath === REPO_ROOT || isInside(REPO_ROOT, absPath)
}

/** Ruling 5's two attempts, in order, and ruling 8's `-e` predicate (existence — a directory resolves) — bounded to the repo by `existsInsideRepo`. */
function resolveCitation(candidate: string, entryPath: string, pkgRoots: readonly string[]): Resolution {
  const attempted: string[] = []
  const repoRelAbs = path.join(REPO_ROOT, candidate)
  attempted.push(`repo-relative (${candidate})`)
  if (existsInsideRepo(repoRelAbs)) return { resolved: true, resolvedAbsPath: repoRelAbs, attempted }

  const ownRoot = pkgRoots.find((r) => isOwnPackageRoot(entryPath, r))
  if (ownRoot) {
    const pkgRelAbs = path.join(REPO_ROOT, ownRoot, candidate)
    attempted.push(`under its own package root ${ownRoot} (${path.posix.join(ownRoot, candidate)})`)
    if (existsInsideRepo(pkgRelAbs)) return { resolved: true, resolvedAbsPath: pkgRelAbs, attempted }
  }
  return { resolved: false, attempted }
}

/** Reads `absPath`'s text if it names an existing, readable, regular file inside the repo — never throws. */
function readFileIfFile(absPath: string): string | undefined {
  try {
    if (!existsInsideRepo(absPath) || !statSync(absPath).isFile()) return undefined
    return readFileSync(absPath, 'utf8')
  } catch {
    return undefined
  }
}

/**
 * True when `haystack` mentions `needle` as a COMPLETE path token, not merely as a prefix
 * of a longer one (ruling 10: the generator must NAME the declared path). Checked only at
 * the trailing edge — the character immediately after the match must not be one that would
 * extend it into a different name (`[A-Za-z0-9._/-]`, the same class ruling 8 uses for a
 * path citation). The leading edge is deliberately unchecked: a real declaration is
 * ordinarily found as part of a LONGER enclosing path (`$root/.swarm/timing-count` in
 * `scripts/gate.sh`), and that is the legitimate, everyday shape this must not reject.
 * `.swarm/timing-count-probe-suffix` contains `.swarm/timing-count` as a substring; this
 * matches neither there (the trailing `-` extends it) nor anywhere else in that string.
 */
function mentionsWholePath(haystack: string, needle: string): boolean {
  const escaped = needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`${escaped}(?![A-Za-z0-9._/-])`).test(haystack)
}

// ── per-entry analysis ──

interface EntryAnalysis {
  readonly entry: RegistryEntry
  readonly violations: readonly string[]
  readonly totalBacktickSpans: number
  readonly assertionSpansSelected: number
  readonly pathCitationsAdmitted: number
  readonly pathCitationsResolved: number
  readonly pathCitationsExempt: number
}

function analyzeEntry(entry: RegistryEntry, sets: TrackedSets, pkgRoots: readonly string[]): EntryAnalysis {
  const violations: string[] = []

  const leadingAbs = path.join(REPO_ROOT, entry.path)
  if (!existsInsideRepo(leadingAbs)) {
    violations.push(`leading path does not exist inside the repo (prd-54 ruling 10, presence): ${entry.path}`)
  }

  if (isUnexplained(entry)) {
    violations.push(
      `reason is empty, or restates its own leading path under equality (prd-54 ruling 10, presence): ${JSON.stringify(entry.reason)}`,
    )
  }

  const spans = extractBacktickSpans(entry.reason)
  const declarations = extractGeneratedDeclarations(entry.reason)
  const declaredGeneratedTexts = new Set(declarations.map((d) => d.generated))
  const citedFileText = readFileIfFile(leadingAbs)

  let assertionSpansSelected = 0
  let pathCitationsAdmitted = 0
  let pathCitationsResolved = 0
  let pathCitationsExempt = 0

  for (const span of spans) {
    if (isAssertionSpan(span.text)) {
      assertionSpansSelected++
      if (citedFileText === undefined) {
        violations.push(
          `assertion span cannot be checked — ${entry.path} is not a readable file (prd-54 ruling 7): \`${span.text}\``,
        )
      } else if (!citedFileText.includes(span.text)) {
        violations.push(
          `assertion span does not occur verbatim (whitespace included) in ${entry.path} (prd-54 ruling 7): \`${span.text}\``,
        )
      }
      continue
    }

    const clause = pathCitationClause(span.text, sets)
    if (!clause) continue
    pathCitationsAdmitted++

    if (declaredGeneratedTexts.has(span.text)) {
      pathCitationsExempt++
      continue
    }

    const resolution = resolveCitation(span.text, entry.path, pkgRoots)
    if (resolution.resolved) {
      pathCitationsResolved++
    } else {
      violations.push(
        `path citation (clause ${clause}) does not resolve — tried ${resolution.attempted.join('; ')}. ` +
          `Check prd-54 ruling 9 before assuming the path moved: a grep target, a family shorthand, or a ` +
          `second-hand mention spelled differently from its first mention all look like this. \`${span.text}\``,
      )
    }
  }

  for (const decl of declarations) {
    const resolution = resolveCitation(decl.generator, entry.path, pkgRoots)
    if (!resolution.resolved) {
      violations.push(
        `declared generator does not resolve (prd-54 ruling 10) — tried ${resolution.attempted.join('; ')}: ` +
          `\`${decl.generator}\` for \`${decl.generated}\``,
      )
      continue
    }
    const generatorText = readFileIfFile(resolution.resolvedAbsPath!)
    if (generatorText === undefined || !mentionsWholePath(generatorText, decl.generated)) {
      violations.push(
        `declared generator \`${decl.generator}\` does not name its generated path as a whole token, ` +
          `not merely as a prefix of a longer one (prd-54 ruling 10): \`${decl.generated}\``,
      )
    }
  }

  return {
    entry,
    violations,
    totalBacktickSpans: spans.length,
    assertionSpansSelected,
    pathCitationsAdmitted,
    pathCitationsResolved,
    pathCitationsExempt,
  }
}

function sum(ns: readonly number[]): number {
  return ns.reduce((a, b) => a + b, 0)
}

function extractPrefixedPaths(output: string, prefix: string): string[] {
  return output
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith(prefix))
    .map((line) => line.slice(prefix.length))
}

// ── the law ──

describe('coupling registry law: .swarm/coupling.txt checks itself (prd-54, #367)', () => {
  const registryText = readFileSync(path.join(REPO_ROOT, COUPLING_PATH), 'utf8')
  const entries = parseRegistry(registryText)

  it('the registry parses to at least one entry — a law that checks nothing is worse than no law', () => {
    expect(entries.length).toBeGreaterThan(0)
  })

  it.each(entries.map((e) => [e.lineNo, e.path, e] as const))(
    'line %i: %s — leading path exists, reason is honest, every checked citation resolves',
    (_lineNo, _p, entry) => {
      const analysis = analyzeEntry(entry, trackedFileSets(), packageSourceRoots())
      expect(analysis.violations).toEqual([])
    },
  )

  it('proves it looked: reports every entry\'s span/selection counts, and the registry-wide totals are not zero', () => {
    const sets = trackedFileSets()
    const pkgRoots = packageSourceRoots()
    const analyses = entries.map((e) => analyzeEntry(e, sets, pkgRoots))

    const table = analyses.map((a) => ({
      path: a.entry.path,
      backtickSpans: a.totalBacktickSpans,
      assertionSpansSelected: a.assertionSpansSelected,
      pathCitationsAdmitted: a.pathCitationsAdmitted,
      pathCitationsResolved: a.pathCitationsResolved,
      pathCitationsExempt: a.pathCitationsExempt,
    }))
    const totals = {
      entries: entries.length,
      backtickSpans: sum(table.map((t) => t.backtickSpans)),
      assertionSpansSelected: sum(table.map((t) => t.assertionSpansSelected)),
      pathCitationsAdmitted: sum(table.map((t) => t.pathCitationsAdmitted)),
      pathCitationsResolved: sum(table.map((t) => t.pathCitationsResolved)),
      pathCitationsExempt: sum(table.map((t) => t.pathCitationsExempt)),
    }
    console.log('coupling registry law — per-entry breakdown:\n' + JSON.stringify(table, null, 2))
    console.log('coupling registry law — totals:', JSON.stringify(totals))

    expect(
      totals.assertionSpansSelected,
      'ruling 7 selected zero assertion spans across the whole registry — the selector is broken, not the registry',
    ).toBeGreaterThan(0)
    expect(
      totals.pathCitationsAdmitted,
      'ruling 8 admitted zero path citations across the whole registry — the selector is broken, not the registry',
    ).toBeGreaterThan(0)

    // Every entry's breakdown is a defined, non-negative count — silence because an entry
    // is clean and silence because the selector never reached it must never be the same
    // output with no way to tell them apart (prd-54's own Evidence section names exactly
    // this failure, twice, elsewhere in this repo).
    for (const t of table) {
      expect(Number.isInteger(t.backtickSpans), `${t.path}: backtick-span count is not a defined integer`).toBe(true)
    }
  })

  it('agrees with scripts/dev/coupling.test.sh about which paths are stale and which reasons are unexplained', { timeout: 20_000 }, () => {
    let shellOutput: string
    try {
      shellOutput = execFileSync('bash', [path.join(REPO_ROOT, COUPLING_SCRIPT_PATH)], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
      })
    } catch (err) {
      shellOutput = (err as { stdout?: string }).stdout ?? ''
    }

    // The script's OWN summary line, not merely "the process exited" or "stdout is
    // non-empty" — a script that crashed before printing anything (or was replaced with a
    // bare `exit N`) leaves both extracted sets empty, and an empty-vs-empty `toEqual`
    // below would pass having compared nothing to nothing. This is what "prove the
    // agreement, do not assert it" actually requires: proof the comparison's INPUT is real.
    expect(
      shellOutput,
      "scripts/dev/coupling.test.sh produced no '<N> passed, <M> failed' summary line — it did not run to completion, so the agreement below would compare two empty sets and pass vacuously",
    ).toMatch(/^\d+ passed, \d+ failed$/m)

    const shellMissing = new Set(extractPrefixedPaths(shellOutput, 'no such path: '))
    const shellUnexplained = new Set(extractPrefixedPaths(shellOutput, 'no reason given: '))

    const lawMissing = new Set(entries.filter((e) => !existsInsideRepo(path.join(REPO_ROOT, e.path))).map((e) => e.path))
    const lawUnexplained = new Set(entries.filter((e) => isUnexplained(e)).map((e) => e.path))

    expect(lawMissing, 'the law and scripts/dev/coupling.test.sh disagree on which leading paths are stale').toEqual(
      shellMissing,
    )
    expect(
      lawUnexplained,
      'the law and scripts/dev/coupling.test.sh disagree on which reasons are unexplained',
    ).toEqual(shellUnexplained)
  })

  it("scripts/dev/coupling.test.sh points at this law's full path, so the two cannot silently diverge", () => {
    const scriptText = readFileSync(path.join(REPO_ROOT, COUPLING_SCRIPT_PATH), 'utf8')
    expect(scriptText).toContain('packages/server/src/coupling-registry-law.test.ts')
  })
})

/**
 * The reason-restatement check (prd-54 ruling 10, presence), against the exact synthetic
 * shapes `scripts/dev/coupling.test.sh`'s own doc comment names — including the ones it
 * declares it deliberately does not catch. Unreachable on the live registry today (no
 * entry is quoted or carries odd whitespace), which is exactly why the shell script's own
 * comment says to write it down here rather than leave it for the entry that first needs
 * it.
 */
describe('reason-restatement check ports scripts/dev/coupling.test.sh exactly (prd-54 ruling 10)', () => {
  const cases: readonly { readonly line: string; readonly unexplained: boolean; readonly note: string }[] = [
    { line: 'p', unexplained: true, note: 'no # at all: the reason IS the whole line' },
    { line: "p  # 'p'", unexplained: true, note: 'single-quoted restatement' },
    { line: 'p  # "p"', unexplained: true, note: 'double-quoted restatement' },
    { line: 'p  # `p`', unexplained: true, note: 'backticked restatement' },
    { line: 'p  # a real reason', unexplained: false, note: 'an ordinary reason is not flagged' },
    {
      line: "p  # ''p''",
      unexplained: false,
      note: 'two layers of the SAME delimiter are deliberately NOT caught',
    },
    {
      line: 'p  # \'p"',
      unexplained: false,
      note: 'a MISMATCHED delimiter pair is deliberately NOT caught',
    },
    {
      line: 'docs/adr/  # run `git ls-tree origin/main docs/adr/` first, then check every open PR head',
      unexplained: false,
      note: 'a true self-reference inside a longer reason (the real docs/adr/ case) is not flagged',
    },
  ]

  it.each(cases)('$line -> unexplained=$unexplained ($note)', ({ line, unexplained }) => {
    const [entry] = parseRegistry(line)
    expect(entry, 'the synthetic line did not parse to an entry').toBeDefined()
    expect(isUnexplained(entry!)).toBe(unexplained)
  })
})
