import { execFileSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { isInside } from './paths/containment.js'

/**
 * prd-54's law — `.swarm/coupling.txt` checks itself (issue #367, wave 2).
 *
 * `.swarm/coupling.txt` is prose asserting facts about other files: that a law pins an
 * exact count, that a spelling occurs verbatim elsewhere, that a path exists. Nothing
 * checked any of that before this file — `scripts/dev/coupling.test.sh` runs in no
 * workflow, no `package.json` script and not in `scripts/gate.sh`, and
 * `doc-citation-law.test.ts` cannot reach a `.txt`. Every ruling this law implements is in
 * `docs/prds/done/prd-54-the-registry-that-checks-itself.md`; only the ones that changed the
 * law's behaviour, not the ones that only explained why, are repeated here.
 *
 * Lives under `packages/server/` for the reason every sibling law here already gives: the
 * root vitest config globs `packages/*`, so a root-level test would never run.
 *
 * ## What is checked, and by which ruling
 *
 * - **Ruling 10, presence.** Every entry's leading path exists, and its reason, trimmed,
 *   is non-empty and not a restatement of the leading path — by EQUALITY against both
 *   spellings of the path (the one `xargs` would produce and the one as typed), after one
 *   matched layer of a backtick/single/double quote is stripped from the reason. This is
 *   `scripts/dev/coupling.test.sh`'s own check, ported rather than re-derived — see
 *   `isUnexplained` below, and the test that runs both engines over the same file to prove
 *   they agree.
 * - **Ruling 7 (which is ruling 2's check).** A backticked span containing `.toBe(`,
 *   `.toHaveLength(` or `.toEqual(` is an assertion span. The **whole span**, whitespace
 *   included, must occur as an exact substring of the entry's leading-path file — not
 *   normalised, not parsed, and not reduced to the assertion call alone.
 * - **Ruling 8 (which replaces ruling 5's Extent, and is the whole path selector).** A
 *   backticked span is a path citation when it carries no glob metacharacter, every
 *   character is in `[A-Za-z0-9._/-]`, it does not begin with `/`, and it either contains
 *   `/`, or (not beginning with `.`) its final dot-separated segment is a tracked
 *   extension, or it is exactly a tracked file's basename. The extension and basename
 *   sets are derived from `git ls-files`, never written down (`trackedFileSets` below).
 *   The population is every backticked span in an entry's reason text; the freestanding
 *   `# ── section ──` comments between entries are not scanned, because they are never
 *   entered into `entries` in the first place — the same skip `coupling.test.sh` and
 *   `scripts/fence-lint.sh` both make.
 * - **Ruling 5's verdict (unchanged).** An admitted citation resolves repo-relative, or —
 *   only if the entry's own leading path lies inside a package source root — relative to
 *   that one root, and nowhere else. The root list is derived from the workspace's own
 *   `package.json` (`packageSourceRoots` below), never hardcoded. "Resolves" is existence
 *   (`-e`, ruling 8's Extent part two): a directory citation resolves.
 * - **Ruling 10, generated declarations.** The one form —
 *   `` `<generated>` is GENERATED by `<generator>` `` — exempts every occurrence of that
 *   generated-path text **within the same entry** from resolution (not merely the one
 *   span inside the declaration phrase: ruling 3 declares a path generated, not a single
 *   mention of it, and ruling 8's own amendment already counted both of
 *   `scripts/gate.sh`'s two `` `.swarm/timing-count` `` occurrences as "the declared
 *   occurrences" before ruling 10 existed to give the declaration a syntax). The generator
 *   must itself resolve under ruling 5's two attempts, and the generator file's text must
 *   contain the generated path.
 * - **Ruling 9.** Not separately enforced — a grep target, a family glob, or a
 *   second-hand shorthand spelled differently from its first mention all surface as a
 *   plain unresolved citation, which is the right verdict with the wrong message on its
 *   own; this law's failure text for an unresolved citation names ruling 9 so the reader
 *   is not sent to "the path moved" when the real fix is "quote it the way ruling 9 asks".
 * - **Ruling 11, enforced.** An entry whose leading path IS `.swarm/coupling.txt` itself —
 *   a self-citing entry — may not carry a backticked assertion span, full stop: not
 *   checked against the file the reason names, not exempted. Ruling 7's whole-span check
 *   is satisfied by the entry's OWN sentence when the leading-path file is the registry
 *   itself, which is a check that cannot fail — the same defect class ruling 6 already
 *   named for a different construction. Path citations are unaffected (Extent, ruling 11):
 *   they resolve against the tree, never against the entry's own file, so the defect this
 *   ruling closes does not arise there.
 *
 * ## Collection must not throw
 *
 * `gate-honesty-law.test.ts`'s anchor lookups run at module scope and throw when a search
 * matches zero lines, which takes every assertion in that file out of service at once for
 * one reworded line. Nothing here runs at module scope except reading the registry text
 * itself (parallel to every other law's `const SOURCE = readFileSync(...)`, safe because
 * the file is required to exist by `scripts/fence-lint.sh` already). Every filesystem read
 * that depends on what a given entry's reason actually says — resolving a citation,
 * reading a cited file's text — happens inside a test body, gated on `existsSync` first,
 * so a bad entry fails that one test rather than the whole file.
 */

const REPO_ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
const COUPLING_PATH = '.swarm/coupling.txt'
const COUPLING_SCRIPT_PATH = 'scripts/dev/coupling.test.sh'
/**
 * The self-citing comparison (ruling 11) is done against this RESOLVED absolute path, never
 * against `entry.path` as a raw string. `path.join` normalises `./` and `..` segments, so a
 * self-entry spelled `./.swarm/coupling.txt` or `docs/../.swarm/coupling.txt` — the same
 * file, a different string — still compares equal here; a raw `entry.path === COUPLING_PATH`
 * does not, and was found (round 1 review) to leave ruling 11 refusing nothing for those
 * spellings.
 *
 * KNOWN RESIDUAL, not fixed here: `path.join` normalises segments but does not resolve
 * symlinks or fold case. A self-entry reached through a symlinked path, or (on a
 * case-insensitive filesystem) a case-variant spelling, still compares unequal to
 * `COUPLING_ABS` and bypasses ruling 11 (round 2 review, EXECUTED). Recorded as a property
 * of this predicate, not a gap to close on this pass.
 */
const COUPLING_ABS = path.join(REPO_ROOT, COUPLING_PATH)

// ── parsing — must agree exactly with the registry read in scripts/fence-lint.sh's `── coupling points ──` block, and with scripts/dev/coupling.test.sh ──

interface RegistryEntry {
  readonly lineNo: number
  /** `${line%%#*}` — everything before the first `#`, unprocessed. */
  readonly rawField: string
  /** `rawField`, trimmed only (bash parameter-expansion trim, no quote/backslash handling). */
  readonly rawTrimmed: string
  /** `$(echo "$rawField" | xargs)` — the path fence-lint.sh and coupling.test.sh both compute. */
  readonly path: string
  /** `${line#*#}` — everything after the first `#` (the whole line, if there is no `#`). */
  readonly reason: string
  /** `reason`, trimmed only. */
  readonly reasonTrimmed: string
}

/**
 * `xargs`' own word-splitting: unquoted whitespace separates tokens, a matched pair of
 * single or double quotes groups one, a backslash escapes the next character, and the
 * result is the tokens rejoined with single spaces — exactly what
 * `$(echo "$raw" | xargs)` does to a registry line's leading field. Every path in the
 * registry today is a single unquoted token, so this only changes behaviour for a
 * hypothetical quoted or multiply-spaced path — which `coupling.test.sh`'s own comment
 * says is "unreachable on today's registry" and is exactly why it is ported rather than
 * approximated.
 */
function xargsNormalize(s: string): string {
  const tokens: string[] = []
  let current = ''
  let inToken = false
  let i = 0
  while (i < s.length) {
    const c = s[i]!
    if (c === ' ' || c === '\t' || c === '\n' || c === '\r') {
      if (inToken) {
        tokens.push(current)
        current = ''
        inToken = false
      }
      i++
      continue
    }
    inToken = true
    if (c === '\\') {
      i++
      if (i < s.length) {
        current += s[i]
        i++
      }
      continue
    }
    if (c === "'") {
      i++
      while (i < s.length && s[i] !== "'") {
        current += s[i]
        i++
      }
      i++
      continue
    }
    if (c === '"') {
      i++
      while (i < s.length && s[i] !== '"') {
        if (s[i] === '\\' && i + 1 < s.length && ['"', '\\', '$', '`'].includes(s[i + 1]!)) {
          current += s[i + 1]
          i += 2
        } else {
          current += s[i]
          i++
        }
      }
      i++
      continue
    }
    current += c
    i++
  }
  if (inToken) tokens.push(current)
  return tokens.join(' ')
}

/** Parses registry text with the same rules as the `${line%%#*}` / `${line#*#}` split inside `scripts/fence-lint.sh`'s `── coupling points ──` block and in `scripts/dev/coupling.test.sh` — blank lines and lines starting with `#` are skipped, everything else is one entry. Cited by the block it lives in, not by line number: that split sat at lines 79-81 when this law was written and at 218-220 one merge later (#549), and a pin to a number in a file that moves is what prd-54 exists to stop. */
function parseRegistry(text: string): RegistryEntry[] {
  const entries: RegistryEntry[] = []
  const lines = text.split('\n')
  lines.forEach((line, idx) => {
    if (line === '' || line.startsWith('#')) return
    const hashIdx = line.indexOf('#')
    const rawField = hashIdx === -1 ? line : line.slice(0, hashIdx)
    const reason = hashIdx === -1 ? line : line.slice(hashIdx + 1)
    const entryPath = xargsNormalize(rawField)
    if (entryPath === '') return
    entries.push({
      lineNo: idx + 1,
      rawField,
      rawTrimmed: rawField.trim(),
      path: entryPath,
      reason,
      reasonTrimmed: reason.trim(),
    })
  })
  return entries
}

const DELIMITERS = ['`', "'", '"'] as const

/** Strips at most one matched layer of a backtick, single, or double quote from both ends — the shell's `for d in '`' "'" '"'` loop, which `break`s on the first member that matches. */
function stripOneDelimiterLayer(s: string): string {
  for (const d of DELIMITERS) {
    if (s.length >= 2 && s.startsWith(d) && s.endsWith(d)) {
      return s.slice(1, -1)
    }
  }
  return s
}

/**
 * `scripts/dev/coupling.test.sh`'s "no reason given" check, ported exactly (prd-54 ruling
 * 10): EQUALITY, not containment, against both spellings of the leading path — the
 * canonical one `xargs` would produce and the one as typed — with at most one matched
 * delimiter layer stripped from the reason first.
 */
function isUnexplained(entry: RegistryEntry): boolean {
  const bare = stripOneDelimiterLayer(entry.reasonTrimmed)
  return (
    entry.reasonTrimmed === '' ||
    entry.reasonTrimmed === entry.path ||
    entry.reasonTrimmed === entry.rawTrimmed ||
    bare === entry.path ||
    bare === entry.rawTrimmed
  )
}

// ── ruling 8's derived sets, and ruling 5's derived package roots ──

interface TrackedSets {
  readonly extensions: ReadonlySet<string>
  readonly basenames: ReadonlySet<string>
}

let trackedSetsCache: TrackedSets | undefined

/** Every tracked file's basename, and every tracked (non-dotfile) basename's final dot-segment — derived from `git ls-files`, never written down (ruling 8's own requirement of its own extension list, applied to itself). */
function trackedFileSets(): TrackedSets {
  if (trackedSetsCache) return trackedSetsCache
  const files = execFileSync('git', ['ls-files'], { cwd: REPO_ROOT, encoding: 'utf8' })
    .split('\n')
    .filter((f) => f.length > 0)
  const extensions = new Set<string>()
  const basenames = new Set<string>()
  for (const f of files) {
    const base = path.basename(f)
    basenames.add(base)
    if (!base.startsWith('.') && base.includes('.')) {
      extensions.add(base.slice(base.lastIndexOf('.') + 1))
    }
  }
  trackedSetsCache = { extensions, basenames }
  return trackedSetsCache
}

let packageRootsCache: readonly string[] | undefined

/** Every workspace package's source root (`packages/<name>/src`), derived from root `package.json`'s own `workspaces` globs plus which of those directories actually carry a `package.json` — never a hardcoded list (ruling 5's own requirement). */
function packageSourceRoots(): readonly string[] {
  if (packageRootsCache) return packageRootsCache
  const rootPkg = JSON.parse(readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')) as {
    workspaces?: readonly string[]
  }
  const roots: string[] = []
  for (const pattern of rootPkg.workspaces ?? []) {
    const m = /^(.*)\/\*$/.exec(pattern)
    if (!m) continue
    const baseDir = m[1]!
    const absBase = path.join(REPO_ROOT, baseDir)
    if (!existsSync(absBase)) continue
    for (const name of readdirSync(absBase).sort()) {
      if (existsSync(path.join(absBase, name, 'package.json'))) {
        roots.push(`${baseDir}/${name}/src`)
      }
    }
  }
  packageRootsCache = roots
  return roots
}

// ── ruling 7's assertion spans, and ruling 8's path-citation clauses ──

interface BacktickSpan {
  readonly start: number
  readonly text: string
}

/** Every backtick-delimited span in `text`, in order — the population ruling 8's clauses and ruling 7's selector both draw from. */
function extractBacktickSpans(text: string): BacktickSpan[] {
  const spans: BacktickSpan[] = []
  const re = /`([^`]+)`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text))) {
    spans.push({ start: m.index + 1, text: m[1]! })
  }
  return spans
}

/** Ruling 7's selector, widened to any assertion call: `.toBe(`, `.toHaveLength(`, or `.toEqual(`, whatever its argument. */
function isAssertionSpan(span: string): boolean {
  return span.includes('.toBe(') || span.includes('.toHaveLength(') || span.includes('.toEqual(')
}

const GLOB_CHARS = new Set(['*', '?', '[', ']', '{', '}'])
const PATH_CHAR_CLASS_RE = /^[A-Za-z0-9._/-]+$/

type PathClause = '4a' | '4b' | '4c'

/** Ruling 8's four clauses. Deliberately disjoint from `isAssertionSpan`: clause 2's character class rejects every span an assertion call selects, because an assertion span always carries parentheses. */
function pathCitationClause(span: string, sets: TrackedSets): PathClause | undefined {
  for (const ch of span) if (GLOB_CHARS.has(ch)) return undefined
  if (!PATH_CHAR_CLASS_RE.test(span)) return undefined
  if (span.startsWith('/')) return undefined
  if (span.includes('/')) return '4a'
  if (!span.startsWith('.') && span.includes('.')) {
    const ext = span.slice(span.lastIndexOf('.') + 1)
    if (sets.extensions.has(ext)) return '4b'
  }
  if (sets.basenames.has(span)) return '4c'
  return undefined
}

interface GeneratedDeclaration {
  readonly generated: string
  readonly generator: string
}

/** Ruling 10's one declaration form: `` `<generated>` is GENERATED by `<generator>` `` — the literal text between two backticked spans, and nothing looser. */
function extractGeneratedDeclarations(text: string): GeneratedDeclaration[] {
  const out: GeneratedDeclaration[] = []
  const re = /`([^`]+)` is GENERATED by `([^`]+)`/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text))) out.push({ generated: m[1]!, generator: m[2]! })
  return out
}

interface Resolution {
  readonly resolved: boolean
  readonly resolvedAbsPath?: string
  readonly attempted: readonly string[]
}

/**
 * Is `entryPath` (repo-relative) `root` itself or somewhere beneath it?
 *
 * Delegates to `paths/containment.ts`'s `isInside` rather than a raw
 * `entryPath.startsWith(root + '/')` — not for symlink safety (both sides are
 * workspace source directories, not caller-supplied paths), but because that
 * shape is exactly what `paths/prefix-comparison-law.test.ts` hunts, and
 * `containment.ts` is the one file that law's own sweep excludes by name.
 * Reaching for the shared primitive here is what that law's own registry
 * entry recommends instead of growing its known-debt count by one.
 */
function isOwnPackageRoot(entryPath: string, root: string): boolean {
  const absEntry = path.join(REPO_ROOT, entryPath)
  const absRoot = path.join(REPO_ROOT, root)
  return absEntry === absRoot || isInside(absRoot, absEntry)
}

/**
 * `existsSync(absPath)`, AND `absPath` resolves inside the repository — never merely
 * "some file on this machine happens to exist at the joined string".
 *
 * `path.join(REPO_ROOT, candidate)` happily walks a `../`-shaped `candidate` out of the
 * repo, and a bare `existsSync` on the result cannot tell a real registry citation from a
 * citation that escaped to the operator's home directory, the filesystem root, or anywhere
 * else a real file or directory happens to sit. Ruling 5's two attempts are both
 * REPO-RELATIVE by definition — resolving outside the repo is not a third attempt, it is a
 * wrong answer to the first two. This is the one predicate every existence check in this
 * file goes through, rather than a `../` string-match bolted onto each call site
 * separately (see the predicate table in the commit body: three ad hoc guards would have
 * been the same defect three times over, not three fixes).
 */
function existsInsideRepo(absPath: string): boolean {
  if (!existsSync(absPath)) return false
  return absPath === REPO_ROOT || isInside(REPO_ROOT, absPath)
}

/** Ruling 5's two attempts, in order, and ruling 8's `-e` predicate (existence — a directory resolves) — bounded to the repo by `existsInsideRepo`. */
function resolveCitation(candidate: string, entryPath: string, pkgRoots: readonly string[]): Resolution {
  const attempted: string[] = []
  const repoRelAbs = path.join(REPO_ROOT, candidate)
  attempted.push(`repo-relative (${candidate})`)
  if (existsInsideRepo(repoRelAbs)) return { resolved: true, resolvedAbsPath: repoRelAbs, attempted }

  const ownRoot = pkgRoots.find((r) => isOwnPackageRoot(entryPath, r))
  if (ownRoot) {
    const pkgRelAbs = path.join(REPO_ROOT, ownRoot, candidate)
    attempted.push(`under its own package root ${ownRoot} (${path.posix.join(ownRoot, candidate)})`)
    if (existsInsideRepo(pkgRelAbs)) return { resolved: true, resolvedAbsPath: pkgRelAbs, attempted }
  }
  return { resolved: false, attempted }
}

/** Reads `absPath`'s text if it names an existing, readable, regular file inside the repo — never throws. */
function readFileIfFile(absPath: string): string | undefined {
  try {
    if (!existsInsideRepo(absPath) || !statSync(absPath).isFile()) return undefined
    return readFileSync(absPath, 'utf8')
  } catch {
    return undefined
  }
}

const MENTION_TRAILING_CHAR_RE = /[A-Za-z0-9._/-]/
/**
 * Characters the leading walk crosses OUTSIDE an open `{...}`/`(...)`: plain path
 * characters, `$`, parens (to ENTER a `$(cmd)`, tracked below) and a quote mark (for a
 * quoted interpolation) — everything a shell interpolation or a merge attempt can be
 * built from at the top level.
 */
const MENTION_PREFIX_OUTER_RE = /[A-Za-z0-9_./$()"-]/

/**
 * One interpolation token: `${name}`/`${digits}` optionally with a parameter-expansion
 * operator tail, `$name`, a SINGLE-digit positional parameter `$N` (real shell: `$10` is
 * `$1` followed by a literal `0`, not one token — braces are required for two or more
 * digits, `${10}`), or a command substitution `$(cmd)`.
 */
const MENTION_INTERPOLATION = String.raw`(?:\$\{(?:[A-Za-z_]\w*|[0-9]+)[^{}]*\}|\$[A-Za-z_]\w*|\$[0-9]|\$\([^()]*\))`
/**
 * The whitelist of legitimate non-empty leading prefixes: one interpolation immediately
 * followed by `/`, unquoted, quoted-and-closed-before-the-slash, or quoted-and-still-open
 * (the real quote closes somewhere after the needle, which this check never needs to see).
 * Anything else non-empty is a merge onto a longer name or an extra path segment.
 */
const MENTION_LEGITIMATE_PREFIXES: readonly RegExp[] = [
  new RegExp(`^${MENTION_INTERPOLATION}/$`),
  new RegExp(`^"${MENTION_INTERPOLATION}"/$`),
  new RegExp(`^"${MENTION_INTERPOLATION}/$`),
]

/**
 * True when `haystack` mentions `needle` as a COMPLETE path token, not merely as a
 * fragment of a longer, DIFFERENT name, and not as a DIFFERENT path that merely ends the
 * same way (ruling 10: the generator must NAME the declared path). Both edges are bounded,
 * and by different rules, because a path is built differently on each side:
 *
 * - TRAILING (unchanged since round 1): the character immediately after the match must
 *   not be one that would extend it into a different name — `[A-Za-z0-9._/-]`, the same
 *   class ruling 8 uses for a path citation.
 * - LEADING: walk BACK from the match through everything that could plausibly be part of
 *   a shell value expression — plain path characters, `$`, parens, a quote, and (only
 *   while inside a matched `{...}` OR `(...)`, tracked by depth as the walk crosses them
 *   right-to-left) ANYTHING except a newline — operator characters (`%`, `#`, `:`, `+`,
 *   `=`, `?`) and whitespace both, since both are ordinary INSIDE a parameter expansion or
 *   a command substitution and mean something else (or nothing) at the top level. A
 *   trailing run of self-referential `/./ ` segments is then stripped before validating
 *   (`stripCurrentDirSegments`) — `.` is a path no-op, not an extra segment, and folding it
 *   away is what tells it apart from a genuine one. Round 1 required only `$name`/`${name}`
 *   and rejected four real, independently-found generator spellings (round 2 review,
 *   EXECUTED); the repair that closed those (round 3) was in turn too permissive in one
 *   direction and too narrow in three others (round 3 review, EXECUTED):
 *     `$root"/.swarm/timing-count` and unbraced `$10/...`   — OVER-admitted: `$10` read as
 *       one positional token, but bash expands it as `$1` then a literal `0`
 *     `$(dirname "$0")/...`, `$(cd sub && pwd)/...`         — falsely REJECTED: any
 *       whitespace inside `$(...)` stopped the walk before the whitelist saw a complete token
 *     `$root/./.swarm/timing-count`                         — falsely REJECTED: a `.`
 *       segment read as a different, extra path segment
 *   All are covered now. An intervening REAL path segment (`$root/nested/.swarm/timing-count`,
 *   round 1's own reachable defect) still fails, because the whole normalised span must
 *   match one complete form and two real segments never do; neither does a bare merge like
 *   `cache.swarm/...` or `relay_.swarm/...`.
 *
 * Two things this cannot close, recorded rather than silently accepted as closed:
 * - A mention inside a COMMENT or an error string is textually indistinguishable from a
 *   mention in a write — this check has no notion of "shell comment" or "string literal",
 *   only of adjacent characters.
 * - A generator that builds the path by variable indirection (`d="$root/.swarm";
 *   C="$d/timing-count"`) is wrongly REJECTED: the generated text `.swarm/timing-count`
 *   never appears contiguously in the generator's own source in that shape at all.
 * - NESTED command substitution (`$(foo $(bar))`) is walked correctly (paren depth tracks
 *   it) but still fails the WHITELIST: `MENTION_INTERPOLATION`'s command-substitution
 *   branch, `[^()]*`, excludes any paren, so a nested pair inside the captured span breaks
 *   that alternative. Narrower than round 3's note (which blamed the walk); the walk is
 *   fine now, the validation regex is the remaining boundary.
 */
function mentionsWholePath(haystack: string, needle: string): boolean {
  let searchFrom = 0
  for (;;) {
    const idx = haystack.indexOf(needle, searchFrom)
    if (idx === -1) return false
    searchFrom = idx + 1

    const after = haystack[idx + needle.length]
    if (after !== undefined && MENTION_TRAILING_CHAR_RE.test(after)) continue

    const prefix = stripCurrentDirSegments(walkMentionPrefix(haystack, idx))
    if (prefix === '' || prefix === '"' || MENTION_LEGITIMATE_PREFIXES.some((re) => re.test(prefix))) {
      return true
    }
  }
}

/**
 * Walks backward from `idx`, tracking brace AND paren depth so operator characters and
 * whitespace are only ever consumed while genuinely inside a matched `{...}` or `(...)`,
 * never at the top level where the same characters mean something else entirely (`=` is a
 * shell assignment operator there, a space ends a token). Depths are independent counters,
 * not a shared stack — a mismatched pair (an unbalanced stray `{` or `(`) stops the walk
 * rather than guessing.
 */
function walkMentionPrefix(haystack: string, idx: number): string {
  let i = idx
  let braceDepth = 0
  let parenDepth = 0
  while (i > 0) {
    const c = haystack[i - 1]!
    if (c === '}') {
      braceDepth++
      i--
      continue
    }
    if (c === '{') {
      if (braceDepth === 0) break
      braceDepth--
      i--
      continue
    }
    if (c === ')') {
      parenDepth++
      i--
      continue
    }
    if (c === '(') {
      if (parenDepth === 0) break
      parenDepth--
      i--
      continue
    }
    if (braceDepth > 0 || parenDepth > 0) {
      if (c === '\n') break
      i--
      continue
    }
    if (MENTION_PREFIX_OUTER_RE.test(c)) {
      i--
      continue
    }
    break
  }
  return haystack.slice(i, idx)
}

/** Folds away a trailing run of `./` segments — `$root/./` is `$root/`, a path no-op, not an extra segment the way `$root/nested/` is. */
function stripCurrentDirSegments(prefix: string): string {
  let p = prefix
  while (p.endsWith('./')) p = p.slice(0, -2)
  return p
}

// ── per-entry analysis ──

interface EntryAnalysis {
  readonly entry: RegistryEntry
  readonly violations: readonly string[]
  readonly totalBacktickSpans: number
  readonly assertionSpansSelected: number
  readonly pathCitationsAdmitted: number
  readonly pathCitationsResolved: number
  readonly pathCitationsExempt: number
}

/**
 * Presence (ruling 10: existence, reason-honesty) is verified by asserting the REAL OUTPUT
 * against KNOWN-bad synthetic entries (see the `presence checks actually flag a KNOWN
 * stale path and a KNOWN unexplained reason` describe block below), not by any side-channel
 * "did it run" signal on `analyzeEntry` itself. Two such signals were tried and both were
 * defeated, three times over:
 *
 * - round 1: `Number.isInteger(t.backtickSpans)` — true by construction for any array
 *   length, checked or not.
 * - round 2: `presenceChecked: boolean`, a bare `const presenceChecked = true` positioned
 *   after the two checks — three mutations that skip the checks (both guards replaced
 *   with `if (false)`; both wrapped in an unrelated `if`; an early return before either
 *   check runs) all left it `true`, because "control flow reached this line" and "the
 *   checks ran" are different facts and the field only ever recorded the first one.
 * - round 3 (this file's own second attempt): an external tracker interface, recording
 *   into a caller-owned counter via a `tracker.record(entry.lineNo)` call placed before
 *   each check. Still defeated: `record` is a SEPARATE STATEMENT from the check it sits
 *   beside, so deleting the check's body entirely (`existsInsideRepo(leadingAbs)` and its
 *   `if`) while leaving both `record` calls untouched left the tracker reporting 2/2 with
 *   a genuinely stale entry undetected end to end (round 2 review, EXECUTED).
 *
 * Three defeats of the same instrument is the stopping rule: no fourth "did it run" flag.
 * A synthetic entry with a KNOWN-wrong leading path, run through the REAL `analyzeEntry`,
 * makes "the check ran and was wired correctly" the only way to pass — there is no
 * separate signal to leave behind while deleting the logic that produces it.
 */
function analyzeEntry(entry: RegistryEntry, sets: TrackedSets, pkgRoots: readonly string[]): EntryAnalysis {
  const violations: string[] = []

  const leadingAbs = path.join(REPO_ROOT, entry.path)

  if (!existsInsideRepo(leadingAbs)) {
    violations.push(`leading path does not exist inside the repo (prd-54 ruling 10, presence): ${entry.path}`)
  }

  if (isUnexplained(entry)) {
    violations.push(
      `reason is empty, or restates its own leading path under equality (prd-54 ruling 10, presence): ${JSON.stringify(entry.reason)}`,
    )
  }

  const spans = extractBacktickSpans(entry.reason)
  const declarations = extractGeneratedDeclarations(entry.reason)
  const declaredGeneratedTexts = new Set(declarations.map((d) => d.generated))
  const citedFileText = readFileIfFile(leadingAbs)

  let assertionSpansSelected = 0
  let pathCitationsAdmitted = 0
  let pathCitationsResolved = 0
  let pathCitationsExempt = 0

  for (const span of spans) {
    if (isAssertionSpan(span.text)) {
      assertionSpansSelected++
      if (leadingAbs === COUPLING_ABS) {
        // Ruling 11: a self-citing entry's leading-path file IS the registry, so ruling
        // 7's whole-span check below would be satisfied by the entry's OWN sentence — a
        // check that cannot fail. Refused outright rather than checked or exempted.
        // Compared as RESOLVED absolute paths (`leadingAbs`/`COUPLING_ABS`), not as raw
        // strings — `./.swarm/coupling.txt` is the same file under a different spelling,
        // and a raw `entry.path === COUPLING_PATH` missed it (round 1 review).
        violations.push(
          `self-citing entry carries an assertion span (prd-54 ruling 11) — refused, not checked: a self-citing ` +
            `entry's leading-path file is this registry itself, so the span would be satisfied by its own ` +
            `sentence. Move it into unbackticked prose: \`${span.text}\``,
        )
        continue
      }
      if (citedFileText === undefined) {
        violations.push(
          `assertion span cannot be checked — ${entry.path} is not a readable file (prd-54 ruling 7): \`${span.text}\``,
        )
      } else if (!citedFileText.includes(span.text)) {
        violations.push(
          `assertion span does not occur verbatim (whitespace included) in ${entry.path} (prd-54 ruling 7): \`${span.text}\``,
        )
      }
      continue
    }

    const clause = pathCitationClause(span.text, sets)
    if (!clause) continue
    pathCitationsAdmitted++

    if (declaredGeneratedTexts.has(span.text)) {
      pathCitationsExempt++
      continue
    }

    const resolution = resolveCitation(span.text, entry.path, pkgRoots)
    if (resolution.resolved) {
      pathCitationsResolved++
    } else {
      violations.push(
        `path citation (clause ${clause}) does not resolve — tried ${resolution.attempted.join('; ')}. ` +
          `Check prd-54 ruling 9 before assuming the path moved: a grep target, a family shorthand, or a ` +
          `second-hand mention spelled differently from its first mention all look like this. \`${span.text}\``,
      )
    }
  }

  for (const decl of declarations) {
    const resolution = resolveCitation(decl.generator, entry.path, pkgRoots)
    if (!resolution.resolved) {
      violations.push(
        `declared generator does not resolve (prd-54 ruling 10) — tried ${resolution.attempted.join('; ')}: ` +
          `\`${decl.generator}\` for \`${decl.generated}\``,
      )
      continue
    }
    const generatorText = readFileIfFile(resolution.resolvedAbsPath!)
    if (generatorText === undefined || !mentionsWholePath(generatorText, decl.generated)) {
      violations.push(
        `declared generator \`${decl.generator}\` does not name its generated path as a whole token, ` +
          `not merely as a prefix of a longer one (prd-54 ruling 10): \`${decl.generated}\``,
      )
    }
  }

  return {
    entry,
    violations,
    totalBacktickSpans: spans.length,
    assertionSpansSelected,
    pathCitationsAdmitted,
    pathCitationsResolved,
    pathCitationsExempt,
  }
}

function sum(ns: readonly number[]): number {
  return ns.reduce((a, b) => a + b, 0)
}

function extractPrefixedPaths(output: string, prefix: string): string[] {
  return output
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith(prefix))
    .map((line) => line.slice(prefix.length))
}

// ── the law ──

describe('coupling registry law: .swarm/coupling.txt checks itself (prd-54, #367)', () => {
  const registryText = readFileSync(path.join(REPO_ROOT, COUPLING_PATH), 'utf8')
  const entries = parseRegistry(registryText)

  it('the registry parses to at least one entry — a law that checks nothing is worse than no law', () => {
    expect(entries.length).toBeGreaterThan(0)
  })

  it.each(entries.map((e) => [e.lineNo, e.path, e] as const))(
    'line %i: %s — leading path exists, reason is honest, every checked citation resolves',
    (_lineNo, _p, entry) => {
      const analysis = analyzeEntry(entry, trackedFileSets(), packageSourceRoots())
      expect(analysis.violations).toEqual([])
    },
  )

  it('proves it looked: reports every entry\'s span/selection counts, and the registry-wide totals are not zero', () => {
    const sets = trackedFileSets()
    const pkgRoots = packageSourceRoots()
    const analyses = entries.map((e) => analyzeEntry(e, sets, pkgRoots))

    const table = analyses.map((a) => ({
      lineNo: a.entry.lineNo,
      path: a.entry.path,
      backtickSpans: a.totalBacktickSpans,
      assertionSpansSelected: a.assertionSpansSelected,
      pathCitationsAdmitted: a.pathCitationsAdmitted,
      pathCitationsResolved: a.pathCitationsResolved,
      pathCitationsExempt: a.pathCitationsExempt,
    }))
    const totals = {
      entries: entries.length,
      backtickSpans: sum(table.map((t) => t.backtickSpans)),
      assertionSpansSelected: sum(table.map((t) => t.assertionSpansSelected)),
      pathCitationsAdmitted: sum(table.map((t) => t.pathCitationsAdmitted)),
      pathCitationsResolved: sum(table.map((t) => t.pathCitationsResolved)),
      pathCitationsExempt: sum(table.map((t) => t.pathCitationsExempt)),
    }
    console.log('coupling registry law — per-entry breakdown:\n' + JSON.stringify(table, null, 2))
    console.log('coupling registry law — totals:', JSON.stringify(totals))

    expect(
      totals.assertionSpansSelected,
      'ruling 7 selected zero assertion spans across the whole registry — the selector is broken, not the registry',
    ).toBeGreaterThan(0)
    expect(
      totals.pathCitationsAdmitted,
      'ruling 8 admitted zero path citations across the whole registry — the selector is broken, not the registry',
    ).toBeGreaterThan(0)
  })

  // Presence (ruling 10: existence, reason-honesty) is verified against KNOWN-bad
  // synthetic entries here, not by any "did it run" side-channel — see analyzeEntry's own
  // doc comment for the three prior attempts at that (an always-true integer check, a
  // positional boolean, an external tracker) and why each was defeated. There is no
  // signal to fake here: the assertion is the real `violations` output of the real
  // function, so the only way to pass is for the check to have actually run and been
  // wired into `violations` correctly.
  describe('presence checks actually flag a KNOWN stale path and a KNOWN unexplained reason', () => {
    // trackedFileSets()/packageSourceRoots() are called INSIDE each `it`, not once at this
    // describe callback's scope — a `describe` body runs at COLLECTION time, before any
    // test is selected to run, which is exactly the anti-pattern this file's own header
    // (above, "Collection must not throw") names `gate-honesty-law.test.ts` for: an
    // unavailable `git ls-files` there took every assertion in that file out of service at
    // once, for one reworded line (round 3 review, EXECUTED: this file had the same
    // property at collection scope — `git ls-files` throwing left ALL 93 tests unreported
    // as "no tests", where calling it per-`it` instead leaves every OTHER test unaffected
    // and names the one that failed). Both functions are memoised, so calling them from
    // three separate `it`s costs one real `git ls-files`/`readdirSync` pass, not three.
    it('flags a leading path that does not exist', () => {
      const [entry] = parseRegistry('does/not/exist/for-a-presence-probe.ts  # a genuine, honest reason\n')
      const analysis = analyzeEntry(entry!, trackedFileSets(), packageSourceRoots())
      expect(analysis.violations.some((v) => v.includes('does not exist inside the repo'))).toBe(true)
    })

    it('flags a reason that restates its own leading path', () => {
      const [entry] = parseRegistry('docs/adr/README.md  # docs/adr/README.md\n')
      const analysis = analyzeEntry(entry!, trackedFileSets(), packageSourceRoots())
      expect(analysis.violations.some((v) => v.includes('restates its own leading path'))).toBe(true)
    })

    it('does NOT flag a healthy entry (control)', () => {
      const [entry] = parseRegistry('README.md  # a real, honest reason naming what couples here\n')
      const analysis = analyzeEntry(entry!, trackedFileSets(), packageSourceRoots())
      expect(analysis.violations.filter((v) => v.includes('prd-54 ruling 10, presence'))).toEqual([])
    })

    // RECORDED, NOT FIXED (round 3 review): every synthetic fixture above parses a
    // one-line registry, so each entry's `lineNo` is 1 — a guard keyed on
    // `entry.lineNo === 1` (never a plausible accidental simplification; nothing else in
    // this file keys behaviour on which line an entry came from) would defeat this
    // control specifically without defeating presence checking generically. Left as a
    // known, bounded property of these three fixtures rather than closed by threading a
    // second-line synthetic registry through every case: the realistic mutation shapes
    // (a guard neutered, a guard misfiled, an early return) are what this describe block
    // exists to survive, and none of them have this shape.
  })

  it('agrees with scripts/dev/coupling.test.sh about which paths are stale and which reasons are unexplained', { timeout: 20_000 }, () => {
    let shellOutput: string
    try {
      shellOutput = execFileSync('bash', [path.join(REPO_ROOT, COUPLING_SCRIPT_PATH)], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
      })
    } catch (err) {
      shellOutput = (err as { stdout?: string }).stdout ?? ''
    }

    // The precondition is the POPULATION, not the summary. A script that emits a genuine
    // "<N> passed, <M> failed" line — or even a genuine "ok 0 entries parsed" — before
    // examining a single entry still satisfies a check that only asks "did it speak"; a
    // script replaced with one that prints that exact summary and exits before its entry
    // loop stays GREEN against that check, comparing two empty sets and passing vacuously,
    // which is the precise failure "prove the agreement, do not assert it" exists to rule
    // out. What proves the two engines looked at the same registry is the script's own
    // "entries parsed" line — `ok    $entries entries parsed`, or a bare `FAIL  entries
    // parsed` when it found none — compared against this law's own `entries.length` from
    // the same file. A disagreement in population is its own failure, distinct from a
    // disagreement in verdict below.
    const okMatch = /^\s*ok\s+(\d+) entries parsed$/m.exec(shellOutput)
    const failMatch = /^\s*FAIL\s+entries parsed$/m.exec(shellOutput)
    expect(
      okMatch ?? failMatch,
      "scripts/dev/coupling.test.sh produced no 'entries parsed' line at all — it did not run far enough to report a population, so the agreement below would compare two empty sets and pass vacuously",
    ).not.toBeNull()
    const shellEntryCount = okMatch ? Number(okMatch[1]) : 0
    expect(
      shellEntryCount,
      `scripts/dev/coupling.test.sh reports ${shellEntryCount} entries parsed but this law parsed ${entries.length} from the same file — the two engines examined different populations, so any agreement on missing/unexplained sets below proves nothing`,
    ).toBe(entries.length)

    // What population agreement does NOT prove, on its own: today's real registry has zero
    // stale paths and zero unexplained reasons, so the set comparison below is empty
    // against empty regardless of whether either engine's DETECTION logic is intact — a
    // stub that prints the correct count but never inspects a single entry satisfies
    // population agreement AND this empty-vs-empty comparison (round 1 review, EXECUTED:
    // a five-line stub printing `ok 52 entries parsed` and a matching pass/fail summary,
    // exiting before any entry loop, passed both). That the two engines' DETECTION agrees
    // on a KNOWN-bad case is proven separately, against a synthetic registry, by the next
    // test — this one only proves they parsed the same real file into the same count.
    const shellMissing = new Set(extractPrefixedPaths(shellOutput, 'no such path: '))
    const shellUnexplained = new Set(extractPrefixedPaths(shellOutput, 'no reason given: '))

    const lawMissing = new Set(entries.filter((e) => !existsInsideRepo(path.join(REPO_ROOT, e.path))).map((e) => e.path))
    const lawUnexplained = new Set(entries.filter((e) => isUnexplained(e)).map((e) => e.path))

    expect(lawMissing, 'the law and scripts/dev/coupling.test.sh disagree on which leading paths are stale').toEqual(
      shellMissing,
    )
    expect(
      lawUnexplained,
      'the law and scripts/dev/coupling.test.sh disagree on which reasons are unexplained',
    ).toEqual(shellUnexplained)
  })

  it(
    'the shell/law agreement is load-bearing: both engines catch a KNOWN stale path and a KNOWN unexplained reason',
    { timeout: 20_000 },
    () => {
      // Round 1 review: the test above is vacuous on detection, because the real registry
      // has nothing stale or unexplained for either engine to disagree about. This test
      // gives both engines a registry with exactly one of each, in an isolated git
      // worktree — never the real `.swarm/coupling.txt`, so there is no shared-file risk
      // with any other test or worker reading it concurrently.
      const SYNTHETIC_STALE_PATH = 'does/not/exist/anywhere.ts'
      const SYNTHETIC_UNEXPLAINED_PATH = 'docs/adr/README.md'
      const syntheticRegistry =
        `${SYNTHETIC_STALE_PATH}  # a genuine, honest reason so only presence is at issue\n` +
        `${SYNTHETIC_UNEXPLAINED_PATH}  # ${SYNTHETIC_UNEXPLAINED_PATH}\n`

      // The shell engine under test is read from REPO_ROOT (the absolute path, exactly as
      // the sibling test above does) even though `cwd` is the synthetic worktree. Passing
      // the bare relative `COUPLING_SCRIPT_PATH` here was found (round 2 review, EXECUTED:
      // renaming this script's own "no such path: " wording in the working tree only left
      // the whole law, this test included, 65/65 green) to make bash resolve the script
      // inside `tmpDir`'s OWN checkout — HEAD's frozen copy of the shell engine, not the
      // one this test is meant to exercise. In an amend workflow HEAD == the working tree
      // at the moment the test runs, which is exactly why that was invisible until a
      // reviewer changed the SCRIPT rather than the registry.
      const tmpDir = mkdtempSync(path.join(tmpdir(), 'coupling-synth-'))
      let worktreeAdded = false
      try {
        execFileSync('git', ['worktree', 'add', '--quiet', '--detach', tmpDir, 'HEAD'], { cwd: REPO_ROOT })
        worktreeAdded = true
        writeFileSync(path.join(tmpDir, COUPLING_PATH), syntheticRegistry, 'utf8')

        let shellOutput: string
        try {
          shellOutput = execFileSync('bash', [path.join(REPO_ROOT, COUPLING_SCRIPT_PATH)], {
            cwd: tmpDir,
            encoding: 'utf8',
          })
        } catch (err) {
          shellOutput = (err as { stdout?: string }).stdout ?? ''
        }
        const shellMissing = new Set(extractPrefixedPaths(shellOutput, 'no such path: '))
        const shellUnexplained = new Set(extractPrefixedPaths(shellOutput, 'no reason given: '))

        expect(shellMissing, 'the shell script did not report the KNOWN stale path in the synthetic registry').toEqual(
          new Set([SYNTHETIC_STALE_PATH]),
        )
        expect(
          shellUnexplained,
          'the shell script did not report the KNOWN unexplained reason in the synthetic registry',
        ).toEqual(new Set([SYNTHETIC_UNEXPLAINED_PATH]))

        const syntheticEntries = parseRegistry(syntheticRegistry)
        const lawMissing = new Set(
          syntheticEntries.filter((e) => !existsInsideRepo(path.join(REPO_ROOT, e.path))).map((e) => e.path),
        )
        const lawUnexplained = new Set(syntheticEntries.filter((e) => isUnexplained(e)).map((e) => e.path))

        expect(lawMissing, 'the law did not report the KNOWN stale path in the synthetic registry').toEqual(
          new Set([SYNTHETIC_STALE_PATH]),
        )
        expect(
          lawUnexplained,
          'the law did not report the KNOWN unexplained reason in the synthetic registry',
        ).toEqual(new Set([SYNTHETIC_UNEXPLAINED_PATH]))

        expect(lawMissing, 'the law and the shell script disagree on the synthetic stale path').toEqual(shellMissing)
        expect(
          lawUnexplained,
          'the law and the shell script disagree on the synthetic unexplained reason',
        ).toEqual(shellUnexplained)
      } finally {
        // `worktreeAdded` guards the removal: if `git worktree add` itself failed, `tmpDir`
        // was never registered as a worktree, and calling `git worktree remove` on it
        // would ALSO fail — and in a `finally`, that second failure REPLACES the first in
        // the thrown error (round 2 review, EXECUTED: confirmed via Node's own
        // finally-throw-overrides-try-throw semantics), so a real setup failure would
        // report as a cleanup failure and hide its own cause. `rmSync` on the plain
        // directory runs unconditionally either way, so a leaked `mkdtemp` directory never
        // survives this test regardless of which step failed.
        //
        // `--force` DOUBLED, not once: a single `--force` removes a DIRTY worktree but
        // refuses a LOCKED one outright ("use 'remove -f -f' to override or unlock first" —
        // confirmed against the real git binary), and `git worktree prune` does not clear a
        // locked worktree's metadata either, by design. A single-`--force` attempt that
        // fails on a lock left permanent admin-directory metadata behind after `rmSync`
        // deleted the underlying directory (round 3 review, EXECUTED). Nothing in this test
        // locks the worktree itself, but the removal must not depend on that remaining true.
        if (worktreeAdded) {
          try {
            execFileSync('git', ['worktree', 'remove', '--force', '--force', tmpDir], { cwd: REPO_ROOT })
          } catch {
            // best-effort — the directory removal below still runs
          }
        }
        rmSync(tmpDir, { recursive: true, force: true })
      }
    },
  )

  it("scripts/dev/coupling.test.sh points at this law's full path, so the two cannot silently diverge", () => {
    const scriptText = readFileSync(path.join(REPO_ROOT, COUPLING_SCRIPT_PATH), 'utf8')
    expect(scriptText).toContain('packages/server/src/coupling-registry-law.test.ts')
  })
})

/**
 * The generator-declaration form table (prd-54 ruling 10), in the tree rather than only in
 * a review comment — round 2 review found four real generator spellings this check
 * rejected (`"$root"/`, `$(pwd)/`, a positional `$1/`, `${root%/}/`) that no test here would
 * have caught, because the only exercised case was the one real line in `scripts/gate.sh`.
 * Round 3 review found the round-2 repair had, in turn, over-admitted an unbraced
 * multi-digit positional (`$10/`) and still falsely rejected whitespace inside a command
 * substitution and a self-referential `./` segment — the same lesson twice: a table this
 * cheap earns its keep exactly at the moment a fix for one direction risks the other.
 * Needs no fixture: `mentionsWholePath` takes plain strings.
 */
describe('mentionsWholePath recognizes every legitimate generator-declaration shape (prd-54 ruling 10)', () => {
  const NEEDLE = '.swarm/timing-count'
  const cases: readonly { readonly haystack: string; readonly mentions: boolean; readonly note: string }[] = [
    { haystack: NEEDLE, mentions: true, note: 'bare' },
    { haystack: `"${NEEDLE}"`, mentions: true, note: 'bare, quoted' },
    { haystack: `$root/${NEEDLE}`, mentions: true, note: 'interpolated behind a variable' },
    { haystack: `\${root}/${NEEDLE}`, mentions: true, note: 'interpolated, braced' },
    { haystack: `\${root%/}/${NEEDLE}`, mentions: true, note: 'interpolated, braced, with a trim operator' },
    { haystack: `$1/${NEEDLE}`, mentions: true, note: 'a positional parameter' },
    { haystack: `$(pwd)/${NEEDLE}`, mentions: true, note: 'a command substitution' },
    { haystack: `"$root"/${NEEDLE}`, mentions: true, note: 'a quoted variable, quote closed before the slash' },
    { haystack: `"$1/${NEEDLE}`, mentions: true, note: 'a quoted positional parameter, quote still open' },
    { haystack: `"$(pwd)/${NEEDLE}`, mentions: true, note: 'a quoted command substitution, quote still open' },
    { haystack: `X=${NEEDLE}`, mentions: true, note: 'preceded by =' },
    { haystack: `echo ${NEEDLE}`, mentions: true, note: 'preceded by whitespace' },
    { haystack: `flux${NEEDLE}`, mentions: false, note: 'merged into a longer alnum name' },
    { haystack: `relay_${NEEDLE}`, mentions: false, note: 'merged into a longer name via underscore' },
    { haystack: `$root/annex/${NEEDLE}`, mentions: false, note: 'an intervening path segment after a bare variable' },
    { haystack: `\${root}/annex/${NEEDLE}`, mentions: false, note: 'an intervening path segment after a braced variable' },
    { haystack: `$root$extra/${NEEDLE}`, mentions: false, note: 'two interpolations, not one' },
    { haystack: `${NEEDLE}-probe-suffix-fresh`, mentions: false, note: 'trailing continuation' },
    { haystack: '.swarm/wall-clock-floor', mentions: false, note: 'a different basename entirely' },
    {
      haystack: `  COUNT_FILE="$root/${NEEDLE}"`,
      mentions: true,
      note: 'the real scripts/gate.sh line, unmutated (quoted, still open at the needle)',
    },
    {
      haystack: `$10/${NEEDLE}`,
      mentions: false,
      note: 'unbraced two-digit positional — bash reads this as $1 then a literal 0, not one token (round 3 review)',
    },
    { haystack: `\${10}/${NEEDLE}`, mentions: true, note: 'braced two-digit positional — the correct spelling of the above' },
    {
      haystack: `$(dirname "$0")/${NEEDLE}`,
      mentions: true,
      note: 'a command substitution containing whitespace and a quoted argument (round 3 review)',
    },
    {
      haystack: `$(cd sub && pwd)/${NEEDLE}`,
      mentions: true,
      note: 'a command substitution containing whitespace and &&  (round 3 review)',
    },
    { haystack: `$root/./${NEEDLE}`, mentions: true, note: 'a self-referential `.` path segment is a no-op, not an extra one (round 3 review)' },
    { haystack: `\${root}/./${NEEDLE}`, mentions: true, note: 'the same no-op segment, braced variable' },
  ]

  it.each(cases)('$note -> mentions=$mentions', ({ haystack, mentions }) => {
    expect(mentionsWholePath(haystack, NEEDLE)).toBe(mentions)
  })
})

/**
 * Ruling 11's self-citation check, in the tree — round 2 review found the branch dead on
 * the live registry (this file's own fix removed the only self-entry assertion span), so
 * nothing here exercised more than the canonical spelling of `.swarm/coupling.txt` before
 * now.
 */
describe('ruling 11 recognizes self-citation under multiple spellings of the same file', () => {
  // trackedFileSets()/packageSourceRoots() are NOT hoisted to this describe callback's
  // scope — see the sibling presence-check describe block's comment for why a `describe`
  // body is the wrong place for anything that can throw (round 3 review, EXECUTED: this
  // exact hoisting took all 93 tests in this file out of service, unnamed, on an
  // unavailable `git ls-files`). Called per-`it.each` case instead; both are memoised.
  const cases: readonly { readonly path: string; readonly selfCiting: boolean }[] = [
    { path: '.swarm/coupling.txt', selfCiting: true },
    { path: './.swarm/coupling.txt', selfCiting: true },
    { path: 'docs/../.swarm/coupling.txt', selfCiting: true },
    { path: '.swarm/./coupling.txt', selfCiting: true },
    { path: 'README.md', selfCiting: false },
  ]

  it.each(cases)('$path -> selfCiting=$selfCiting', ({ path: entryPath, selfCiting }) => {
    const [entry] = parseRegistry(
      `${entryPath}  # a real, honest reason \`expect(formTableProbe).toBe(true)\`\n`,
    )
    const analysis = analyzeEntry(entry!, trackedFileSets(), packageSourceRoots())
    const flagged = analysis.violations.some((v) => v.includes('prd-54 ruling 11'))
    expect(flagged).toBe(selfCiting)
  })
})

/**
 * The reason-restatement check (prd-54 ruling 10, presence), against the exact synthetic
 * shapes `scripts/dev/coupling.test.sh`'s own doc comment names — including the ones it
 * declares it deliberately does not catch. Unreachable on the live registry today (no
 * entry is quoted or carries odd whitespace), which is exactly why the shell script's own
 * comment says to write it down here rather than leave it for the entry that first needs
 * it.
 */
describe('reason-restatement check ports scripts/dev/coupling.test.sh exactly (prd-54 ruling 10)', () => {
  const cases: readonly { readonly line: string; readonly unexplained: boolean; readonly note: string }[] = [
    { line: 'p', unexplained: true, note: 'no # at all: the reason IS the whole line' },
    { line: "p  # 'p'", unexplained: true, note: 'single-quoted restatement' },
    { line: 'p  # "p"', unexplained: true, note: 'double-quoted restatement' },
    { line: 'p  # `p`', unexplained: true, note: 'backticked restatement' },
    { line: 'p  # a real reason', unexplained: false, note: 'an ordinary reason is not flagged' },
    {
      line: "p  # ''p''",
      unexplained: false,
      note: 'two layers of the SAME delimiter are deliberately NOT caught',
    },
    {
      line: 'p  # \'p"',
      unexplained: false,
      note: 'a MISMATCHED delimiter pair is deliberately NOT caught',
    },
    {
      line: 'docs/adr/  # run `git ls-tree origin/main docs/adr/` first, then check every open PR head',
      unexplained: false,
      note: 'a true self-reference inside a longer reason (the real docs/adr/ case) is not flagged',
    },
  ]

  it.each(cases)('$line -> unexplained=$unexplained ($note)', ({ line, unexplained }) => {
    const [entry] = parseRegistry(line)
    expect(entry, 'the synthetic line did not parse to an entry').toBeDefined()
    expect(isUnexplained(entry!)).toBe(unexplained)
  })
})
