import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * prd56 ruling 1's law — a PRD whose milestone is closed belongs under
 * `docs/prds/done/`, and this fails naming every file that is not.
 *
 * A location is reasoned FROM in this repo, not just stored: `docs/follow-up-292.md`
 * argued that a PRD sitting in `docs/prds/` rather than `docs/prds/done/` makes its
 * ruling live rather than archival, and `#416`'s enumeration classified a finished PRD
 * as a current document, and nearly edited its prose, for exactly that reason. Five
 * PRDs (`prd-25`, `prd-27`, `prd-43`, `prd-50`, `prd-52`) had closed milestones and
 * unarchived files when this law was written; prd56 wave 1 moved them in the same
 * commit as this file, so the law lands green rather than convicting its own evidence.
 * This is a SIBLING of `doc-citation-law.test.ts`, not a replacement for it: that law
 * proves a cited path exists, this one proves a PRD's shelf agrees with its milestone.
 *
 * Lives under `packages/server/` for the reason every sibling law here already gives:
 * the root vitest config globs `packages/*`, so a root-level test would never run and
 * would be its own vacuous law.
 *
 * ## Why a committed manifest, and not a live `gh` call (ruling 1)
 *
 * The suite must run offline: CI runs it on ten legs, this repo's own sibling laws
 * already derive tracker facts from `git log` rather than `gh` for the identical
 * reason, and a review seat could not run this suite at all this week because its
 * sandbox denied `gh`'s subprocess and socket access. A law that needs a token is a
 * law that gets skipped. `.swarm/prd-milestones.txt`, regenerated by
 * `scripts/dev/prd-milestones.sh` and committed like `.swarm/coupling.txt` beside it,
 * is what this file reads instead.
 *
 * ## The manifest's own staleness (prd56's open question, closed here)
 *
 * A committed manifest can itself drift out of step with GitHub the moment a
 * milestone opens or closes and nobody reruns the generator. Two candidates were
 * weighed:
 *
 *   1. Regenerate in CI and fail the build when regeneration would change the file.
 *   2. Bound the manifest's own age and fail once it is older than that bound.
 *
 * **This law takes (2) — a staleness bound of {@link MAX_MANIFEST_AGE_DAYS} days —
 * and (1) loses for two reasons.** First, (1) needs a `gh` token in a CI job, which
 * is the exact dependency ruling 1 removes from the SUITE — moving it into a
 * different CI step still leaves the repository unable to certify this law from a
 * bare clone with no network, where (2) can. Second, and more basic: PRD milestones
 * close through an operator act on GitHub, which no push to this repository causes —
 * regenerate-in-CI only ever runs on a push, so it would certify freshness at the
 * last commit's time, not at the time anyone actually reads the verdict, and a stale
 * manifest sitting untouched between pushes would report itself perfectly fresh
 * forever. A bound is honest about what it cannot promise (the manifest might have
 * gone stale seconds ago and still pass) rather than silently wrong about it.
 *
 * 14 days, not 30: `docs/prds/reconciliation-2026-08-22.md` records nine PRDs moved
 * to `done/` in one batch, and prd56's own Evidence section found five had drifted
 * back within three weeks (21 days) of that batch. A bound wider than the observed
 * recurrence interval would still read green while the exact drift this law exists
 * to catch was reaccumulating.
 *
 * ## Ruling 2 is not implemented here, on purpose
 *
 * "A PRD may stay unarchived when its own text declares why" is ruling 2, and its
 * form does not exist yet — wave 2 (#428) designs and builds it. Until it does, every
 * PRD reads as having no declared exemption, which is the correct answer today (none
 * of the five this wave moved had one) and is NOT an error condition — ruling 1 is
 * explicit that the law must read the form's absence as "no exemption claimed" and
 * carry on. {@link declaredExemptionReason} is a deliberate stub for exactly that:
 * wave 2 replaces its body, not the shape callers here depend on.
 *
 * ## The mirror case now HAS an instance — prd-56's open question is stale
 *
 * prd-56's Open Questions ask whether the law should also fail an ARCHIVED PRD whose
 * milestone is still OPEN, and leave it **open, not ruled**, on the stated ground that
 * "no instance exists today". That ground is no longer true, and this wave is what made
 * it untrue: `prd43`'s milestone REOPENED (1 open issue, no `closed_at`) after this wave
 * moved `prd-43-the-claim-is-a-test.md` into `done/` on the strength of its then-closed
 * milestone, and after the manifest recorded `43 closed 2026-09-07T22:46:05Z`.
 *
 * Nothing here goes red, and that is by design rather than by oversight: {@link liveShelfEntries}
 * reads only `docs/prds/`, never `docs/prds/done/`, so an archived PRD is outside this
 * law's sweep whatever its milestone says. The row is left as the generator wrote it.
 *
 * It is recorded here rather than fixed here because fixing it is not this wave's call
 * and does not stay local: moving the file back to the live shelf requires the manifest
 * to say `43 open`, which requires regenerating it, which also flips `prd48` and `prd53`
 * to closed — and both of those files are on the live shelf, so the law then fails naming
 * them. Measured: exit 1, `expected [ 'prd-48-the-shared-record.md', 'prd-53-the-lab.md' ]
 * to deeply equal []`. The mirror case and those two archival candidates are one decision,
 * they belong to whoever rules prd-56's open question, and ruling 2's exemption form
 * (wave 2) is what either of them would need.
 *
 * ## The glob hazard (verified against the real tree before this law was written)
 *
 * Three non-PRD markdown files live in `docs/prds/`: `README.md`,
 * `reconciliation-2026-08-22.md` and `retained-prds-review-2026-08-22.md`. A sweep
 * that globs `docs/prds/*.md` and pulls a milestone number out of ANY digits in the
 * filename misfires on the latter two — `2026-08-22` is a date, not a PRD number.
 * {@link PRD_FILE_RE} is anchored (`^prd-(\d+)-`), not a digits-anywhere match, for
 * exactly that reason; the glob-hazard test below proves it against all three by
 * name. `docs/prds/done/` holds none of the three, so the hazard is one-sided —
 * verified, not assumed, the same way `doc-citation-law.test.ts`'s own glob-gotcha
 * note insists on.
 */

const REPO_ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
const PRDS_DIR = path.join(REPO_ROOT, 'docs', 'prds')
const MANIFEST_PATH = path.join(REPO_ROOT, '.swarm', 'prd-milestones.txt')

/** `prd-25-the-third-platform.md` -> `25`. Anchored to the START of the filename — see the glob-hazard note above. */
const PRD_FILE_RE = /^prd-(\d+)-.+\.md$/

interface ShelfEntry {
  number: string
  file: string
  text: string
}

/** Pure: which filenames are PRDs, and their numbers — tested on synthetic input below, independent of the real `docs/prds/` listing. */
function matchPrdFilenames(filenames: readonly string[]): { number: string; file: string }[] {
  return filenames
    .map((file) => ({ file, m: PRD_FILE_RE.exec(file) }))
    .filter((r): r is { file: string; m: RegExpExecArray } => r.m !== null)
    .map((r) => ({ number: r.m[1]!, file: r.file }))
}

function liveShelfEntries(): ShelfEntry[] {
  return matchPrdFilenames(readdirSync(PRDS_DIR)).map(({ number, file }) => ({
    number,
    file,
    text: readFileSync(path.join(PRDS_DIR, file), 'utf8'),
  }))
}

type MilestoneState = 'open' | 'closed'
interface ManifestEntry {
  state: MilestoneState
  closedAt: string | undefined
}
interface Manifest {
  generatedAt: string | undefined
  entries: Map<string, ManifestEntry>
}

const GENERATED_AT_RE = /^#\s*generated-at:\s*(\S+)\s*$/m
/**
 * `\r?$` is the blocker fix, not decoration: `.swarm/prd-milestones.txt` is read with
 * `split('\n')`, so on a CRLF checkout every line arrives ending `\r`. `\S` cannot match
 * `\r`, so `$` was unreachable and EVERY row silently failed to match — `parseManifest`
 * returned an empty map and {@link violationsIn} reported NO violations while a
 * closed-milestone PRD sat on the live shelf. Verified on a CRLF copy: 0 rows parsed,
 * the law green on a real violation. `.gitattributes` now pins `.swarm/*.txt` to `eol=lf`
 * so the bytes are right in the first place; this tolerates the `\r` anyway, because a
 * law that goes VACUOUS rather than red is the one failure mode worth belt-and-braces.
 * Only `\r` is tolerated, deliberately — arbitrary trailing whitespace would also accept
 * a row a corrupt generator wrote, which {@link unmappedLiveShelf} must be able to see.
 */
const MANIFEST_ROW_RE = /^(\d+)\t(open|closed)\t(\S+)\r?$/

/** Pure: parses the manifest format `scripts/dev/prd-milestones.sh` writes. A line that is not a comment and does not match the row shape is silently skipped, matching `.swarm/coupling.txt`'s own "blank/comment lines are skipped" convention. */
function parseManifest(text: string): Manifest {
  const generatedAt = GENERATED_AT_RE.exec(text)?.[1]
  const entries = new Map<string, ManifestEntry>()
  for (const line of text.split('\n')) {
    const m = MANIFEST_ROW_RE.exec(line)
    if (!m) continue
    entries.set(m[1]!, { state: m[2] as MilestoneState, closedAt: m[3] === '-' ? undefined : m[3] })
  }
  return { generatedAt, entries }
}

function liveManifest(): Manifest {
  return parseManifest(readFileSync(MANIFEST_PATH, 'utf8'))
}

/**
 * Ruling 2's declared-exemption reader — a STUB. See the doc comment above: the
 * form does not exist yet, so every PRD reads as having none, which is correct
 * today and is exactly what "read the absence as no exemption claimed, not an
 * error" requires. Returns the reason string once wave 2 gives it a shape; `undefined`
 * means "no exemption claimed."
 */
function declaredExemptionReason(_text: string): string | undefined {
  return undefined
}

/** Pure: every shelf entry whose milestone is closed and carries no declared exemption. Mirrors `doc-citation-law.test.ts`'s pattern of a pure detector fed by both the real tree and a synthetic mutation. */
function violationsIn(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  const out: string[] = []
  for (const { number, file, text } of shelf) {
    const entry = manifest.entries.get(number)
    if (!entry || entry.state !== 'closed') continue
    if (declaredExemptionReason(text) !== undefined) continue
    out.push(file)
  }
  return out
}

/**
 * PRDs allowed to be on the live shelf with NO manifest row — i.e. genuinely no
 * milestone. Named, never inferred: `violationsIn` treats "no row" as "not a violation",
 * so without this floor a row that is MISSING for any other reason — a manifest that
 * failed to parse, a key spelling the generator never produced, a malformed line
 * silently skipped — is indistinguishable from a legitimate exemption and the law
 * fails OPEN. Adding a PRD here is a decision someone makes on purpose.
 */
const NO_MILESTONE_ALLOWLIST: readonly string[] = ['prd-34-the-doorstep.md']

/** Pure: live-shelf PRDs with no manifest row and no place on the allowlist — the floor under {@link violationsIn}. */
function unmappedLiveShelf(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  return shelf
    .filter((e) => !manifest.entries.has(e.number) && !NO_MILESTONE_ALLOWLIST.includes(e.file))
    .map((e) => e.file)
}

/** See the doc comment's staleness section for why this is a bound rather than a CI regeneration diff. */
const MAX_MANIFEST_AGE_DAYS = 14
const DAY_MS = 24 * 60 * 60 * 1000

/** Pure: `undefined`/unparseable dates are stale by definition — a manifest that does not say when it was generated cannot be trusted to be fresh. */
function isManifestStale(generatedAt: string | undefined, now: Date): boolean {
  if (generatedAt === undefined) return true
  const then = new Date(generatedAt).getTime()
  if (Number.isNaN(then)) return true
  const ageDays = (now.getTime() - then) / DAY_MS
  // A FUTURE generated-at is stale, not fresh. A negative age is never greater than
  // the bound, so the naive comparison called a clock-skewed or hand-edited manifest
  // permanently fresh — the one input that disables this check entirely.
  if (ageDays < 0) return true // see isFutureStamped: the caller reports this differently
  return ageDays > MAX_MANIFEST_AGE_DAYS
}

describe('a PRD whose milestone is closed lives under docs/prds/done/ (prd56 ruling 1)', () => {
  it('has PRDs to check at all — an empty directory would prove nothing', () => {
    expect(liveShelfEntries().length).toBeGreaterThan(5)
  })

  it('the manifest parses and has entries for both open and closed milestones', () => {
    const manifest = liveManifest()
    const states = new Set([...manifest.entries.values()].map((e) => e.state))
    expect(states.has('open')).toBe(true)
    expect(states.has('closed')).toBe(true)
  })

  it('no PRD on the live shelf has a closed milestone with no declared exemption', () => {
    expect(violationsIn(liveShelfEntries(), liveManifest())).toEqual([])
  })

  it('a PRD with no milestone is not a violation — prd-34-the-doorstep is that one PRD today', () => {
    const shelf = liveShelfEntries()
    const doorstep = shelf.find((e) => e.file === 'prd-34-the-doorstep.md')
    expect(doorstep).toBeDefined()
    // Re-derive rather than trust: this fails, naming the file, the day prd-34
    // gets a milestone — at which point this assertion (and this comment) are
    // the ones that need updating, per the issue's own instruction to verify
    // rather than assume.
    expect(liveManifest().entries.get(doorstep!.number)).toBeUndefined()
    expect(violationsIn([doorstep!], liveManifest())).toEqual([])
  })

  it('every live-shelf PRD has a manifest row, except the named no-milestone allowlist', () => {
    expect(
      unmappedLiveShelf(liveShelfEntries(), liveManifest()),
      'These PRDs are on the live shelf with no row in .swarm/prd-milestones.txt. If you just ' +
        'added one, regenerate and commit the manifest: scripts/dev/prd-milestones.sh. If the PRD ' +
        'genuinely has no milestone, add it to NO_MILESTONE_ALLOWLIST in this file and say why. ' +
        'An empty list here would also mean the manifest failed to parse at all.',
    ).toEqual([])
  })

  it('the floor names a PRD whose row is missing, however it went missing', () => {
    const shelf = liveShelfEntries()
    const manifest = liveManifest()
    // A row deleted, a key the generator never spelled, a line silently skipped as
    // malformed: all three arrive here as "no entry", and all three must be LOUD.
    const stripped: Manifest = { generatedAt: manifest.generatedAt, entries: new Map(manifest.entries) }
    const victim = shelf.find((e) => !NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(victim).toBeDefined()
    stripped.entries.delete(victim!.number)
    // toContain, not toEqual: this test consumes the REAL shelf, so an unrelated PRD
    // added without a manifest row would otherwise make it fail naming the wrong file
    // — a test failing for a reason it does not claim.
    expect(unmappedLiveShelf(shelf, stripped)).toContain(victim!.file)
    // Scoped to the ALLOWLISTED entry, not the whole shelf. Asserting emptiness over
    // the real shelf here duplicated the dedicated floor test one screen up, and made
    // this test fail — with no message — whenever any unrelated PRD lacked a row. The
    // claim is "the allowlisted one stays silent", so that is what is asserted.
    const allowlisted = shelf.filter((e) => NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(allowlisted.length, 'the allowlist must actually match something on the live shelf').toBeGreaterThan(0)
    expect(unmappedLiveShelf(allowlisted, manifest)).toEqual([])
  })

  it('a CRLF manifest does not silently disarm the law — it reddens the floor instead', () => {
    // The blocker this file shipped with: `.swarm/*.txt` was eol-unspecified, so a
    // Windows checkout delivered `\r`-terminated rows, NO row matched, and the law
    // reported zero violations against a real one. `.gitattributes` now pins the file;
    // this proves that even if it did not, the failure is loud rather than vacuous.
    const crlf = readFileSync(MANIFEST_PATH, 'utf8').replace(/\n/g, '\r\n')
    const parsed = parseManifest(crlf)
    expect(parsed.entries.size, 'the \\r?$ tolerance must keep CRLF rows parseable').toBeGreaterThan(0)
    const emptied: Manifest = { generatedAt: parsed.generatedAt, entries: new Map() }
    expect(unmappedLiveShelf(liveShelfEntries(), emptied).length).toBeGreaterThan(0)
  })

  it('the glob hazard: docs/prds/ non-PRD markdown files are not read as PRDs', () => {
    const matched = matchPrdFilenames([
      'README.md',
      'reconciliation-2026-08-22.md',
      'retained-prds-review-2026-08-22.md',
      // These three pin the ANCHORING the doc comment credits this test with. Without
      // them the fixture killed only a digits-anywhere mutant: dropping the leading `^`
      // and loosening the tail to `.*\.md$` both survived 8/8.
      'notes-prd-99-x.md',
      'prd-99-x.md.bak',
      'prd-99.md',
      'prd-14-experiment-console.md',
    ])
    expect(matched).toEqual([{ number: '14', file: 'prd-14-experiment-console.md' }])
  })

  it('the manifest is not stale (bound: 14 days — see the doc comment for why a bound, not CI regeneration)', () => {
    const generatedAt = liveManifest().generatedAt
    const now = new Date()
    const future = generatedAt !== undefined && !Number.isNaN(new Date(generatedAt).getTime()) && new Date(generatedAt).getTime() > now.getTime()
    // A future stamp is stale too, but telling the reader it is "older than 14 days"
    // is false, and the prescribed remedy re-reads the same wrong clock. WSL2 clock
    // drift across suspend/resume is this repo's own environment, so this is reachable.
    expect(
      future,
      `.swarm/prd-milestones.txt is stamped ${generatedAt}, which is in the FUTURE relative to ` +
        `this machine's clock. Check the clock before regenerating — scripts/dev/prd-milestones.sh ` +
        `reads the same one, so regenerating now would reproduce this.`,
    ).toBe(false)
    expect(
      isManifestStale(generatedAt, now),
      `.swarm/prd-milestones.txt was generated at ${generatedAt} and is now older than ` +
        `${MAX_MANIFEST_AGE_DAYS} days. This is the staleness bound working as ruled, not a ` +
        `defect in whatever you are changing. Regenerate and commit it: scripts/dev/prd-milestones.sh`,
    ).toBe(false)
  })

  it('mutation: the detector bites when a closed-milestone PRD sits on the live shelf', () => {
    // Real manifest, real entry: prd-52's milestone is closed. Rather than
    // actually moving the real file back out of done/ (that mutation was run
    // by hand — see this commit's own body for the executed proof — a repo-
    // wide integration test earns nothing this pure-function test cannot
    // already prove), simulate the exact shape the law must catch: a
    // closed-milestone PRD's text presented as if it were still on the live
    // shelf.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const putBack: ShelfEntry = { number: closedNumber!, file: `prd-${closedNumber}-put-back.md`, text: 'no exemption declared' }
    expect(violationsIn([putBack], manifest)).toEqual([putBack.file])

    // The control: the same entry, but its milestone is open — must NOT fire.
    const openNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'open')?.[0]
    expect(openNumber).toBeDefined()
    const stillLive: ShelfEntry = { number: openNumber!, file: `prd-${openNumber}-still-live.md`, text: 'no exemption declared' }
    expect(violationsIn([stillLive], manifest)).toEqual([])
  })

  it('mutation: the bound is exactly 14 days — LITERAL dates, so this reddens at 13 and at 15', () => {
    // These dates are written out, NOT derived from MAX_MANIFEST_AGE_DAYS or DAY_MS.
    // The earlier version computed them as (B-1) and (B+1) days, which asserts
    // `(B-1) > B` is false and `(B+1) > B` is true — true for EVERY B. Measured: the
    // whole file stayed 8/8 green with the bound set to 1, 3, 13, 15 and 365, and with
    // DAY_MS set to three days. It pinned the comparison operator, never the number.
    const now = new Date('2026-09-11T00:00:00Z')
    expect(isManifestStale('2026-08-28T00:00:01Z', now)).toBe(false) // 13d 23h 59m — inside
    expect(isManifestStale('2026-08-28T00:00:00Z', now)).toBe(false) // exactly 14d — the boundary is NOT stale
    expect(isManifestStale('2026-08-27T23:59:59Z', now)).toBe(true) // 14d + 1s — outside
    expect(isManifestStale(undefined, now)).toBe(true)
    expect(isManifestStale('not-a-date', now)).toBe(true)
    // A future timestamp is stale, not fresh — a negative age is never > the bound.
    expect(isManifestStale('2026-09-12T00:00:00Z', now)).toBe(true)
  })
})
