import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * prd56 ruling 1's law — a PRD whose milestone is closed belongs under
 * `docs/prds/done/`, and this fails naming every file that is not.
 *
 * A location is reasoned FROM in this repo, not just stored: `docs/follow-up-292.md`
 * argued that a PRD sitting in `docs/prds/` rather than `docs/prds/done/` makes its
 * ruling live rather than archival, and `#416`'s enumeration classified a finished PRD
 * as a current document, and nearly edited its prose, for exactly that reason. Five
 * PRDs (`prd-25`, `prd-27`, `prd-43`, `prd-50`, `prd-52`) had closed milestones and
 * unarchived files when this law was written; prd56 wave 1 moved them in the same
 * commit as this file, so the law lands green rather than convicting its own evidence.
 * This is a SIBLING of `doc-citation-law.test.ts`, not a replacement for it: that law
 * proves a cited path exists, this one proves a PRD's shelf agrees with its milestone.
 *
 * Lives under `packages/server/` for the reason every sibling law here already gives:
 * the root vitest config globs `packages/*`, so a root-level test would never run and
 * would be its own vacuous law.
 *
 * ## Why a committed manifest, and not a live `gh` call (ruling 1)
 *
 * The suite must run offline: CI runs it on ten legs, this repo's own sibling laws
 * already derive tracker facts from `git log` rather than `gh` for the identical
 * reason, and a review seat could not run this suite at all this week because its
 * sandbox denied `gh`'s subprocess and socket access. A law that needs a token is a
 * law that gets skipped. `.swarm/prd-milestones.txt`, regenerated by
 * `scripts/dev/prd-milestones.sh` and committed like `.swarm/coupling.txt` beside it,
 * is what this file reads instead.
 *
 * ## The manifest's own staleness (prd56's open question, closed here)
 *
 * A committed manifest can itself drift out of step with GitHub the moment a
 * milestone opens or closes and nobody reruns the generator. Two candidates were
 * weighed:
 *
 *   1. Regenerate in CI and fail the build when regeneration would change the file.
 *   2. Bound the manifest's own age and fail once it is older than that bound.
 *
 * **This law takes (2) — a staleness bound of {@link MAX_MANIFEST_AGE_DAYS} days —
 * and (1) loses for two reasons.** First, (1) needs a `gh` token in a CI job, which
 * is the exact dependency ruling 1 removes from the SUITE — moving it into a
 * different CI step still leaves the repository unable to certify this law from a
 * bare clone with no network, where (2) can. Second, and more basic: PRD milestones
 * close through an operator act on GitHub, which no push to this repository causes —
 * regenerate-in-CI only ever runs on a push, so it would certify freshness at the
 * last commit's time, not at the time anyone actually reads the verdict, and a stale
 * manifest sitting untouched between pushes would report itself perfectly fresh
 * forever. A bound is honest about what it cannot promise (the manifest might have
 * gone stale seconds ago and still pass) rather than silently wrong about it.
 *
 * 14 days, not 30: `docs/prds/reconciliation-2026-08-22.md` records nine PRDs moved
 * to `done/` in one batch, and prd56's own Evidence section found five had drifted
 * back within three weeks (21 days) of that batch. A bound wider than the observed
 * recurrence interval would still read green while the exact drift this law exists
 * to catch was reaccumulating.
 *
 * ## Ruling 2 — the declared-exemption form (wave 2, #428)
 *
 * "A PRD may stay unarchived when its own text declares why" is ruling 2.
 * {@link declaredExemptionReason} reads it: a PRD's text carrying a genuine DECLARATION of
 * the marker `**Shelf exemption:**` (a line starting with it, outside any comment or code
 * block — see that function's own doc comment for the full grammar) followed by prose that
 * clears a substance threshold is exempt from this law; a PRD with no such declaration, or
 * one with nothing but a placeholder behind it, is not, and reads exactly as it did before
 * this wave — "no exemption claimed", not an error. The reason may continue across further
 * blockquote lines (each starting with `>`) after the marker's own line, the same
 * `> **Label:** wrapped prose` shape this file's own PRDs already use elsewhere (see this
 * PRD's own `**Outcome:**` blocks); a blank quoted line (`>` alone) ends the paragraph, so a
 * later, unrelated quoted paragraph is never swept into the reason.
 *
 * **Keyed on the declaration, never on the document.** The rejected alternative is a list
 * of allowed filenames (or a check for `prd-17` by name): it passes today and is a fitted
 * instrument, because the next PRD with a real reason to stay would not be on the list, the
 * law would convict it, and the fix would be adding a second name rather than writing a
 * reason. `declaredExemptionReason` never inspects a file's name, only its text — proven
 * below by a synthetic file carrying the marker under a name this repo has never used.
 *
 * The second rejected alternative is a flag that suppresses the whole law rather than one
 * file's violation. Proven below: a synthetic closed-milestone, no-reason entry is convicted
 * in the SAME `violationsIn` call that clears the real prd-17 entry, so the form cannot be
 * "never fire".
 *
 * **A third rejected alternative, added at verify (2026-09-14, `c8709751`).** The first
 * version matched the first OCCURRENCE of the marker via a bare `text.indexOf`, not the
 * first DECLARATION — concealable behind an HTML comment or a fenced code block, confusable
 * with a mid-sentence mention of the marker itself, and unpinned as to WHICH occurrence
 * governs when a file (every one of the four this wave exempts) contains it twice. Two
 * independent review seats plus the orchestrator found this, all EXECUTED: an HTML-comment
 * concealment and a `lastIndexOf` mutation both left the suite 21/21 green. The rejected fix
 * was a word blacklist ("TBD", "n/a", "-", …) for the sibling defect — placeholder reasons
 * ("`> **Shelf exemption:** -`" and five others) also passed — for the same reason the
 * filename list was rejected above: the next placeholder is never on the list. Both are
 * fixed structurally instead — see {@link declaredExemptionReason}'s own doc comment.
 *
 * **Four subjects carry a declared reason; one is archived instead**, and the two are not
 * interchangeable (prd-56, operator-ruled 2026-09-13, recorded on #428): `prd-17`
 * (`docs/follow-up-292.md` holds an open item against ruling 3), `prd-53` (`prd-55`'s waves
 * build live on its rulings), `prd-14` and `prd-20` (`prd-55` and `prd-34`, respectively,
 * each cite a still-live PRD's rulings from a document that is itself unfinished) each
 * declare one. `prd-48` had no such argument found for it and moved to `docs/prds/done/`
 * instead, taking ruling 1's ordinary path — reaching for the exemption to paper over an
 * archival candidate is exactly what would turn the form into a way to switch the law off.
 * Adding the two late subjects (`prd-14`, `prd-20`, discovered only once the manifest was
 * actually regenerated) required editing no code in this file — only their own PRD text —
 * which is itself evidence the form is keyed on the declaration and not on which PRD asks.
 *
 * ## The mirror case still has its instance — prd-56's open question is stale, and now ruled
 *
 * prd-56's Open Questions ask whether the law should also fail an ARCHIVED PRD whose
 * milestone is still OPEN, and left it **open, not ruled**, on the stated ground that "no
 * instance exists today". That ground stopped being true when wave 1 moved
 * `prd-43-the-claim-is-a-test.md` into `done/` on the strength of its then-closed milestone
 * and the milestone then REOPENED (1 open issue, no `closed_at`). #459 is the ruling: the law
 * stays one-way, deliberately, because a closed-milestone PRD on the live shelf misleads a
 * reader into treating a shipped ruling as open, while an archived PRD with a reopened
 * milestone only reads as stale — nobody is misled into treating it as settled.
 *
 * Nothing here goes red, and that is by design rather than by oversight: {@link liveShelfEntries}
 * reads only `docs/prds/`, never `docs/prds/done/`, so an archived PRD is outside this law's
 * sweep whatever its milestone says. The row is left as the generator wrote it. #459 owns
 * writing the ruling into prd-56's own document; this file only needed its citation updated
 * once #459 gives it a number to cite, which is #459's job, not this wave's.
 *
 * What IS resolved, by this wave regenerating the manifest: `prd14`, `prd17`, `prd20`, `prd48`
 * and `prd53` all flipping to closed no longer fails the law, because four now carry ruling
 * 2's form and the fifth (`prd48`) moved to `done/` in this same commit. Measured before this
 * wave's changes: regenerating exited 1 naming all five `docs/prds/*.md` files by name.
 *
 * ## The glob hazard (verified against the real tree before this law was written)
 *
 * Three non-PRD markdown files live in `docs/prds/`: `README.md`,
 * `reconciliation-2026-08-22.md` and `retained-prds-review-2026-08-22.md`. A sweep
 * that globs `docs/prds/*.md` and pulls a milestone number out of ANY digits in the
 * filename misfires on the latter two — `2026-08-22` is a date, not a PRD number.
 * {@link PRD_FILE_RE} is anchored (`^prd-(\d+)-`), not a digits-anywhere match, for
 * exactly that reason; the glob-hazard test below proves it against all three by
 * name. `docs/prds/done/` holds none of the three, so the hazard is one-sided —
 * verified, not assumed, the same way `doc-citation-law.test.ts`'s own glob-gotcha
 * note insists on.
 */

const REPO_ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
const PRDS_DIR = path.join(REPO_ROOT, 'docs', 'prds')
const MANIFEST_PATH = path.join(REPO_ROOT, '.swarm', 'prd-milestones.txt')

/** `prd-25-the-third-platform.md` -> `25`. Anchored to the START of the filename — see the glob-hazard note above. */
const PRD_FILE_RE = /^prd-(\d+)-.+\.md$/

interface ShelfEntry {
  number: string
  file: string
  text: string
}

/** Pure: which filenames are PRDs, and their numbers — tested on synthetic input below, independent of the real `docs/prds/` listing. */
function matchPrdFilenames(filenames: readonly string[]): { number: string; file: string }[] {
  return filenames
    .map((file) => ({ file, m: PRD_FILE_RE.exec(file) }))
    .filter((r): r is { file: string; m: RegExpExecArray } => r.m !== null)
    .map((r) => ({ number: r.m[1]!, file: r.file }))
}

function liveShelfEntries(): ShelfEntry[] {
  return matchPrdFilenames(readdirSync(PRDS_DIR)).map(({ number, file }) => ({
    number,
    file,
    text: readFileSync(path.join(PRDS_DIR, file), 'utf8'),
  }))
}

type MilestoneState = 'open' | 'closed'
interface ManifestEntry {
  state: MilestoneState
  closedAt: string | undefined
}
interface Manifest {
  generatedAt: string | undefined
  entries: Map<string, ManifestEntry>
}

const GENERATED_AT_RE = /^#\s*generated-at:\s*(\S+)\s*$/m
/**
 * `\r?$` is the blocker fix, not decoration: `.swarm/prd-milestones.txt` is read with
 * `split('\n')`, so on a CRLF checkout every line arrives ending `\r`. `\S` cannot match
 * `\r`, so `$` was unreachable and EVERY row silently failed to match — `parseManifest`
 * returned an empty map and {@link violationsIn} reported NO violations while a
 * closed-milestone PRD sat on the live shelf. Verified on a CRLF copy: 0 rows parsed,
 * the law green on a real violation. `.gitattributes` now pins `.swarm/*.txt` to `eol=lf`
 * so the bytes are right in the first place; this tolerates the `\r` anyway, because a
 * law that goes VACUOUS rather than red is the one failure mode worth belt-and-braces.
 * Only `\r` is tolerated, deliberately — arbitrary trailing whitespace would also accept
 * a row a corrupt generator wrote, which {@link unmappedLiveShelf} must be able to see.
 */
const MANIFEST_ROW_RE = /^(\d+)\t(open|closed)\t(\S+)\r?$/

/** Pure: parses the manifest format `scripts/dev/prd-milestones.sh` writes. A line that is not a comment and does not match the row shape is silently skipped, matching `.swarm/coupling.txt`'s own "blank/comment lines are skipped" convention. */
function parseManifest(text: string): Manifest {
  const generatedAt = GENERATED_AT_RE.exec(text)?.[1]
  const entries = new Map<string, ManifestEntry>()
  for (const line of text.split('\n')) {
    const m = MANIFEST_ROW_RE.exec(line)
    if (!m) continue
    entries.set(m[1]!, { state: m[2] as MilestoneState, closedAt: m[3] === '-' ? undefined : m[3] })
  }
  return { generatedAt, entries }
}

function liveManifest(): Manifest {
  return parseManifest(readFileSync(MANIFEST_PATH, 'utf8'))
}

/** The exact marker {@link declaredExemptionReason} looks for — see the Ruling 2 doc comment above for the form's rationale and its two rejected alternatives. */
const EXEMPTION_MARKER = '**Shelf exemption:**'

/**
 * A declared reason must contain at least this many "words" — runs of 2+ letters — to
 * count as substance rather than a placeholder. A THRESHOLD, not a blacklist of rejected
 * strings ("TBD", "n/a", "-", "x", "**", a bare zero-width space all score 0 or 1): a
 * blacklist is the same fitted instrument this issue already rejects for the exemption
 * itself — the next placeholder is never on the list, and the fix becomes adding a fourth
 * string rather than asking whether ANY placeholder should pass. A single letter, a bare
 * punctuation mark, and an invisible character all score zero because `[A-Za-z]{2,}`
 * requires two-plus letters in a row; a real reason is a sentence, which structurally
 * requires several such runs. See the "declaredExemptionReason" describe block below for
 * every scored form, each checked directly.
 */
const MIN_REASON_WORDS = 3

/**
 * Strips zero or more levels of a CommonMark blockquote prefix (up to 3 leading spaces,
 * `>`, then any run of spaces/tabs) from the START of one line. Deliberately consumes ALL
 * whitespace after the `>`, not just CommonMark's own one optional space: this file has no
 * indented code living inside a blockquote, so the simpler rule is the one that does not
 * misread `>   **Shelf exemption:**` (extra padding) as an indented-code line.
 */
function stripBlockquotePrefix(line: string): string {
  let rest = line
  for (;;) {
    const m = /^ {0,3}>[ \t]*/.exec(rest)
    if (!m) return rest
    rest = rest.slice(m[0].length)
  }
}

/** A fence delimiter line (3+ of the same backtick or tilde), read after stripping any blockquote prefix. */
const FENCE_OPEN_RE = /^(`{3,}|~{3,})/

/**
 * Ruling 2's declared-exemption reader. Keyed on the DECLARATION, never on the document:
 * any text carrying a genuine declaration is exempt, regardless of which file it lives
 * in — this function never sees a filename, only `text`.
 *
 * **Verify review found the first version matched the first OCCURRENCE of
 * {@link EXEMPTION_MARKER}, not the first DECLARATION** (2026-09-14, `c8709751`,
 * two independent seats plus the orchestrator, all EXECUTED): a bare `text.indexOf` sees
 * a marker sitting inside an HTML comment, a fenced or indented code block, or a
 * mid-sentence MENTION (this very file's own "keyed on the `**Shelf exemption:**` marker"
 * sentences, added deliberately to each PRD as a human-readable cross-reference) exactly
 * as readily as a real declaration — concealing a real one behind an HTML comment left the
 * suite green, and mutating `indexOf` to `lastIndexOf` did too, because every one of the
 * four PRDs this wave exempts contains the marker TWICE and no test pinned WHICH occurrence
 * governs.
 *
 * The fix: a declaration is a LINE whose content — after {@link stripBlockquotePrefix} —
 * starts with the marker, is not inside a fenced or indented code block, and is not inside
 * an HTML comment (blanked out globally before the line scan, since a comment can wrap
 * several `>`-quoted lines). The scan returns the FIRST such line; a mid-sentence mention
 * never qualifies, because the marker there is not at the start of its line's content.
 *
 * The reason may continue across further blockquote lines the same way it always did,
 * ending at the first blank quoted line or non-quoted line. It must then clear
 * {@link MIN_REASON_WORDS} or the declaration is a hard stop — a placeholder reason
 * convicts the file rather than leaving the scan to hunt for a better one further down,
 * matching ruling 2's "an empty or placeholder reason is not an exemption" exactly.
 *
 * Returns the trimmed, whitespace-collapsed reason, or `undefined` for no declaration, a
 * below-threshold one, or one that never emerges from a comment/fence/indented block.
 */
function declaredExemptionReason(text: string): string | undefined {
  // HTML comments are blanked over the WHOLE text first, not line by line: a comment can
  // wrap several `>`-quoted lines, and replacing only non-newline characters keeps every
  // later line index identical to what it would be without the comment there.
  const withoutComments = text.replace(/<!--[\s\S]*?-->/g, (m) => m.replace(/[^\n]/g, ' '))
  const lines = withoutComments.split('\n')

  let inFence = false
  let fenceChar = ''
  let fenceLen = 0

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i]!
    const stripped = stripBlockquotePrefix(raw)

    if (inFence) {
      const close = /^(`+|~+)\s*$/.exec(stripped)
      if (close && close[1]![0] === fenceChar && close[1]!.length >= fenceLen) inFence = false
      continue // every line strictly between open and close, and the close line itself, is code
    }
    const open = FENCE_OPEN_RE.exec(stripped)
    if (open) {
      inFence = true
      fenceChar = open[1]![0]!
      fenceLen = open[1]!.length
      continue
    }
    if (/^( {4,}|\t)/.test(stripped)) continue // an indented code line, not prose

    if (!stripped.startsWith(EXEMPTION_MARKER)) continue

    // A declaration line. Collect its paragraph exactly as ruling 2 always did: the rest
    // of this line, then further `>`-prefixed lines, stopping at the first blank quoted
    // line or non-quoted line. `\r` on a CONTINUATION line must be stripped before the
    // regex runs — `.` excludes line terminators, so an untouched trailing `\r` blocks
    // `(.*)$` from ever reaching the end of the string and the line reads as "not a
    // continuation" (measured: a CRLF second line then drops out of the paragraph
    // entirely). The marker's OWN line needs no such strip: `\s+` normalisation below
    // already folds a trailing `\r` into the join, and removing it here changes nothing —
    // verified by running both versions over the same CRLF fixture.
    const paragraph: string[] = [stripped.slice(EXEMPTION_MARKER.length)]
    for (let j = i + 1; j < lines.length; j++) {
      const cont = /^\s*>\s?(.*)$/.exec(lines[j]!.replace(/\r$/, ''))
      if (!cont || cont[1]!.trim().length === 0) break
      paragraph.push(cont[1]!)
    }
    const reason = paragraph.join(' ').replace(/\s+/g, ' ').trim()
    const words = reason.match(/[A-Za-z]{2,}/g) ?? []
    return words.length >= MIN_REASON_WORDS ? reason : undefined
  }
  return undefined
}

/** Pure: every shelf entry whose milestone is closed and carries no declared exemption. Mirrors `doc-citation-law.test.ts`'s pattern of a pure detector fed by both the real tree and a synthetic mutation. */
function violationsIn(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  const out: string[] = []
  for (const { number, file, text } of shelf) {
    const entry = manifest.entries.get(number)
    if (!entry || entry.state !== 'closed') continue
    if (declaredExemptionReason(text) !== undefined) continue
    out.push(file)
  }
  return out
}

/**
 * PRDs allowed to be on the live shelf with NO manifest row — i.e. genuinely no
 * milestone. Named, never inferred: `violationsIn` treats "no row" as "not a violation",
 * so without this floor a row that is MISSING for any other reason — a manifest that
 * failed to parse, a key spelling the generator never produced, a malformed line
 * silently skipped — is indistinguishable from a legitimate exemption and the law
 * fails OPEN. Adding a PRD here is a decision someone makes on purpose.
 */
const NO_MILESTONE_ALLOWLIST: readonly string[] = ['prd-34-the-doorstep.md']

/** Pure: live-shelf PRDs with no manifest row and no place on the allowlist — the floor under {@link violationsIn}. */
function unmappedLiveShelf(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  return shelf
    .filter((e) => !manifest.entries.has(e.number) && !NO_MILESTONE_ALLOWLIST.includes(e.file))
    .map((e) => e.file)
}

/** See the doc comment's staleness section for why this is a bound rather than a CI regeneration diff. */
const MAX_MANIFEST_AGE_DAYS = 14
const DAY_MS = 24 * 60 * 60 * 1000

/** Pure: `undefined`/unparseable dates are stale by definition — a manifest that does not say when it was generated cannot be trusted to be fresh. */
function isManifestStale(generatedAt: string | undefined, now: Date): boolean {
  if (generatedAt === undefined) return true
  const then = new Date(generatedAt).getTime()
  if (Number.isNaN(then)) return true
  const ageDays = (now.getTime() - then) / DAY_MS
  // A FUTURE generated-at is stale, not fresh. A negative age is never greater than
  // the bound, so the naive comparison called a clock-skewed or hand-edited manifest
  // permanently fresh — the one input that disables this check entirely.
  if (ageDays < 0) return true // see isFutureStamped: the caller reports this differently
  return ageDays > MAX_MANIFEST_AGE_DAYS
}

describe('a PRD whose milestone is closed lives under docs/prds/done/ (prd56 ruling 1)', () => {
  it('has PRDs to check at all — an empty directory would prove nothing', () => {
    expect(liveShelfEntries().length).toBeGreaterThan(5)
  })

  it('the manifest parses and has entries for both open and closed milestones', () => {
    const manifest = liveManifest()
    const states = new Set([...manifest.entries.values()].map((e) => e.state))
    expect(states.has('open')).toBe(true)
    expect(states.has('closed')).toBe(true)
  })

  it('no PRD on the live shelf has a closed milestone with no declared exemption', () => {
    expect(violationsIn(liveShelfEntries(), liveManifest())).toEqual([])
  })

  it('ruling 2: prd-17, prd-53, prd-14 and prd-20 each carry a declared reason despite a closed milestone', () => {
    // `toBeDefined()` alone survived BOTH the HTML-comment-conceal mutant and the
    // `indexOf` -> `lastIndexOf` mutant (verify, 2026-09-14): every one of these four files
    // contains the marker TWICE — the declaration, then a self-reference in the trailing
    // "read by ... for the marker" sentence each one carries — so the wrong occurrence
    // still returns SOME defined string. Pinning the exact CONTENT is what reddens on the
    // wrong occurrence, not just on no occurrence.
    const EXPECTED_REASON: Record<string, string> = {
      'prd-17-complete-record.md':
        "it stays in `docs/prds/` rather than moving to `docs/prds/done/`, and that is a separate operator decision rather than a consequence of shipping — `docs/follow-up-292.md` reads this file's location as the difference between a LIVE ruling and an archival one, and holds an open, uncorrected item against ruling 3's law 1 — whose wording it calls the origin of a claim that is still false in `docs/architecture.md`. Archiving this PRD would demote that ruling while the item is open, and that document reserves the amendment decision for whoever owns the ruling. The move is a follow-up.",
      'prd-53-the-lab.md':
        "`prd-53`'s milestone closed 2026-09-11, but this stays on the live shelf rather than moving to `docs/prds/done/` — `prd-55`, *the lab, stage two*, is live with waves 6 and 7 building directly on this PRD's rulings, and archiving prd-53 mid-build would demote the rulings stage two is building on.",
      'prd-14-experiment-console.md':
        'stays on the live shelf rather than moving to `docs/prds/done/` — `docs/prds/prd-55-the-lab-stage-two.md` is live, with a wave in flight, and reasons from this PRD\'s rulings in the present tense: its Non-goals bind the R&D surface to naming no winner by citing "prd-14 ruling 3", and ruling 4 says a proposal\'s launch "applies unchanged (prd-14 ruling 4)". Archiving this PRD would demote rulings prd-55 is building on.',
      'prd-20-the-concierge.md':
        'stays on the live shelf rather than moving to `docs/prds/done/` — `docs/prds/prd-34-the-doorstep.md` is live (unmilestoned, still being built) and reasons from this PRD in the present tense: prd-34\'s own ruling 4 says *"prd-20 remains the authority on what the concierge may do (launch or relaunch a conductor, clone by URL; no OAuth, no accounts, no stored credentials)."* Archiving this PRD would demote a ruling prd-34 is deferring to.',
    }
    const shelf = liveShelfEntries()
    const manifest = liveManifest()
    for (const [file, expectedReason] of Object.entries(EXPECTED_REASON)) {
      const entry = shelf.find((e) => e.file === file)
      expect(entry, `${file} must still be on the live shelf`).toBeDefined()
      expect(manifest.entries.get(entry!.number)?.state, `${file}'s milestone must be closed for this test to mean anything`).toBe('closed')
      expect(entry!.text.split(EXEMPTION_MARKER).length - 1, `${file} must carry the marker at least twice for this test to be meaningful`).toBeGreaterThanOrEqual(2)
      expect(declaredExemptionReason(entry!.text), `${file}'s declared reason`).toBe(expectedReason)
    }
  })

  it('the exemption is keyed on the DECLARATION, not on which document made it — a synthetic file under an unrelated name is exempt just the same', () => {
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const declaredElsewhere: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9999-a-file-this-repo-has-never-used.md',
      text: '> **Shelf exemption:** a synthetic reason, not any real PRD\'s.\n',
    }
    expect(violationsIn([declaredElsewhere], manifest)).toEqual([])
  })

  it('the exemption is per-file, not a switch for the whole law — a synthetic no-reason PRD is convicted in the SAME run that clears the real prd-17', () => {
    const shelf = liveShelfEntries()
    const prd17 = shelf.find((e) => e.file === 'prd-17-complete-record.md')
    expect(prd17).toBeDefined()
    const manifest = liveManifest()
    const noReasonClosed: ShelfEntry = { number: prd17!.number, file: 'prd-9998-no-reason-declared.md', text: 'nothing declared here' }
    // Same manifest, same call: prd17 (real, with a reason) clears; the synthetic sibling
    // sharing its milestone number, with no reason, does not. Proves the form cannot be
    // implemented as "never fire" — the obvious miss this issue names.
    expect(violationsIn([prd17!, noReasonClosed], manifest)).toEqual([noReasonClosed.file])
  })

  it('a declaration concealed behind an HTML comment is convicted, not exempted', () => {
    // Verify, 2026-09-14: replacing a real declared-reason block with a single HTML
    // comment carrying the marker left the first version 21/21 green — a reader sees a
    // finished PRD with no stated reason, and the law agreed with the file.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const concealed: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9997-concealed-in-a-comment.md',
      text: '<!-- **Shelf exemption:** still needed, see #428 -->\n\nNo visible reason anywhere in this document.',
    }
    expect(violationsIn([concealed], manifest)).toEqual([concealed.file])
  })

  it('a marker sitting only in a fenced code block documenting the form is convicted, not exempted', () => {
    // Verify, 2026-09-14 (Opus seat): a PRD whose only marker sits inside a fence that
    // documents the mechanism, with the body itself saying nothing is declared, read as
    // exempt — the fence was never excluded from the scan.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const fenced: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9996-marker-only-in-a-fence.md',
      text: "Ruling 2's form looks like this:\n\n```md\n> **Shelf exemption:** <reason>\n```\n\nNothing is declared in this PRD.",
    }
    expect(violationsIn([fenced], manifest)).toEqual([fenced.file])
  })

  it('mutation: emptying or removing prd-17\'s declared reason convicts it — the marker alone is not an exemption', () => {
    const shelf = liveShelfEntries()
    const prd17 = shelf.find((e) => e.file === 'prd-17-complete-record.md')
    expect(prd17).toBeDefined()
    const manifest = liveManifest()
    expect(manifest.entries.get(prd17!.number)?.state).toBe('closed')
    expect(violationsIn([prd17!], manifest), 'sanity: prd-17 passes today').toEqual([])

    // The real reason continues across several further blockquote lines (this file's own
    // `> **Label:** wrapped prose` convention), so a mutation that only touches the
    // marker's own line leaves the rest of the paragraph intact and understates nothing —
    // measured failing exactly that way on the first version of this test. Strip through
    // the whole quoted run instead: the first line break not followed by another `>` line.
    const markerIdx = prd17!.text.indexOf(EXEMPTION_MARKER)
    expect(markerIdx).toBeGreaterThanOrEqual(0)
    const afterMarker = markerIdx + EXEMPTION_MARKER.length
    const quoteBreak = /\n(?!\s*>)/.exec(prd17!.text.slice(afterMarker))
    const blockEnd = quoteBreak ? afterMarker + quoteBreak.index : prd17!.text.length
    expect(blockEnd, 'the marker must be followed by at least one more blockquote line to strip').toBeGreaterThan(afterMarker)

    const emptied = prd17!.text.slice(0, afterMarker) + prd17!.text.slice(blockEnd)
    expect(emptied, 'the reason must actually have been stripped').not.toBe(prd17!.text)
    expect(declaredExemptionReason(emptied)).toBeUndefined()
    expect(violationsIn([{ ...prd17!, text: emptied }], manifest)).toEqual([prd17!.file])

    const removed = prd17!.text.slice(0, markerIdx) + prd17!.text.slice(blockEnd)
    expect(declaredExemptionReason(removed)).toBeUndefined()
    expect(violationsIn([{ ...prd17!, text: removed }], manifest)).toEqual([prd17!.file])
  })

  it('a PRD with no milestone is not a violation — prd-34-the-doorstep is that one PRD today', () => {
    const shelf = liveShelfEntries()
    const doorstep = shelf.find((e) => e.file === 'prd-34-the-doorstep.md')
    expect(doorstep).toBeDefined()
    // Re-derive rather than trust: this fails, naming the file, the day prd-34
    // gets a milestone — at which point this assertion (and this comment) are
    // the ones that need updating, per the issue's own instruction to verify
    // rather than assume.
    expect(liveManifest().entries.get(doorstep!.number)).toBeUndefined()
    expect(violationsIn([doorstep!], liveManifest())).toEqual([])
  })

  it('every live-shelf PRD has a manifest row, except the named no-milestone allowlist', () => {
    expect(
      unmappedLiveShelf(liveShelfEntries(), liveManifest()),
      'These PRDs are on the live shelf with no row in .swarm/prd-milestones.txt. If you just ' +
        'added one, regenerate and commit the manifest: scripts/dev/prd-milestones.sh. If the PRD ' +
        'genuinely has no milestone, add it to NO_MILESTONE_ALLOWLIST in this file and say why. ' +
        'An empty list here would also mean the manifest failed to parse at all.',
    ).toEqual([])
  })

  it('the floor names a PRD whose row is missing, however it went missing', () => {
    const shelf = liveShelfEntries()
    const manifest = liveManifest()
    // A row deleted, a key the generator never spelled, a line silently skipped as
    // malformed: all three arrive here as "no entry", and all three must be LOUD.
    const stripped: Manifest = { generatedAt: manifest.generatedAt, entries: new Map(manifest.entries) }
    const victim = shelf.find((e) => !NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(victim).toBeDefined()
    stripped.entries.delete(victim!.number)
    // toContain, not toEqual: this test consumes the REAL shelf, so an unrelated PRD
    // added without a manifest row would otherwise make it fail naming the wrong file
    // — a test failing for a reason it does not claim.
    expect(unmappedLiveShelf(shelf, stripped)).toContain(victim!.file)
    // Scoped to the ALLOWLISTED entry, not the whole shelf. Asserting emptiness over
    // the real shelf here duplicated the dedicated floor test one screen up, and made
    // this test fail — with no message — whenever any unrelated PRD lacked a row. The
    // claim is "the allowlisted one stays silent", so that is what is asserted.
    const allowlisted = shelf.filter((e) => NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(allowlisted.length, 'the allowlist must actually match something on the live shelf').toBeGreaterThan(0)
    expect(unmappedLiveShelf(allowlisted, manifest)).toEqual([])
  })

  it('a CRLF manifest does not silently disarm the law — it reddens the floor instead', () => {
    // The blocker this file shipped with: `.swarm/*.txt` was eol-unspecified, so a
    // Windows checkout delivered `\r`-terminated rows, NO row matched, and the law
    // reported zero violations against a real one. `.gitattributes` now pins the file;
    // this proves that even if it did not, the failure is loud rather than vacuous.
    const crlf = readFileSync(MANIFEST_PATH, 'utf8').replace(/\n/g, '\r\n')
    const parsed = parseManifest(crlf)
    expect(parsed.entries.size, 'the \\r?$ tolerance must keep CRLF rows parseable').toBeGreaterThan(0)
    const emptied: Manifest = { generatedAt: parsed.generatedAt, entries: new Map() }
    expect(unmappedLiveShelf(liveShelfEntries(), emptied).length).toBeGreaterThan(0)
  })

  it('the glob hazard: docs/prds/ non-PRD markdown files are not read as PRDs', () => {
    const matched = matchPrdFilenames([
      'README.md',
      'reconciliation-2026-08-22.md',
      'retained-prds-review-2026-08-22.md',
      // These three pin the ANCHORING the doc comment credits this test with. Without
      // them the fixture killed only a digits-anywhere mutant: dropping the leading `^`
      // and loosening the tail to `.*\.md$` both survived 8/8.
      'notes-prd-99-x.md',
      'prd-99-x.md.bak',
      'prd-99.md',
      'prd-14-experiment-console.md',
    ])
    expect(matched).toEqual([{ number: '14', file: 'prd-14-experiment-console.md' }])
  })

  it('the manifest is not stale (bound: 14 days — see the doc comment for why a bound, not CI regeneration)', () => {
    const generatedAt = liveManifest().generatedAt
    const now = new Date()
    const future = generatedAt !== undefined && !Number.isNaN(new Date(generatedAt).getTime()) && new Date(generatedAt).getTime() > now.getTime()
    // A future stamp is stale too, but telling the reader it is "older than 14 days"
    // is false, and the prescribed remedy re-reads the same wrong clock. WSL2 clock
    // drift across suspend/resume is this repo's own environment, so this is reachable.
    expect(
      future,
      `.swarm/prd-milestones.txt is stamped ${generatedAt}, which is in the FUTURE relative to ` +
        `this machine's clock. Check the clock before regenerating — scripts/dev/prd-milestones.sh ` +
        `reads the same one, so regenerating now would reproduce this.`,
    ).toBe(false)
    expect(
      isManifestStale(generatedAt, now),
      `.swarm/prd-milestones.txt was generated at ${generatedAt} and is now older than ` +
        `${MAX_MANIFEST_AGE_DAYS} days. This is the staleness bound working as ruled, not a ` +
        `defect in whatever you are changing. Regenerate and commit it: scripts/dev/prd-milestones.sh`,
    ).toBe(false)
  })

  it('mutation: the detector bites when a closed-milestone PRD sits on the live shelf', () => {
    // Real manifest, real entry: prd-52's milestone is closed. Rather than
    // actually moving the real file back out of done/ (that mutation was run
    // by hand — see this commit's own body for the executed proof — a repo-
    // wide integration test earns nothing this pure-function test cannot
    // already prove), simulate the exact shape the law must catch: a
    // closed-milestone PRD's text presented as if it were still on the live
    // shelf.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const putBack: ShelfEntry = { number: closedNumber!, file: `prd-${closedNumber}-put-back.md`, text: 'no exemption declared' }
    expect(violationsIn([putBack], manifest)).toEqual([putBack.file])

    // The control: the same entry, but its milestone is open — must NOT fire.
    const openNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'open')?.[0]
    expect(openNumber).toBeDefined()
    const stillLive: ShelfEntry = { number: openNumber!, file: `prd-${openNumber}-still-live.md`, text: 'no exemption declared' }
    expect(violationsIn([stillLive], manifest)).toEqual([])
  })

  it('mutation: the bound is exactly 14 days — LITERAL dates, so this reddens at 13 and at 15', () => {
    // These dates are written out, NOT derived from MAX_MANIFEST_AGE_DAYS or DAY_MS.
    // The earlier version computed them as (B-1) and (B+1) days, which asserts
    // `(B-1) > B` is false and `(B+1) > B` is true — true for EVERY B. Measured: the
    // whole file stayed 8/8 green with the bound set to 1, 3, 13, 15 and 365, and with
    // DAY_MS set to three days. It pinned the comparison operator, never the number.
    const now = new Date('2026-09-11T00:00:00Z')
    expect(isManifestStale('2026-08-28T00:00:01Z', now)).toBe(false) // 13d 23h 59m — inside
    expect(isManifestStale('2026-08-28T00:00:00Z', now)).toBe(false) // exactly 14d — the boundary is NOT stale
    expect(isManifestStale('2026-08-27T23:59:59Z', now)).toBe(true) // 14d + 1s — outside
    expect(isManifestStale(undefined, now)).toBe(true)
    expect(isManifestStale('not-a-date', now)).toBe(true)
    // A future timestamp is stale, not fresh — a negative age is never > the bound.
    expect(isManifestStale('2026-09-12T00:00:00Z', now)).toBe(true)
  })
})

describe('declaredExemptionReason — ruling 2\'s marker reader, tested directly and independent of the real tree', () => {
  it('no marker present -> no exemption claimed', () => {
    expect(declaredExemptionReason('nothing relevant here')).toBeUndefined()
  })

  it('marker with prose on its own line -> the reason', () => {
    expect(declaredExemptionReason('> **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('marker at true line start with no blockquote at all -> still the reason', () => {
    expect(declaredExemptionReason('**Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('marker after a nested blockquote, or one with extra internal padding -> still the reason', () => {
    expect(declaredExemptionReason('>> **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
    expect(declaredExemptionReason('>   **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('a reason continuing across further blockquote lines is joined and whitespace-collapsed', () => {
    const text = '> **Shelf exemption:** first line\n> continues   here\n> and here.\n\n## Next section'
    expect(declaredExemptionReason(text)).toBe('first line continues here and here.')
  })

  it('a blank blockquote line ends the paragraph — a later, unrelated paragraph is not swept in', () => {
    const text = '> **Shelf exemption:** the real reason stated here.\n>\n> Unrelated prose in a new paragraph.'
    expect(declaredExemptionReason(text)).toBe('the real reason stated here.')
  })

  it('a non-quoted line also ends the paragraph', () => {
    const text = '> **Shelf exemption:** the real reason stated here.\nplain text with no > prefix'
    expect(declaredExemptionReason(text)).toBe('the real reason stated here.')
  })

  it('CRLF line endings around the marker and its continuation are tolerated', () => {
    expect(declaredExemptionReason('> **Shelf exemption:** first line here\r\n> continues here\r\n')).toBe('first line here continues here')
  })

  // Verify, 2026-09-14: `> **Shelf exemption:** -` and five siblings all passed the first
  // version, which implemented only `reason.length > 0`. This test's TITLE already claimed
  // "placeholder", but only its EMPTY-string assertions backed that claim — a test whose
  // title claims more than it checks is this repo's own recorded defect shape. Each string
  // below is now actually asserted, not merely named.
  it('a placeholder reason is not an exemption, whatever shape the placeholder takes', () => {
    for (const placeholder of ['-', 'TBD', 'n/a', '.', 'x', '**', '​']) {
      expect(declaredExemptionReason(`> **Shelf exemption:** ${placeholder}`), `placeholder ${JSON.stringify(placeholder)} must not be an exemption`).toBeUndefined()
    }
  })

  it('an empty declaration is not an exemption — the marker alone convicts', () => {
    expect(declaredExemptionReason('> **Shelf exemption:**\n')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:**   \n')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:**\n>\n> more text after a paragraph break')).toBeUndefined()
  })

  it('a reason at or just above the substance threshold is an exemption; one word short is not', () => {
    // Pins MIN_REASON_WORDS as a real boundary, the same way the manifest's 14-day bound
    // is pinned with literal dates rather than derived from the constant it tests.
    expect(declaredExemptionReason('> **Shelf exemption:** two words')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:** exactly three words')).toBe('exactly three words')
  })

  // The three findings verify raised all collapse into one class: the reader must find the
  // first DECLARATION, not the first OCCURRENCE. Every case below is a form the marker can
  // appear in WITHOUT being a declaration, or a case where more than one occurrence exists
  // and only one may govern.

  it('a marker sitting inside an HTML comment is not a declaration — single-line and multi-line', () => {
    expect(declaredExemptionReason('<!-- **Shelf exemption:** still needed, see #428 -->')).toBeUndefined()
    expect(declaredExemptionReason('> <!-- **Shelf exemption:** still needed,\n> see #428 -->')).toBeUndefined()
  })

  it('a marker sitting inside a fenced code block is not a declaration — backtick and tilde fences', () => {
    expect(declaredExemptionReason('```md\n> **Shelf exemption:** <reason>\n```\n\nNothing is declared here.')).toBeUndefined()
    expect(declaredExemptionReason('~~~\n**Shelf exemption:** example only\n~~~')).toBeUndefined()
  })

  it('a marker sitting inside an indented code block (4 spaces or a tab) is not a declaration', () => {
    expect(declaredExemptionReason('    **Shelf exemption:** this is example code, not a declaration')).toBeUndefined()
  })

  it('a marker preceded by other prose on the same line is a MENTION, not a declaration, and is skipped', () => {
    expect(declaredExemptionReason('> The form is called **Shelf exemption:** and every PRD should have one.')).toBeUndefined()
    // The mention sitting in a code span, this file's own PRDs' self-reference shape:
    const mentionOnly = "> Declared for #428: the paragraph above is what the law reads, keyed on the\n> `**Shelf exemption:**` marker rather than on this file's name."
    expect(declaredExemptionReason(mentionOnly)).toBeUndefined()
  })

  it('a real declaration is found even when a MENTION of the marker precedes it in the same document', () => {
    const text = '> The form is **Shelf exemption:** described here.\n>\n> **Shelf exemption:** prd-55 depends on this ruling directly.'
    expect(declaredExemptionReason(text)).toBe('prd-55 depends on this ruling directly.')
  })

  it('two genuine declaration lines in one document — the FIRST governs, not the last', () => {
    // Distinct from the mention cases above: both lines here independently satisfy
    // "starts with the marker, has substance". First-match is a deliberate choice, not
    // an accident of scanning order, and this is what would redden a first-vs-last mutant
    // in a document that (unlike today's four real PRDs) actually contains two.
    const text = '> **Shelf exemption:** the first real reason stated here.\n\n> **Shelf exemption:** a different second reason stated here.'
    expect(declaredExemptionReason(text)).toBe('the first real reason stated here.')
  })

  it('mutation: indexOf vs lastIndexOf is pinned by CONTENT — a real declaration followed by a self-reference mention returns the DECLARATION, not the mention', () => {
    // This is the exact shape all four exempted PRDs carry: the declaration, then a later
    // sentence quoting the marker (in a code span) to tell a human reader where the law
    // looks. Verify measured the first version 21/21 green under `indexOf` -> `lastIndexOf`
    // because nothing asserted WHICH occurrence's text came back.
    const text = "> **Shelf exemption:** prd-55 depends on this ruling directly.\n>\n> Declared for #428, read via the\n> `**Shelf exemption:**` marker."
    expect(declaredExemptionReason(text)).toBe('prd-55 depends on this ruling directly.')
  })

  it('the reader never inspects a filename — only violationsIn does, and only via the manifest number', () => {
    // Pinned so a future refactor cannot quietly add a filename parameter and start
    // keying the exemption on identity, the exact failure mode this issue names.
    expect(declaredExemptionReason.length).toBe(1)
  })
})
