import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * prd56 ruling 1's law — a PRD whose milestone is closed belongs under
 * `docs/prds/done/`, and this fails naming every file that is not.
 *
 * A location is reasoned FROM in this repo, not just stored: `docs/follow-up-292.md`
 * argued that a PRD sitting in `docs/prds/` rather than `docs/prds/done/` makes its
 * ruling live rather than archival, and `#416`'s enumeration classified a finished PRD
 * as a current document, and nearly edited its prose, for exactly that reason. Five
 * PRDs (`prd-25`, `prd-27`, `prd-43`, `prd-50`, `prd-52`) had closed milestones and
 * unarchived files when this law was written; prd56 wave 1 moved them in the same
 * commit as this file, so the law lands green rather than convicting its own evidence.
 * This is a SIBLING of `doc-citation-law.test.ts`, not a replacement for it: that law
 * proves a cited path exists, this one proves a PRD's shelf agrees with its milestone.
 *
 * Lives under `packages/server/` for the reason every sibling law here already gives:
 * the root vitest config globs `packages/*`, so a root-level test would never run and
 * would be its own vacuous law.
 *
 * ## Why a committed manifest, and not a live `gh` call (ruling 1)
 *
 * The suite must run offline: CI runs it on ten legs, this repo's own sibling laws
 * already derive tracker facts from `git log` rather than `gh` for the identical
 * reason, and a review seat could not run this suite at all this week because its
 * sandbox denied `gh`'s subprocess and socket access. A law that needs a token is a
 * law that gets skipped. `.swarm/prd-milestones.txt`, regenerated by
 * `scripts/dev/prd-milestones.sh` and committed like `.swarm/coupling.txt` beside it,
 * is what this file reads instead.
 *
 * ## The manifest's own staleness (prd56's open question, closed here)
 *
 * A committed manifest can itself drift out of step with GitHub the moment a
 * milestone opens or closes and nobody reruns the generator. Two candidates were
 * weighed:
 *
 *   1. Regenerate in CI and fail the build when regeneration would change the file.
 *   2. Bound the manifest's own age and fail once it is older than that bound.
 *
 * **This law takes (2) — a staleness bound of {@link MAX_MANIFEST_AGE_DAYS} days —
 * and (1) loses for two reasons.** First, (1) needs a `gh` token in a CI job, which
 * is the exact dependency ruling 1 removes from the SUITE — moving it into a
 * different CI step still leaves the repository unable to certify this law from a
 * bare clone with no network, where (2) can. Second, and more basic: PRD milestones
 * close through an operator act on GitHub, which no push to this repository causes —
 * regenerate-in-CI only ever runs on a push, so it would certify freshness at the
 * last commit's time, not at the time anyone actually reads the verdict, and a stale
 * manifest sitting untouched between pushes would report itself perfectly fresh
 * forever. A bound is honest about what it cannot promise (the manifest might have
 * gone stale seconds ago and still pass) rather than silently wrong about it.
 *
 * 14 days, not 30: `docs/prds/reconciliation-2026-08-22.md` records nine PRDs moved
 * to `done/` in one batch, and prd56's own Evidence section found five had drifted
 * back within three weeks (21 days) of that batch. A bound wider than the observed
 * recurrence interval would still read green while the exact drift this law exists
 * to catch was reaccumulating.
 *
 * ## Ruling 2 — the declared-exemption form (wave 2, #428)
 *
 * "A PRD may stay unarchived when its own text declares why" is ruling 2.
 * {@link declaredExemptionReason} reads it: a PRD's text carrying a genuine DECLARATION of
 * the marker `**Shelf exemption:**` (a line starting with it, outside any comment or code
 * block — see that function's own doc comment for the full grammar) followed by prose that
 * clears a substance threshold is exempt from this law; a PRD with no such declaration, or
 * one with nothing but a placeholder behind it, is not, and reads exactly as it did before
 * this wave — "no exemption claimed", not an error. The reason may continue across further
 * blockquote lines (each starting with `>`) after the marker's own line, the same
 * `> **Label:** wrapped prose` shape this file's own PRDs already use elsewhere (see this
 * PRD's own `**Outcome:**` blocks); a blank quoted line (`>` alone) ends the paragraph, so a
 * later, unrelated quoted paragraph is never swept into the reason.
 *
 * **Keyed on the declaration, never on the document.** The rejected alternative is a list
 * of allowed filenames (or a check for `prd-17` by name): it passes today and is a fitted
 * instrument, because the next PRD with a real reason to stay would not be on the list, the
 * law would convict it, and the fix would be adding a second name rather than writing a
 * reason. `declaredExemptionReason` never inspects a file's name, only its text — proven
 * below by a synthetic file carrying the marker under a name this repo has never used.
 *
 * The second rejected alternative is a flag that suppresses the whole law rather than one
 * file's violation. Proven below: a synthetic closed-milestone, no-reason entry is convicted
 * in the SAME `violationsIn` call that clears the real prd-17 entry, so the form cannot be
 * "never fire".
 *
 * **A third rejected alternative, added at verify (2026-09-14, `c8709751`).** The first
 * version matched the first OCCURRENCE of the marker via a bare `text.indexOf`, not the
 * first DECLARATION — concealable behind an HTML comment or a fenced code block, confusable
 * with a mid-sentence mention of the marker itself, and unpinned as to WHICH occurrence
 * governs when a file (every one of the four this wave exempts) contains it twice. Two
 * independent review seats plus the orchestrator found this, all EXECUTED: an HTML-comment
 * concealment and a `lastIndexOf` mutation both left the suite 21/21 green. The rejected fix
 * was a word blacklist ("TBD", "n/a", "-", …) for the sibling defect — placeholder reasons
 * ("`> **Shelf exemption:** -`" and five others) also passed — for the same reason the
 * filename list was rejected above: the next placeholder is never on the list. Both are
 * fixed structurally instead — see {@link declaredExemptionReason}'s own doc comment.
 *
 * **Four subjects carry a declared reason; one is archived instead**, and the two are not
 * interchangeable (prd-56, operator-ruled 2026-09-13, recorded on #428): `prd-17`
 * (`docs/follow-up-292.md` holds an open item against ruling 3), `prd-53` (`prd-55`'s waves
 * build live on its rulings), `prd-14` and `prd-20` (`prd-55` and `prd-34`, respectively,
 * each cite a still-live PRD's rulings from a document that is itself unfinished) each
 * declare one. `prd-48` had no such argument found for it and moved to `docs/prds/done/`
 * instead, taking ruling 1's ordinary path — reaching for the exemption to paper over an
 * archival candidate is exactly what would turn the form into a way to switch the law off.
 * Adding the two late subjects (`prd-14`, `prd-20`, discovered only once the manifest was
 * actually regenerated) required editing no code in this file — only their own PRD text —
 * which is itself evidence the form is keyed on the declaration and not on which PRD asks.
 *
 * ## The mirror case still has its instance — prd-56's open question is stale, and now ruled
 *
 * prd-56's Open Questions ask whether the law should also fail an ARCHIVED PRD whose
 * milestone is still OPEN, and left it **open, not ruled**, on the stated ground that "no
 * instance exists today". That ground stopped being true when wave 1 moved
 * `prd-43-the-claim-is-a-test.md` into `done/` on the strength of its then-closed milestone
 * and the milestone then REOPENED (1 open issue, no `closed_at`). #459 is the ruling: the law
 * stays one-way, deliberately, because a closed-milestone PRD on the live shelf misleads a
 * reader into treating a shipped ruling as open, while an archived PRD with a reopened
 * milestone only reads as stale — nobody is misled into treating it as settled.
 *
 * Nothing here goes red, and that is by design rather than by oversight: {@link liveShelfEntries}
 * reads only `docs/prds/`, never `docs/prds/done/`, so an archived PRD is outside this law's
 * sweep whatever its milestone says. The row is left as the generator wrote it. #459 owns
 * writing the ruling into prd-56's own document; this file only needed its citation updated
 * once #459 gives it a number to cite, which is #459's job, not this wave's.
 *
 * What IS resolved, by this wave regenerating the manifest: `prd14`, `prd17`, `prd20`, `prd48`
 * and `prd53` all flipping to closed no longer fails the law, because four now carry ruling
 * 2's form and the fifth (`prd48`) moved to `done/` in this same commit. Measured before this
 * wave's changes: regenerating exited 1 naming all five `docs/prds/*.md` files by name.
 *
 * ## Wave 3 — one predicate, tabulated (prd56 w3, #484)
 *
 * Wave 2's own fix re-review found four places where {@link declaredExemptionReason} disagreed
 * with what a person reading the RENDERED document sees. All four are one question — "is this
 * line prose or code?" — asked twice (once by the declaration scan, once by the continuation
 * loop) with two different answers depending on where the question was asked. {@link
 * classifyLines} is now the single predicate both scans call; this table is its truth table,
 * enumerated BEFORE any of the four gaps was patched, per the issue's own First Instruction.
 *
 * `code?` is `classifyLines`'s per-line verdict — a code line can never start or continue a
 * declaration. Gaps are cited by #484's own numbering; every gap row has an "unlisted spelling"
 * sibling proving the repair is not just the reported string.
 *
 * | # | form (one representative line) | code? | declared / continues? | note |
 * |---|---|---|---|---|
 * | 1 | `**Shelf exemption:** reason` — column 0, no quote | no | yes | baseline |
 * | 2 | `> **Shelf exemption:** reason` — one quote level | no | yes | baseline |
 * | 3 | `>   **Shelf exemption:** reason` — quote + 1-3 residual spaces | no | yes | CommonMark allows up to 3 spaces of container-relative indent before a paragraph still counts as unindented |
 * | 4 | `>     **Shelf exemption:** reason` — quote + 4+ residual spaces | **yes**, indented code | no | **gap 2** — the base blockquote-stripping function consumed ALL post-`>` whitespace, so this could never be classified as code |
 * | 5 | `>> **Shelf exemption:** reason` — nested quote | no | yes | each `>` gives up at most one optional space, same rule applied twice |
 * | 6 | `prose **Shelf exemption:** reason` — marker mid-line | no | no | a MENTION, not a declaration — the marker must start the line's content |
 * | 7 | ` ``` ` fence at column 0, marker inside | yes | no | baseline fence |
 * | 8 | `  ``` ` fence indented 1-3 columns, no quote, marker inside | **yes** | no | **gap 1** — CommonMark allows an indented fence opener; anchoring `FENCE_OPEN_RE` at column 0 missed it |
 * | 9 | `    ``` ` — backtick run indented 4+ columns, no quote, marker on the UNINDENTED line right after | **yes, but only that ONE line** | **the marker is DECLARED** | **corrected 2026-09-14 (round 2, finding 1, #484).** The base table claimed this "hides its interior" the way row 8 does; it does not, and the CODE was already right — only the TABLE was wrong. A 4+-column-indented backtick run is CommonMark indented code, never a fence opener (nothing "opens"), so only that one physical line is code; the very next, unindented line is an ordinary, visible paragraph — read exactly as row 1 would read it. Control: a genuine column-0 fence (row 7) still hides its interior. |
 * | 10 | same shape, `~~~` tilde fence | **yes, but only that ONE line** | **declared**, same as row 9 | the fence CHARACTER was never what mattered; the INDENT was always the (mis-)documented part — same correction as row 9. |
 * | 11 | `` > ``` `` fence inside one quote level | yes | no | fence-open is checked AFTER blockquote-marker consumption, with `credit` already under 4 |
 * | 12 | `` >    ``` `` — quote + 1-3 residual columns + fence | yes | no | same allowance as row 3, applied to a fence instead of the marker |
 * | 13 | `    marker` — 4-column indented code, no quote | yes | no | baseline indented code — **contrast with row 9**: here the MARKER's own line is indented, so it is rightly hidden; row 9 indents a FENCE-LOOKING line instead, whose only casualty is itself. Opposite consequences for whatever comes after — they were never the same case, which is exactly what round 2's finding 1 corrected. |
 * | 14 | `\tmarker` — a BARE leading tab, no quote, no preceding whitespace at all | yes | no | a tab starting at column 0 advances to column 4 — the full indented-code threshold in one character. **This is true only because nothing has already moved the starting column** (round 2, finding 2, #484) — see rows 30-36 for what happens once a blockquote's own marker has moved it, which is the case the base table's "a tab counts the same as 4 spaces" wrongly generalized from this one row. |
 * | 15 | `<!-- marker -->` — comment, single line | blanked, no | no | baseline comment |
 * | 16 | multi-line `<!--` … `-->` wrapping a marker line | blanked, no | no | comment blanking is index-preserving across lines |
 * | 17 | `<!--` with no matching `-->` anywhere in the document | blanked to EOF, no | no | **gap 4a, fail open** — the old regex required a closing `-->` to match at all, so an unterminated comment blanked NOTHING and a declaration below it wrongly counted |
 * | 18 | `` `<!-- looks like a comment -->` `` — comment syntax inside an inline code span | **not blanked**, whatever it says | as written | **gap 4b, fail closed** — the old code blanked this too, deleting real, visible prose and convicting a correct declaration |
 * | 19 | `` `**Shelf exemption:**` `` — the marker itself inside a code span, at column 0 | no | no | never needs special-casing — a code span always opens with a backtick, so `startsWith(MARKER)` is already false |
 * | 20 | two genuine declaration lines in one document | no / no | the first wins | pinned by content, not merely "is defined" |
 * | 21 | a declaration, then a later MENTION of the marker (this file's own cross-reference convention) | no / no | the declaration, never the mention | a mention never starts its own line |
 * | 22 | continuation: further `>`-quoted prose lines | no | swept into the reason, whitespace-collapsed | baseline |
 * | 23 | continuation: a blank quoted line (`>` alone) | n/a (blank) | paragraph ends | baseline |
 * | 24 | continuation: a non-quoted line | no | paragraph ends | baseline |
 * | 25 | continuation: end of document | n/a | paragraph ends | baseline |
 * | 26 | continuation: a quoted FENCED block | **yes** | paragraph ends before it | **gap 3, fence variant** — the old continuation loop had no fence check at all, so quoted code text cleared the substance threshold |
 * | 27 | continuation: a quoted INDENTED-code line | **yes** | paragraph ends before it | **gap 3, indent variant** — same defect; the unlisted-spelling sibling proving it is not only the fence spelling |
 * | 28 | placeholder reason (`-`, `TBD`, `n/a`, `.`, `x`, `**`, a bare zero-width space) | no | below {@link MIN_REASON_WORDS}, not declared | baseline |
 * | 29 | CRLF line endings anywhere in the above | normalized first | unaffected | `\r\n?` is collapsed to `\n` before any of the above runs |
 *
 * **Rows 30-36 — round 2's space/tab-prefix class (finding 2, #484), a column-arithmetic verdict per
 * row, written down BEFORE the arithmetic was fixed, per the same First Instruction wave 3 opened
 * with.** `col` tracks the ABSOLUTE column ({@link nextTabStop}: a tab advances to the next multiple
 * of 4 from wherever it starts, never a flat +4); `credit` is `col` minus the column right after the
 * blockquote marker's own one-column allowance — CommonMark's indented-code test is `credit >= 4`.
 *
 * | # | prefix after `>` | arithmetic | credit | code? | declared? | note |
 * |---|---|---|---|---|---|---|
 * | 30 | one tab, nothing else (`>\t`) | tab at col 1 -> its own next stop, col 4; FULLY consumes the marker's allowance | 0 | no | yes | a bare `>` + tab is a paragraph, and always was — **correction to the record**: an earlier round wrongly called this a fail-open exemption. |
 * | 31 | two tabs (`>\t\t`) | tab 1: col 1 -> 4 (marker's allowance); tab 2 starts EXACTLY on a stop (col 4) -> col 8 | 4 | yes | no | at the threshold exactly — the control proving two tabs alone still convicts. |
 * | 32 | space then tab (`> \t`) | the LITERAL space satisfies the marker (col 1 -> 2); the tab is now ordinary content-indentation, starting at col 2 -> its own next stop, col 4 | 2 | no | yes | **the regression, now fixed.** The base implementation counted the tab as a flat +4 regardless of where it started, reading this as indented code. |
 * | 33 | two spaces then tab (`>  \t`) | one space satisfies the marker (col 1 -> 2); the second space is ordinary content-indentation (col 2 -> 3), then the tab (col 3 -> its own next stop, col 4) | 2 | no | yes | same regression as row 32, one more literal space ahead of the tab. |
 * | 34 | space, tab, space (`> \t `) | marker's space (col 1 -> 2); tab from col 2 -> col 4 (2 credit); trailing space (col 4 -> 5, 1 more credit) | 3 | no | yes | same regression, one column under the threshold — the trailing space cannot push it over on its own. |
 * | 35 | two spaces, tab, space (`>  \t `) | marker's space (col 1 -> 2); space (col 2 -> 3); tab (col 3 -> 4); space (col 4 -> 5) | 3 | no | yes | same regression as row 34, reached by a different route — pins that the arithmetic is genuinely columnar, not "which literal characters appear". |
 * | 36 | space then two tabs (`> \t\t`) | marker's space (col 1 -> 2); tab 1 (col 2 -> its own next stop, col 4: 2 credit); tab 2 starts exactly on a stop (col 4 -> 8: 4 more credit) | 6 | yes | no | **control: proves the fix is not "any tab now exempts".** Enough tab-driven credit still convicts once a space has already spent the marker's one-column allowance — only the four prefixes in rows 32-35 (whose total genuinely stays under 4) read as paragraphs. |
 * | 37 | tab IMMEDIATELY after `>`, then 2+ spaces (`>\t  `, `>\t   `) | this reader: marker consumes the tab whole to col 4, then 2-3 spaces | 2-3 | no | yes | **KNOWN DIVERGENCE FROM COMMONMARK, recorded at the review of #493 rather than fixed.** CommonMark takes ONE COLUMN of that tab and leaves two behind (spec "Tabs", example 6), so its credit is 4-5 and the line is indented CODE — hidden from a reader, read as a declaration here. Fails OPEN. Unreachable in this corpus: no PRD on either shelf contains a tab (EXECUTED). Closing it means partial-tab consumption in {@link stripBlockquoteMarkers}, a structural change rather than a cell — same bucket as the container tracking and lazy continuation this wave books out. |
 *
 * Unreachable today, and why: rows 4, 8, 9, 10, 12, 17, 18, 26, 27 and 30-36 all require a syntactic
 * shape — an indented fence, a comment wrapping only part of a line, quoted code following a
 * placeholder, a tab anywhere at all — that no live-shelf PRD's text currently contains, verified by
 * reading the four declarations these rows would otherwise misjudge (`prd-17`, `prd-53`, `prd-14`,
 * `prd-20`) and finding none of them use any of these forms. That is why this is a repair to the
 * READER's grammar, not a repair to any PRD's text — see "EXPLICITLY OUT of scope" on #484.
 *
 * ## Wave 3, round 2 — the table was wrong, and the tab arithmetic was missing (#484)
 *
 * A fix re-review of wave 3 found two NEW defects — a different axis from the four gaps above,
 * which were about which LINES are code. These are about the TABLE stating a verdict the code does
 * not produce, and about tab COLUMN arithmetic, never present at all.
 *
 * **Finding 1 — rows 9 and 10 were simply wrong, and the code was already right.** The base table
 * claimed a 4+-column-indented fence-looking line "hides its interior" the same way row 8's validly
 * recognized 1-3-column-indented fence does. It does not: CommonMark never treats an indented opener
 * as a fence at all, so a 4+-indented ``` `` ``` is ordinary indented code for that ONE line only,
 * and the very next (unindented) line is a plainly visible paragraph. Restoring the base ordering
 * (fence-open checked before the indent guard) leaves the whole suite green, because
 * {@link FENCE_OPEN_RE} never matches a 4+-indented run either way (trimming caps at 3 columns) — the
 * code was never in question, only the sentence describing it. Fixed in the rows themselves and in
 * row 13's note, which now says explicitly why the two rows are not the same case.
 *
 * **Finding 2 — a fail-closed regression on a SPACE-then-TAB blockquote prefix
 * (`> \t`, `>  \t`, `> \t `, `>  \t `).** Round 1's blockquote-stripping function (since replaced by
 * {@link stripBlockquoteMarkers}) consumed one WHITESPACE CHARACTER per blockquote level, which is
 * correct
 * for a literal space and wrong for a tab, whose column-width depends on where it starts — the old
 * code treated a tab anywhere as an automatic flat +4, so a tab that in fact only closed a 2-column
 * gap (because a literal space had already consumed the marker's own one-column allowance) still
 * read as a full 4-column indent, convicting four prefixes that CommonMark reads as ordinary,
 * visible paragraphs. **The root cause was the instrument, not a cell to patch**: nothing anywhere
 * expanded a tab to the column it actually reaches. {@link nextTabStop}, {@link stripBlockquoteMarkers}
 * and {@link measureIndent} replace the character-counting approach with real column arithmetic —
 * fixed ONCE, in {@link classifyLines}, so both the declaration scan and the continuation loop (which
 * had the identical blind spot — a continuation line of `>   \t` swept CommonMark indented code into
 * the reason, gap 3's own failure mode in a spelling round 1 never tested) inherit the same fix
 * rather than four prefixes being special-cased at either call site. Table rows 30-36 carry the
 * worked arithmetic for every prefix in this class, including two CONTROLS (rows 31 and 36) proving
 * the fix still convicts once enough columns are actually spent — this is a corrected instrument, not
 * a new "tabs are always fine" exemption.
 *
 * **Two claims from round 1 were false and are corrected here, not merely narrowed:** round 1's
 * blockquote-stripping function's doc comment claimed CommonMark-faithful behavior "rather than a
 * rule invented to make one test pass" — true of the SPACE case, false of the TAB case, which this
 * round's {@link stripBlockquoteMarkers} brings much closer without reaching (row 37 is the
 * remaining gap, recorded at the review of #493); and table row 14's "a tab
 * counts the same as 4 spaces" was true only for a bare leading tab with nothing ahead of it, never
 * stated as scoped that way.
 *
 * Explicitly out of scope for this round, same as wave 3's own scope note: no PRD text, no
 * dispositions; comments whose span crosses a fence delimiter (a TERMINATED one does this too, not
 * only an unterminated one — that whole class is #459's, already widened to cover it); and container
 * tracking for list items or lazy continuation (`- **Shelf exemption:**` convicting a visible
 * declaration is real and pre-existing, and is outside this wave's four gaps).
 *
 * ## The glob hazard (verified against the real tree before this law was written)
 *
 * Three non-PRD markdown files live in `docs/prds/`: `README.md`,
 * `reconciliation-2026-08-22.md` and `retained-prds-review-2026-08-22.md`. A sweep
 * that globs `docs/prds/*.md` and pulls a milestone number out of ANY digits in the
 * filename misfires on the latter two — `2026-08-22` is a date, not a PRD number.
 * {@link PRD_FILE_RE} is anchored (`^prd-(\d+)-`), not a digits-anywhere match, for
 * exactly that reason; the glob-hazard test below proves it against all three by
 * name. `docs/prds/done/` holds none of the three, so the hazard is one-sided —
 * verified, not assumed, the same way `doc-citation-law.test.ts`'s own glob-gotcha
 * note insists on.
 */

const REPO_ROOT = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
const PRDS_DIR = path.join(REPO_ROOT, 'docs', 'prds')
const MANIFEST_PATH = path.join(REPO_ROOT, '.swarm', 'prd-milestones.txt')

/** `prd-25-the-third-platform.md` -> `25`. Anchored to the START of the filename — see the glob-hazard note above. */
const PRD_FILE_RE = /^prd-(\d+)-.+\.md$/

interface ShelfEntry {
  number: string
  file: string
  text: string
}

/** Pure: which filenames are PRDs, and their numbers — tested on synthetic input below, independent of the real `docs/prds/` listing. */
function matchPrdFilenames(filenames: readonly string[]): { number: string; file: string }[] {
  return filenames
    .map((file) => ({ file, m: PRD_FILE_RE.exec(file) }))
    .filter((r): r is { file: string; m: RegExpExecArray } => r.m !== null)
    .map((r) => ({ number: r.m[1]!, file: r.file }))
}

function liveShelfEntries(): ShelfEntry[] {
  return matchPrdFilenames(readdirSync(PRDS_DIR)).map(({ number, file }) => ({
    number,
    file,
    text: readFileSync(path.join(PRDS_DIR, file), 'utf8'),
  }))
}

type MilestoneState = 'open' | 'closed'
interface ManifestEntry {
  state: MilestoneState
  closedAt: string | undefined
}
interface Manifest {
  generatedAt: string | undefined
  entries: Map<string, ManifestEntry>
}

const GENERATED_AT_RE = /^#\s*generated-at:\s*(\S+)\s*$/m
/**
 * `\r?$` is the blocker fix, not decoration: `.swarm/prd-milestones.txt` is read with
 * `split('\n')`, so on a CRLF checkout every line arrives ending `\r`. `\S` cannot match
 * `\r`, so `$` was unreachable and EVERY row silently failed to match — `parseManifest`
 * returned an empty map and {@link violationsIn} reported NO violations while a
 * closed-milestone PRD sat on the live shelf. Verified on a CRLF copy: 0 rows parsed,
 * the law green on a real violation. `.gitattributes` now pins `.swarm/*.txt` to `eol=lf`
 * so the bytes are right in the first place; this tolerates the `\r` anyway, because a
 * law that goes VACUOUS rather than red is the one failure mode worth belt-and-braces.
 * Only `\r` is tolerated, deliberately — arbitrary trailing whitespace would also accept
 * a row a corrupt generator wrote, which {@link unmappedLiveShelf} must be able to see.
 */
const MANIFEST_ROW_RE = /^(\d+)\t(open|closed)\t(\S+)\r?$/

/** Pure: parses the manifest format `scripts/dev/prd-milestones.sh` writes. A line that is not a comment and does not match the row shape is silently skipped, matching `.swarm/coupling.txt`'s own "blank/comment lines are skipped" convention. */
function parseManifest(text: string): Manifest {
  const generatedAt = GENERATED_AT_RE.exec(text)?.[1]
  const entries = new Map<string, ManifestEntry>()
  for (const line of text.split('\n')) {
    const m = MANIFEST_ROW_RE.exec(line)
    if (!m) continue
    entries.set(m[1]!, { state: m[2] as MilestoneState, closedAt: m[3] === '-' ? undefined : m[3] })
  }
  return { generatedAt, entries }
}

function liveManifest(): Manifest {
  return parseManifest(readFileSync(MANIFEST_PATH, 'utf8'))
}

/** The exact marker {@link declaredExemptionReason} looks for — see the Ruling 2 doc comment above for the form's rationale and its two rejected alternatives. */
const EXEMPTION_MARKER = '**Shelf exemption:**'

/**
 * A declared reason must contain at least this many "words" — runs of 2+ letters — to
 * count as substance rather than a placeholder. A THRESHOLD, not a blacklist of rejected
 * strings ("TBD", "n/a", "-", "x", "**", a bare zero-width space all score 0 or 1): a
 * blacklist is the same fitted instrument this issue already rejects for the exemption
 * itself — the next placeholder is never on the list, and the fix becomes adding a fourth
 * string rather than asking whether ANY placeholder should pass. A single letter, a bare
 * punctuation mark, and an invisible character all score zero because `[A-Za-z]{2,}`
 * requires two-plus letters in a row; a real reason is a sentence, which structurally
 * requires several such runs. See the "declaredExemptionReason" describe block below for
 * every scored form, each checked directly.
 */
const MIN_REASON_WORDS = 3

/**
 * The next CommonMark tab stop at or after `col` — tabs advance to the next multiple of 4, never
 * by a flat +4. **Missing entirely was round 2's finding 2 (#484):** the base implementation
 * counted CHARACTERS ("a tab is one guard-firing character, same as 4 spaces"), not COLUMNS, so
 * `> \t` — a literal space, then a tab — read the tab as an automatic 4-column indent regardless of
 * where it actually started. It does not: a tab's width depends on the column it starts from. See
 * {@link stripBlockquoteMarkers} and {@link measureIndent}, the two places this now feeds, and table
 * rows 30-36 for the worked arithmetic.
 */
function nextTabStop(col: number): number {
  return col + (4 - (col % 4))
}

/**
 * Consumes zero or more levels of a CommonMark blockquote marker (up to 3 leading spaces, `>`,
 * then AT MOST one following whitespace CHARACTER — space or tab, consumed WHOLE) from the START of
 * `line`, tracking the ABSOLUTE column reached (tab-stop correct, via {@link nextTabStop}) rather
 * than a character count. Returns the index and column right after the last level consumed, and
 * whether at least one level was found at all.
 *
 * **Round 2 correction (finding 2, #484):** wave 3 first fixed this to consume only one WHITESPACE
 * CHARACTER per level rather than a whole run — correct for a literal space, wrong for a tab, whose
 * column-width is not fixed. The fix is not "count differently for a tab"; it is to stop counting
 * characters at all and track the column a real CommonMark implementation tracks. Consuming the tab
 * character WHOLE, and crediting the marker with wherever that lands (its own next tab stop, not a
 * flat +1), is what shipped: `>` + one tab alone lands the baseline at column 4 (the tab starts at
 * column 1, its own next stop) with nothing left over — a bare `>\t` is a paragraph, not code, and
 * always was; `>` + a literal space + a tab lands the baseline at column 2 (the SPACE is what
 * satisfies the marker, landing on column 2 exactly, same as any other literal space), and the tab
 * is now ordinary CONTENT indentation measured by {@link measureIndent} from that baseline — table
 * rows 30-36 work every case in this class by hand.
 *
 * **It is NOT the entire CommonMark rule, and row 37 is where the two part company.** CommonMark
 * consumes ONE COLUMN of a following tab, not the whole of it, leaving the remainder as ordinary
 * content indentation — spec "Tabs", example 6: `>\t\tfoo` renders as indented code carrying TWO
 * leading spaces, which is only arithmetic if the marker took one column of the first tab and left
 * two behind. Consuming the tab whole hands those columns to the marker instead, so a tab
 * IMMEDIATELY after `>` followed by two or more spaces reads as a paragraph here and as indented
 * code in a renderer. Measured through this reader at the review of #493, and see row 37. The claim
 * narrowed rather than the code changed, deliberately: the divergence is unreachable in this corpus
 * (no PRD on either shelf contains a tab at all, EXECUTED), it fails OPEN in a wave whose other
 * three fail-open gaps are now closed, and partial-tab consumption is a structural change to this
 * instrument rather than a sentence — it belongs with the container tracking and lazy continuation
 * already booked out of this wave, not stapled to it.
 */
function stripBlockquoteMarkers(line: string): { index: number; column: number; quoted: boolean } {
  let index = 0
  let column = 0
  let quoted = false
  for (;;) {
    let i = index
    let col = column
    let spaces = 0
    while (spaces < 3 && line[i] === ' ') {
      i++
      col++
      spaces++
    }
    if (line[i] !== '>') return { index, column, quoted }
    i++
    col++
    if (line[i] === ' ') {
      i++
      col++
    } else if (line[i] === '\t') {
      i++
      col = nextTabStop(col)
    }
    index = i
    column = col
    quoted = true
  }
}

/**
 * Walks past any further leading spaces/tabs from `index`/`column`, continuing the SAME absolute
 * column arithmetic {@link stripBlockquoteMarkers} started, and reports `credit` — the number of
 * COLUMNS gained, which is what CommonMark's "4 or more" indented-code rule actually measures, never
 * a character count. A space always contributes exactly 1; a tab contributes however far it is to
 * its own next stop from wherever it happens to start, which is the entire fix for round 2's finding
 * 2 (#484) — see {@link stripBlockquoteMarkers}'s doc comment and table rows 30-36.
 */
function measureIndent(line: string, index: number, column: number): { index: number; column: number; credit: number } {
  let i = index
  let col = column
  for (;;) {
    if (line[i] === ' ') {
      i++
      col++
      continue
    }
    if (line[i] === '\t') {
      i++
      col = nextTabStop(col)
      continue
    }
    break
  }
  return { index: i, column: col, credit: col - column }
}

/**
 * A fence delimiter line (3+ of the same backtick or tilde). Read after
 * {@link stripBlockquoteMarkers} and {@link measureIndent} have already established that `credit`
 * is under 4 — CommonMark allows a fence opener indented by 0-3 columns relative to its container,
 * the same allowance a paragraph gets, so this regex only ever runs against content that already
 * clears that check. **Applying this regex directly to un-trimmed content was gap 1 (#484): a fence
 * indented 1-3 columns, with no blockquote at all, never matched, so a marker sitting inside it read
 * as a bare top-level declaration.**
 *
 * **A 4-or-more-column-indented run of backticks is NEVER tested against this regex at all (round 2,
 * finding 1, #484) — table rows 9-10.** Once `credit >= 4`, {@link classifyLines} has already
 * classified the WHOLE line as indented code and moved on; CommonMark never treats an indented
 * opener as a fence in the first place; nothing "opens", so there is no fence for a later line to be
 * "inside" — the line right after an indented ``` ``` ``` is an ORDINARY, visible paragraph, read
 * exactly as if the indented line were not there. The base implementation's table said otherwise
 * ("consistent with row 13, not a separate case") — that sentence was wrong, not the code: row 13
 * indents the MARKER (hiding it, correctly); row 9 indents a FENCE-LOOKING line (hiding only ITSELF,
 * with no effect on anything after it). They were never the same case.
 */
const FENCE_OPEN_RE = /^(`{3,}|~{3,})/

/**
 * Replaces the content of every CommonMark inline code span (`` `...` ``, or a longer run of
 * backticks, on a SINGLE line — this file's spans never cross a line break) with a copy that has
 * every `<` neutralized. Used only to decide where a REAL HTML comment can open; the caller must
 * blank matched comments in the ORIGINAL text, never in this masked copy, so a genuine declaration's
 * visible content is never altered by this function itself.
 *
 * **Why:** gap 4b (#484) — a comment-blanking pass with no notion of code spans treats `` `<!--
 * documented here -->` `` (literal comment syntax someone is discussing, not a real comment) exactly
 * like a real one, deletes it, and can convict a real declaration for having "no reason" when the
 * reason was sitting in that span the whole time.
 */
function maskInlineCodeSpans(line: string): string {
  return line.replace(/(`+)([\s\S]*?)\1/g, (_m, ticks: string, inner: string) => ticks + inner.replace(/</g, '\u0000') + ticks)
}

/**
 * Blanks every REAL HTML comment in `text` — non-newline characters inside `<!--...-->` become
 * spaces, so every later line index is unchanged, matching the wave-2 design this replaces. Two
 * fixes layered on that design, both gap 4 (#484):
 *
 * 1. **Code-span aware (fail closed, gap 4b).** Comment boundaries are located in a copy where
 *    {@link maskInlineCodeSpans} has neutralized every `<` inside an inline code span first, so a
 *    span merely discussing comment syntax is never mistaken for a real comment. The blanking
 *    itself is still applied to the ORIGINAL text at the same indices — the mask is scratch, never
 *    output.
 * 2. **Unterminated comments reach end of document (fail open, gap 4a).** The old pattern required
 *    a matching `-->`, so an opener with no closer anywhere in the document matched nothing and
 *    blanked nothing — exactly backwards, since an unclosed HTML comment swallows everything after
 *    it until EOF wherever it is actually rendered. `(?:-->|$)` matches the first closer if one
 *    exists, and the end of the text otherwise, so an unterminated opener now blanks through EOF
 *    instead of leaving every later line visible.
 */
function blankRealHtmlComments(text: string): string {
  const masked = text.split('\n').map(maskInlineCodeSpans).join('\n')
  const re = /<!--[\s\S]*?(?:-->|$)/g
  let result = ''
  let cursor = 0
  let m: RegExpExecArray | null
  while ((m = re.exec(masked))) {
    result += text.slice(cursor, m.index)
    result += m[0].replace(/[^\n]/g, ' ')
    cursor = m.index + m[0].length
  }
  return result + text.slice(cursor)
}

interface ClassifiedLine {
  /**
   * The line's content once every container is peeled off: blockquote markers consumed via
   * {@link stripBlockquoteMarkers}, then any further leading indentation measured via
   * {@link measureIndent} and dropped, provided its `credit` stayed under 4 columns (CommonMark's
   * "still counts as unindented" allowance, measured in COLUMNS — round 2, finding 2, #484 — never
   * in characters). Meaningless (empty) whenever `isCode` is true.
   */
  content: string
  /** True for a fence delimiter, fenced interior, indented-code line, or a line fully inside an HTML comment — a line a declaration can never start OR continue on. */
  isCode: boolean
  /** True when this line carried at least one level of `>` before any stripping — continuation lines must be quoted; the first declaration line itself need not be (table row 1). */
  quoted: boolean
}

/**
 * The single predicate wave 3 exists to build (#484): classifies every line of `text` ONCE, and
 * both the declaration scan and the continuation loop in {@link declaredExemptionReason} read this
 * same array rather than running their own, disagreeing checks. **Gap 3 was exactly that
 * disagreement** — the continuation loop applied no fence or indent check at all, only the
 * declaration line did, so quoted code text after a placeholder reason could clear the substance
 * threshold. There is now nowhere left for the two scans to diverge, because there is only one scan.
 *
 * Indentation is measured in COLUMNS (via {@link stripBlockquoteMarkers} and
 * {@link measureIndent}), not characters — round 2's finding 2 (#484): a bare character count reads
 * a tab as an automatic 4-column indent no matter where it starts, which is only true when nothing
 * has already moved the starting column. Fixing this here, once, is what makes both scans inherit
 * it; a fix that special-cased the four regressed prefixes at either call site would have left the
 * other scan (or the next unlisted prefix) wrong in exactly the way gap 3 already was.
 *
 * See the grammar table above this file's Ruling 2 doc comment for every input row this function is
 * answerable to.
 */
function classifyLines(text: string): ClassifiedLine[] {
  const withoutComments = blankRealHtmlComments(text)
  const out: ClassifiedLine[] = []
  let inFence = false
  let fenceChar = ''
  let fenceLen = 0
  for (const raw of withoutComments.split('\n')) {
    const bq = stripBlockquoteMarkers(raw)
    const indent = measureIndent(raw, bq.index, bq.column)
    const content = raw.slice(indent.index)

    if (inFence) {
      const close = indent.credit <= 3 ? /^(`+|~+)\s*$/.exec(content) : null
      if (close && close[1]![0] === fenceChar && close[1]!.length >= fenceLen) inFence = false
      out.push({ content: '', isCode: true, quoted: bq.quoted })
      continue
    }
    if (indent.credit >= 4) {
      out.push({ content: '', isCode: true, quoted: bq.quoted }) // indented code — gap 2 lives here
      continue
    }
    const open = FENCE_OPEN_RE.exec(content)
    if (open) {
      inFence = true
      fenceChar = open[1]![0]!
      fenceLen = open[1]!.length
      out.push({ content: '', isCode: true, quoted: bq.quoted }) // fence open — gap 1 lives here
      continue
    }
    out.push({ content, isCode: false, quoted: bq.quoted })
  }
  return out
}

/**
 * Ruling 2's declared-exemption reader. Keyed on the DECLARATION, never on the document:
 * any text carrying a genuine declaration is exempt, regardless of which file it lives
 * in — this function never sees a filename, only `text`.
 *
 * **Verify review found the first version matched the first OCCURRENCE of
 * {@link EXEMPTION_MARKER}, not the first DECLARATION** (2026-09-14, `c8709751`,
 * two independent seats plus the orchestrator, all EXECUTED): a bare `text.indexOf` sees
 * a marker sitting inside an HTML comment, a fenced or indented code block, or a
 * mid-sentence MENTION (this very file's own "keyed on the `**Shelf exemption:**` marker"
 * sentences, added deliberately to each PRD as a human-readable cross-reference) exactly
 * as readily as a real declaration — concealing a real one behind an HTML comment left the
 * suite green, and mutating `indexOf` to `lastIndexOf` did too, because every one of the
 * four PRDs this wave exempts contains the marker TWICE and no test pinned WHICH occurrence
 * governs.
 *
 * The fix: a declaration is a LINE whose content — read from {@link classifyLines} — starts
 * with the marker and is not code. The scan returns the FIRST such line; a mid-sentence
 * mention never qualifies, because the marker there is not at the start of its line's content.
 *
 * The reason may continue across further blockquote lines the same way it always did, ending
 * at the first blank quoted line, non-quoted line, or **CODE** line (prd56 wave 3, gap 3,
 * #484 — the continuation walk used to run its own quoted-line regex with no fence or indent
 * check at all, so a quoted fenced or indented block after a placeholder reason could clear
 * {@link MIN_REASON_WORDS} on code text alone; it now reads the exact same `ClassifiedLine`
 * array the declaration scan does, so a code line ends the paragraph here too). The collected
 * reason must then clear {@link MIN_REASON_WORDS} or the declaration is a hard stop — a
 * placeholder reason convicts the file rather than leaving the scan to hunt for a better one
 * further down, matching ruling 2's "an empty or placeholder reason is not an exemption"
 * exactly.
 *
 * **Round 2 note (#484): the explicit `if (cont.isCode) break` below is defence-in-depth over
 * an invariant that already holds — every code `ClassifiedLine` carries empty `content`, so the
 * very next check (`cont.content.trim().length === 0`) already ends the paragraph on its own,
 * which is why deleting the `isCode` check leaves this file green — it documents the real reason
 * a code line can never contribute to a reason, rather than being the mechanism that enforces it.
 *
 * CRLF line endings are normalized to `\n` up front (`\r\n?` -> `\n`) rather than stripped
 * line-by-line: this text is scanned by {@link classifyLines} at several different points
 * (fence state, indent state, comment state), and normalizing once, before any of them run,
 * means none of them need their own `\r` case.
 *
 * Returns the trimmed, whitespace-collapsed reason, or `undefined` for no declaration, a
 * below-threshold one, or one that never emerges from a comment/fence/indented block.
 */
function declaredExemptionReason(text: string): string | undefined {
  const lines = classifyLines(text.replace(/\r\n?/g, '\n'))

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!
    if (line.isCode) continue
    if (!line.content.startsWith(EXEMPTION_MARKER)) continue

    // A declaration line. Collect its paragraph: the rest of this line, then further quoted
    // lines, stopping at the first blank quoted line, non-quoted line, or code line — all
    // three read off the SAME classified array the declaration line itself came from.
    const paragraph: string[] = [line.content.slice(EXEMPTION_MARKER.length)]
    for (let j = i + 1; j < lines.length; j++) {
      const cont = lines[j]!
      if (cont.isCode) break // gap 3: quoted code ends the paragraph exactly like a blank line does
      if (!cont.quoted) break
      if (cont.content.trim().length === 0) break
      paragraph.push(cont.content)
    }
    const reason = paragraph.join(' ').replace(/\s+/g, ' ').trim()
    const words = reason.match(/[A-Za-z]{2,}/g) ?? []
    return words.length >= MIN_REASON_WORDS ? reason : undefined
  }
  return undefined
}

/** Pure: every shelf entry whose milestone is closed and carries no declared exemption. Mirrors `doc-citation-law.test.ts`'s pattern of a pure detector fed by both the real tree and a synthetic mutation. */
function violationsIn(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  const out: string[] = []
  for (const { number, file, text } of shelf) {
    const entry = manifest.entries.get(number)
    if (!entry || entry.state !== 'closed') continue
    if (declaredExemptionReason(text) !== undefined) continue
    out.push(file)
  }
  return out
}

/**
 * PRDs allowed to be on the live shelf with NO manifest row — i.e. genuinely no
 * milestone. Named, never inferred: `violationsIn` treats "no row" as "not a violation",
 * so without this floor a row that is MISSING for any other reason — a manifest that
 * failed to parse, a key spelling the generator never produced, a malformed line
 * silently skipped — is indistinguishable from a legitimate exemption and the law
 * fails OPEN. Adding a PRD here is a decision someone makes on purpose.
 */
const NO_MILESTONE_ALLOWLIST: readonly string[] = ['prd-34-the-doorstep.md']

/** Pure: live-shelf PRDs with no manifest row and no place on the allowlist — the floor under {@link violationsIn}. */
function unmappedLiveShelf(shelf: readonly ShelfEntry[], manifest: Manifest): string[] {
  return shelf
    .filter((e) => !manifest.entries.has(e.number) && !NO_MILESTONE_ALLOWLIST.includes(e.file))
    .map((e) => e.file)
}

/** See the doc comment's staleness section for why this is a bound rather than a CI regeneration diff. */
const MAX_MANIFEST_AGE_DAYS = 14
const DAY_MS = 24 * 60 * 60 * 1000

/** Pure: `undefined`/unparseable dates are stale by definition — a manifest that does not say when it was generated cannot be trusted to be fresh. */
function isManifestStale(generatedAt: string | undefined, now: Date): boolean {
  if (generatedAt === undefined) return true
  const then = new Date(generatedAt).getTime()
  if (Number.isNaN(then)) return true
  const ageDays = (now.getTime() - then) / DAY_MS
  // A FUTURE generated-at is stale, not fresh. A negative age is never greater than
  // the bound, so the naive comparison called a clock-skewed or hand-edited manifest
  // permanently fresh — the one input that disables this check entirely.
  if (ageDays < 0) return true // see isFutureStamped: the caller reports this differently
  return ageDays > MAX_MANIFEST_AGE_DAYS
}

describe('a PRD whose milestone is closed lives under docs/prds/done/ (prd56 ruling 1)', () => {
  it('has PRDs to check at all — an empty directory would prove nothing', () => {
    expect(liveShelfEntries().length).toBeGreaterThan(5)
  })

  it('the manifest parses and has entries for both open and closed milestones', () => {
    const manifest = liveManifest()
    const states = new Set([...manifest.entries.values()].map((e) => e.state))
    expect(states.has('open')).toBe(true)
    expect(states.has('closed')).toBe(true)
  })

  it('no PRD on the live shelf has a closed milestone with no declared exemption', () => {
    expect(violationsIn(liveShelfEntries(), liveManifest())).toEqual([])
  })

  it('ruling 2: prd-17, prd-53, prd-14 and prd-20 each carry a declared reason despite a closed milestone', () => {
    // `toBeDefined()` alone survived BOTH the HTML-comment-conceal mutant and the
    // `indexOf` -> `lastIndexOf` mutant (verify, 2026-09-14): every one of these four files
    // contains the marker TWICE — the declaration, then a self-reference in the trailing
    // "read by ... for the marker" sentence each one carries — so the wrong occurrence
    // still returns SOME defined string. Pinning the exact CONTENT is what reddens on the
    // wrong occurrence, not just on no occurrence.
    const EXPECTED_REASON: Record<string, string> = {
      'prd-17-complete-record.md':
        "it stays in `docs/prds/` rather than moving to `docs/prds/done/`, and that is a separate operator decision rather than a consequence of shipping — `docs/follow-up-292.md` reads this file's location as the difference between a LIVE ruling and an archival one, and holds an open, uncorrected item against ruling 3's law 1 — whose wording it calls the origin of a claim that is still false in `docs/architecture.md`. Archiving this PRD would demote that ruling while the item is open, and that document reserves the amendment decision for whoever owns the ruling. The move is a follow-up.",
      'prd-20-the-concierge.md':
        'stays on the live shelf rather than moving to `docs/prds/done/` — `docs/prds/prd-34-the-doorstep.md` is live (unmilestoned, still being built) and reasons from this PRD in the present tense: prd-34\'s own ruling 4 says *"prd-20 remains the authority on what the concierge may do (launch or relaunch a conductor, clone by URL; no OAuth, no accounts, no stored credentials)."* Archiving this PRD would demote a ruling prd-34 is deferring to.',
    }
    const shelf = liveShelfEntries()
    const manifest = liveManifest()
    for (const [file, expectedReason] of Object.entries(EXPECTED_REASON)) {
      const entry = shelf.find((e) => e.file === file)
      expect(entry, `${file} must still be on the live shelf`).toBeDefined()
      expect(manifest.entries.get(entry!.number)?.state, `${file}'s milestone must be closed for this test to mean anything`).toBe('closed')
      expect(entry!.text.split(EXEMPTION_MARKER).length - 1, `${file} must carry the marker at least twice for this test to be meaningful`).toBeGreaterThanOrEqual(2)
      expect(declaredExemptionReason(entry!.text), `${file}'s declared reason`).toBe(expectedReason)
    }
  })

  it('the exemption is keyed on the DECLARATION, not on which document made it — a synthetic file under an unrelated name is exempt just the same', () => {
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const declaredElsewhere: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9999-a-file-this-repo-has-never-used.md',
      text: '> **Shelf exemption:** a synthetic reason, not any real PRD\'s.\n',
    }
    expect(violationsIn([declaredElsewhere], manifest)).toEqual([])
  })

  it('the exemption is per-file, not a switch for the whole law — a synthetic no-reason PRD is convicted in the SAME run that clears the real prd-17', () => {
    const shelf = liveShelfEntries()
    const prd17 = shelf.find((e) => e.file === 'prd-17-complete-record.md')
    expect(prd17).toBeDefined()
    const manifest = liveManifest()
    const noReasonClosed: ShelfEntry = { number: prd17!.number, file: 'prd-9998-no-reason-declared.md', text: 'nothing declared here' }
    // Same manifest, same call: prd17 (real, with a reason) clears; the synthetic sibling
    // sharing its milestone number, with no reason, does not. Proves the form cannot be
    // implemented as "never fire" — the obvious miss this issue names.
    expect(violationsIn([prd17!, noReasonClosed], manifest)).toEqual([noReasonClosed.file])
  })

  it('a declaration concealed behind an HTML comment is convicted, not exempted', () => {
    // Verify, 2026-09-14: replacing a real declared-reason block with a single HTML
    // comment carrying the marker left the first version 21/21 green — a reader sees a
    // finished PRD with no stated reason, and the law agreed with the file.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const concealed: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9997-concealed-in-a-comment.md',
      text: '<!-- **Shelf exemption:** still needed, see #428 -->\n\nNo visible reason anywhere in this document.',
    }
    expect(violationsIn([concealed], manifest)).toEqual([concealed.file])
  })

  it('a marker sitting only in a fenced code block documenting the form is convicted, not exempted', () => {
    // Verify, 2026-09-14 (Opus seat): a PRD whose only marker sits inside a fence that
    // documents the mechanism, with the body itself saying nothing is declared, read as
    // exempt — the fence was never excluded from the scan.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const fenced: ShelfEntry = {
      number: closedNumber!,
      file: 'prd-9996-marker-only-in-a-fence.md',
      text: "Ruling 2's form looks like this:\n\n```md\n> **Shelf exemption:** <reason>\n```\n\nNothing is declared in this PRD.",
    }
    expect(violationsIn([fenced], manifest)).toEqual([fenced.file])
  })

  it('mutation: emptying or removing prd-17\'s declared reason convicts it — the marker alone is not an exemption', () => {
    const shelf = liveShelfEntries()
    const prd17 = shelf.find((e) => e.file === 'prd-17-complete-record.md')
    expect(prd17).toBeDefined()
    const manifest = liveManifest()
    expect(manifest.entries.get(prd17!.number)?.state).toBe('closed')
    expect(violationsIn([prd17!], manifest), 'sanity: prd-17 passes today').toEqual([])

    // The real reason continues across several further blockquote lines (this file's own
    // `> **Label:** wrapped prose` convention), so a mutation that only touches the
    // marker's own line leaves the rest of the paragraph intact and understates nothing —
    // measured failing exactly that way on the first version of this test. Strip through
    // the whole quoted run instead: the first line break not followed by another `>` line.
    const markerIdx = prd17!.text.indexOf(EXEMPTION_MARKER)
    expect(markerIdx).toBeGreaterThanOrEqual(0)
    const afterMarker = markerIdx + EXEMPTION_MARKER.length
    const quoteBreak = /\n(?!\s*>)/.exec(prd17!.text.slice(afterMarker))
    const blockEnd = quoteBreak ? afterMarker + quoteBreak.index : prd17!.text.length
    expect(blockEnd, 'the marker must be followed by at least one more blockquote line to strip').toBeGreaterThan(afterMarker)

    const emptied = prd17!.text.slice(0, afterMarker) + prd17!.text.slice(blockEnd)
    expect(emptied, 'the reason must actually have been stripped').not.toBe(prd17!.text)
    expect(declaredExemptionReason(emptied)).toBeUndefined()
    expect(violationsIn([{ ...prd17!, text: emptied }], manifest)).toEqual([prd17!.file])

    const removed = prd17!.text.slice(0, markerIdx) + prd17!.text.slice(blockEnd)
    expect(declaredExemptionReason(removed)).toBeUndefined()
    expect(violationsIn([{ ...prd17!, text: removed }], manifest)).toEqual([prd17!.file])
  })

  it('a PRD with no milestone is not a violation — prd-34-the-doorstep is that one PRD today', () => {
    const shelf = liveShelfEntries()
    const doorstep = shelf.find((e) => e.file === 'prd-34-the-doorstep.md')
    expect(doorstep).toBeDefined()
    // Re-derive rather than trust: this fails, naming the file, the day prd-34
    // gets a milestone — at which point this assertion (and this comment) are
    // the ones that need updating, per the issue's own instruction to verify
    // rather than assume.
    expect(liveManifest().entries.get(doorstep!.number)).toBeUndefined()
    expect(violationsIn([doorstep!], liveManifest())).toEqual([])
  })

  it('every live-shelf PRD has a manifest row, except the named no-milestone allowlist', () => {
    expect(
      unmappedLiveShelf(liveShelfEntries(), liveManifest()),
      'These PRDs are on the live shelf with no row in .swarm/prd-milestones.txt. If you just ' +
        'added one, regenerate and commit the manifest: scripts/dev/prd-milestones.sh. If the PRD ' +
        'genuinely has no milestone, add it to NO_MILESTONE_ALLOWLIST in this file and say why. ' +
        'An empty list here would also mean the manifest failed to parse at all.',
    ).toEqual([])
  })

  it('the floor names a PRD whose row is missing, however it went missing', () => {
    const shelf = liveShelfEntries()
    const manifest = liveManifest()
    // A row deleted, a key the generator never spelled, a line silently skipped as
    // malformed: all three arrive here as "no entry", and all three must be LOUD.
    const stripped: Manifest = { generatedAt: manifest.generatedAt, entries: new Map(manifest.entries) }
    const victim = shelf.find((e) => !NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(victim).toBeDefined()
    stripped.entries.delete(victim!.number)
    // toContain, not toEqual: this test consumes the REAL shelf, so an unrelated PRD
    // added without a manifest row would otherwise make it fail naming the wrong file
    // — a test failing for a reason it does not claim.
    expect(unmappedLiveShelf(shelf, stripped)).toContain(victim!.file)
    // Scoped to the ALLOWLISTED entry, not the whole shelf. Asserting emptiness over
    // the real shelf here duplicated the dedicated floor test one screen up, and made
    // this test fail — with no message — whenever any unrelated PRD lacked a row. The
    // claim is "the allowlisted one stays silent", so that is what is asserted.
    const allowlisted = shelf.filter((e) => NO_MILESTONE_ALLOWLIST.includes(e.file))
    expect(allowlisted.length, 'the allowlist must actually match something on the live shelf').toBeGreaterThan(0)
    expect(unmappedLiveShelf(allowlisted, manifest)).toEqual([])
  })

  it('a CRLF manifest does not silently disarm the law — it reddens the floor instead', () => {
    // The blocker this file shipped with: `.swarm/*.txt` was eol-unspecified, so a
    // Windows checkout delivered `\r`-terminated rows, NO row matched, and the law
    // reported zero violations against a real one. `.gitattributes` now pins the file;
    // this proves that even if it did not, the failure is loud rather than vacuous.
    const crlf = readFileSync(MANIFEST_PATH, 'utf8').replace(/\n/g, '\r\n')
    const parsed = parseManifest(crlf)
    expect(parsed.entries.size, 'the \\r?$ tolerance must keep CRLF rows parseable').toBeGreaterThan(0)
    const emptied: Manifest = { generatedAt: parsed.generatedAt, entries: new Map() }
    expect(unmappedLiveShelf(liveShelfEntries(), emptied).length).toBeGreaterThan(0)
  })

  it('the glob hazard: docs/prds/ non-PRD markdown files are not read as PRDs', () => {
    const matched = matchPrdFilenames([
      'README.md',
      'reconciliation-2026-08-22.md',
      'retained-prds-review-2026-08-22.md',
      // These three pin the ANCHORING the doc comment credits this test with. Without
      // them the fixture killed only a digits-anywhere mutant: dropping the leading `^`
      // and loosening the tail to `.*\.md$` both survived 8/8.
      'notes-prd-99-x.md',
      'prd-99-x.md.bak',
      'prd-99.md',
      'prd-14-experiment-console.md',
    ])
    expect(matched).toEqual([{ number: '14', file: 'prd-14-experiment-console.md' }])
  })

  it('the manifest is not stale (bound: 14 days — see the doc comment for why a bound, not CI regeneration)', () => {
    const generatedAt = liveManifest().generatedAt
    const now = new Date()
    const future = generatedAt !== undefined && !Number.isNaN(new Date(generatedAt).getTime()) && new Date(generatedAt).getTime() > now.getTime()
    // A future stamp is stale too, but telling the reader it is "older than 14 days"
    // is false, and the prescribed remedy re-reads the same wrong clock. WSL2 clock
    // drift across suspend/resume is this repo's own environment, so this is reachable.
    expect(
      future,
      `.swarm/prd-milestones.txt is stamped ${generatedAt}, which is in the FUTURE relative to ` +
        `this machine's clock. Check the clock before regenerating — scripts/dev/prd-milestones.sh ` +
        `reads the same one, so regenerating now would reproduce this.`,
    ).toBe(false)
    expect(
      isManifestStale(generatedAt, now),
      `.swarm/prd-milestones.txt was generated at ${generatedAt} and is now older than ` +
        `${MAX_MANIFEST_AGE_DAYS} days. This is the staleness bound working as ruled, not a ` +
        `defect in whatever you are changing. Regenerate and commit it: scripts/dev/prd-milestones.sh`,
    ).toBe(false)
  })

  it('mutation: the detector bites when a closed-milestone PRD sits on the live shelf', () => {
    // Real manifest, real entry: prd-52's milestone is closed. Rather than
    // actually moving the real file back out of done/ (that mutation was run
    // by hand — see this commit's own body for the executed proof — a repo-
    // wide integration test earns nothing this pure-function test cannot
    // already prove), simulate the exact shape the law must catch: a
    // closed-milestone PRD's text presented as if it were still on the live
    // shelf.
    const manifest = liveManifest()
    const closedNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'closed')?.[0]
    expect(closedNumber).toBeDefined()
    const putBack: ShelfEntry = { number: closedNumber!, file: `prd-${closedNumber}-put-back.md`, text: 'no exemption declared' }
    expect(violationsIn([putBack], manifest)).toEqual([putBack.file])

    // The control: the same entry, but its milestone is open — must NOT fire.
    const openNumber = [...manifest.entries.entries()].find(([, e]) => e.state === 'open')?.[0]
    expect(openNumber).toBeDefined()
    const stillLive: ShelfEntry = { number: openNumber!, file: `prd-${openNumber}-still-live.md`, text: 'no exemption declared' }
    expect(violationsIn([stillLive], manifest)).toEqual([])
  })

  it('prd56 wave 3 (#484): the three fail-open gap shapes are convicted, and the fail-closed one is cleared, all in the SAME violationsIn call that clears the real prd-17', () => {
    // The control from the four-real-PRD requirement above, run again here so this test does
    // not just prove the predicate convicts everything: prd-17 (a genuine declaration) clears
    // in the identical call that convicts the three fail-open synthetics and clears the
    // fail-closed one — a predicate hard-coded to "convict everything" would redden prd-17
    // here; one hard-coded to "never fire" would clear all four gap shapes.
    const shelf = liveShelfEntries()
    const prd17 = shelf.find((e) => e.file === 'prd-17-complete-record.md')
    expect(prd17).toBeDefined()
    const manifest = liveManifest()
    const closedNumber = prd17!.number
    expect(manifest.entries.get(closedNumber)?.state).toBe('closed')

    const gap1FenceIndent: ShelfEntry = {
      number: closedNumber,
      file: 'prd-9995-gap1-indented-fence.md',
      text: '  ~~~\n**Shelf exemption:** only an indented-fence example, never declared for real\n  ~~~\n\nNo real declaration anywhere in this file.',
    }
    const gap2BlockquoteIndent: ShelfEntry = {
      number: closedNumber,
      file: 'prd-9994-gap2-blockquote-indent.md',
      text: '>     **Shelf exemption:** demonstration text inside an indented block, not declared for real.\n\nNo real declaration anywhere in this file.',
    }
    const gap3ContinuationCode: ShelfEntry = {
      number: closedNumber,
      file: 'prd-9993-gap3-continuation-code.md',
      text: '> **Shelf exemption:** -\n> ```\n> quoted code that must never clear the substance threshold\n> ```',
    }
    const gap4CodeSpanComment: ShelfEntry = {
      number: closedNumber,
      file: 'prd-9992-gap4-code-span-comment.md',
      text: '> **Shelf exemption:** `<!-- looks like a comment, is actually the whole reason -->`',
    }

    expect(
      violationsIn([prd17!, gap1FenceIndent, gap2BlockquoteIndent, gap3ContinuationCode, gap4CodeSpanComment], manifest),
    ).toEqual([gap1FenceIndent.file, gap2BlockquoteIndent.file, gap3ContinuationCode.file])
  })

  it('mutation: the bound is exactly 14 days — LITERAL dates, so this reddens at 13 and at 15', () => {
    // These dates are written out, NOT derived from MAX_MANIFEST_AGE_DAYS or DAY_MS.
    // The earlier version computed them as (B-1) and (B+1) days, which asserts
    // `(B-1) > B` is false and `(B+1) > B` is true — true for EVERY B. Measured: the
    // whole file stayed 8/8 green with the bound set to 1, 3, 13, 15 and 365, and with
    // DAY_MS set to three days. It pinned the comparison operator, never the number.
    const now = new Date('2026-09-11T00:00:00Z')
    expect(isManifestStale('2026-08-28T00:00:01Z', now)).toBe(false) // 13d 23h 59m — inside
    expect(isManifestStale('2026-08-28T00:00:00Z', now)).toBe(false) // exactly 14d — the boundary is NOT stale
    expect(isManifestStale('2026-08-27T23:59:59Z', now)).toBe(true) // 14d + 1s — outside
    expect(isManifestStale(undefined, now)).toBe(true)
    expect(isManifestStale('not-a-date', now)).toBe(true)
    // A future timestamp is stale, not fresh — a negative age is never > the bound.
    expect(isManifestStale('2026-09-12T00:00:00Z', now)).toBe(true)
  })
})

describe('declaredExemptionReason — ruling 2\'s marker reader, tested directly and independent of the real tree', () => {
  it('no marker present -> no exemption claimed', () => {
    expect(declaredExemptionReason('nothing relevant here')).toBeUndefined()
  })

  it('marker with prose on its own line -> the reason', () => {
    expect(declaredExemptionReason('> **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('marker at true line start with no blockquote at all -> still the reason', () => {
    expect(declaredExemptionReason('**Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('marker after a nested blockquote, or one with extra internal padding -> still the reason', () => {
    expect(declaredExemptionReason('>> **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
    expect(declaredExemptionReason('>   **Shelf exemption:** prd-55 depends on this ruling directly.')).toBe('prd-55 depends on this ruling directly.')
  })

  it('a reason continuing across further blockquote lines is joined and whitespace-collapsed', () => {
    const text = '> **Shelf exemption:** first line\n> continues   here\n> and here.\n\n## Next section'
    expect(declaredExemptionReason(text)).toBe('first line continues here and here.')
  })

  it('a blank blockquote line ends the paragraph — a later, unrelated paragraph is not swept in', () => {
    const text = '> **Shelf exemption:** the real reason stated here.\n>\n> Unrelated prose in a new paragraph.'
    expect(declaredExemptionReason(text)).toBe('the real reason stated here.')
  })

  it('a non-quoted line also ends the paragraph', () => {
    const text = '> **Shelf exemption:** the real reason stated here.\nplain text with no > prefix'
    expect(declaredExemptionReason(text)).toBe('the real reason stated here.')
  })

  it('CRLF line endings around the marker and its continuation are tolerated', () => {
    expect(declaredExemptionReason('> **Shelf exemption:** first line here\r\n> continues here\r\n')).toBe('first line here continues here')
  })

  // Verify, 2026-09-14: `> **Shelf exemption:** -` and five siblings all passed the first
  // version, which implemented only `reason.length > 0`. This test's TITLE already claimed
  // "placeholder", but only its EMPTY-string assertions backed that claim — a test whose
  // title claims more than it checks is this repo's own recorded defect shape. Each string
  // below is now actually asserted, not merely named.
  it('a placeholder reason is not an exemption, whatever shape the placeholder takes', () => {
    for (const placeholder of ['-', 'TBD', 'n/a', '.', 'x', '**', '​']) {
      expect(declaredExemptionReason(`> **Shelf exemption:** ${placeholder}`), `placeholder ${JSON.stringify(placeholder)} must not be an exemption`).toBeUndefined()
    }
  })

  it('an empty declaration is not an exemption — the marker alone convicts', () => {
    expect(declaredExemptionReason('> **Shelf exemption:**\n')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:**   \n')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:**\n>\n> more text after a paragraph break')).toBeUndefined()
  })

  it('a reason at or just above the substance threshold is an exemption; one word short is not', () => {
    // Pins MIN_REASON_WORDS as a real boundary, the same way the manifest's 14-day bound
    // is pinned with literal dates rather than derived from the constant it tests.
    expect(declaredExemptionReason('> **Shelf exemption:** two words')).toBeUndefined()
    expect(declaredExemptionReason('> **Shelf exemption:** exactly three words')).toBe('exactly three words')
  })

  // The three findings verify raised all collapse into one class: the reader must find the
  // first DECLARATION, not the first OCCURRENCE. Every case below is a form the marker can
  // appear in WITHOUT being a declaration, or a case where more than one occurrence exists
  // and only one may govern.

  it('a marker sitting inside an HTML comment is not a declaration — single-line and multi-line', () => {
    expect(declaredExemptionReason('<!-- **Shelf exemption:** still needed, see #428 -->')).toBeUndefined()
    expect(declaredExemptionReason('> <!-- **Shelf exemption:** still needed,\n> see #428 -->')).toBeUndefined()

    // The two cases above pass WITHOUT the comment blanking too: their opener sits on the
    // marker's own line, so the line-start rule alone rejects them (measured at review —
    // deleting the `withoutComments` step left this test green). The blanking is
    // load-bearing only when the comment WRAPS a line that begins with the marker; these two
    // are that shape, and they are what reddens if the blanking is ever dropped.
    expect(declaredExemptionReason('<!--\n**Shelf exemption:** a hidden reason with several words\n-->')).toBeUndefined()
    expect(declaredExemptionReason('> <!--\n> **Shelf exemption:** a hidden reason with several words\n> -->')).toBeUndefined()
  })

  it('a marker sitting inside a fenced code block is not a declaration — backtick and tilde fences', () => {
    expect(declaredExemptionReason('```md\n> **Shelf exemption:** <reason>\n```\n\nNothing is declared here.')).toBeUndefined()
    expect(declaredExemptionReason('~~~\n**Shelf exemption:** example only\n~~~')).toBeUndefined()
  })

  it('a marker sitting inside an indented code block (4 spaces or a tab) is not a declaration', () => {
    expect(declaredExemptionReason('    **Shelf exemption:** this is example code, not a declaration')).toBeUndefined()
  })

  it('a marker preceded by other prose on the same line is a MENTION, not a declaration, and is skipped', () => {
    expect(declaredExemptionReason('> The form is called **Shelf exemption:** and every PRD should have one.')).toBeUndefined()
    // The mention sitting in a code span, this file's own PRDs' self-reference shape:
    const mentionOnly = "> Declared for #428: the paragraph above is what the law reads, keyed on the\n> `**Shelf exemption:**` marker rather than on this file's name."
    expect(declaredExemptionReason(mentionOnly)).toBeUndefined()
  })

  it('a real declaration is found even when a MENTION of the marker precedes it in the same document', () => {
    const text = '> The form is **Shelf exemption:** described here.\n>\n> **Shelf exemption:** prd-55 depends on this ruling directly.'
    expect(declaredExemptionReason(text)).toBe('prd-55 depends on this ruling directly.')
  })

  it('two genuine declaration lines in one document — the FIRST governs, not the last', () => {
    // Distinct from the mention cases above: both lines here independently satisfy
    // "starts with the marker, has substance". First-match is a deliberate choice, not
    // an accident of scanning order, and this is what would redden a first-vs-last mutant
    // in a document that (unlike today's four real PRDs) actually contains two.
    const text = '> **Shelf exemption:** the first real reason stated here.\n\n> **Shelf exemption:** a different second reason stated here.'
    expect(declaredExemptionReason(text)).toBe('the first real reason stated here.')
  })

  it('mutation: indexOf vs lastIndexOf is pinned by CONTENT — a real declaration followed by a self-reference mention returns the DECLARATION, not the mention', () => {
    // This is the exact shape all four exempted PRDs carry: the declaration, then a later
    // sentence quoting the marker (in a code span) to tell a human reader where the law
    // looks. Verify measured the first version 21/21 green under `indexOf` -> `lastIndexOf`
    // because nothing asserted WHICH occurrence's text came back.
    const text = "> **Shelf exemption:** prd-55 depends on this ruling directly.\n>\n> Declared for #428, read via the\n> `**Shelf exemption:**` marker."
    expect(declaredExemptionReason(text)).toBe('prd-55 depends on this ruling directly.')
  })

  it('the reader never inspects a filename — only violationsIn does, and only via the manifest number', () => {
    // Pinned so a future refactor cannot quietly add a filename parameter and start
    // keying the exemption on identity, the exact failure mode this issue names.
    expect(declaredExemptionReason.length).toBe(1)
  })

  // prd56 wave 3 (#484) — the four gaps wave 2's fix re-review found. Each test below
  // reddens on the tree this wave started from and passes once `classifyLines` is the
  // single predicate both the declaration scan and the continuation loop read. Each also
  // carries a second assertion using a spelling this issue's own table never named, so a
  // fix that only special-cased the reported string cannot pass either one.

  it('gap 1 (#484, fail open): a fence indented 1-3 columns, with no blockquote, still hides its interior', () => {
    const indentedFence = '  ~~~\n**Shelf exemption:** worked example only, not a real declaration\n  ~~~\n\nNo real declaration exists anywhere in this document.'
    expect(declaredExemptionReason(indentedFence)).toBeUndefined()

    // Unlisted spelling: 1-column indent (the opposite boundary from the primary case's 2),
    // backtick fence instead of tilde, still with no blockquote at all.
    const oneColumn = ' ```\n**Shelf exemption:** also just an example, still inside the fence\n ```\n\nNo real declaration exists anywhere in this document.'
    expect(declaredExemptionReason(oneColumn)).toBeUndefined()

    // Control: the same 1-3 column allowance must not swallow a REAL declaration sitting
    // outside any fence.
    const real = '  ~~~\nexample fence content, unrelated\n  ~~~\n\n> **Shelf exemption:** the real reason, stated in the open.'
    expect(declaredExemptionReason(real)).toBe('the real reason, stated in the open.')
  })

  it('gap 2 (#484, fail open): an indented-code line inside a blockquote is code once the blockquote\'s own one-space allowance is accounted for', () => {
    const indented = '>     **Shelf exemption:** demonstration text living in an indented block, not declared for real.\n\nNo real declaration exists anywhere in this document.'
    expect(declaredExemptionReason(indented)).toBeUndefined()

    // Unlisted spelling: a tab-indented residual instead of five spaces.
    const tabbed = '>\t\t**Shelf exemption:** filler behind a tab-indented line, never actually declared.\n\nNo real declaration exists anywhere in this document.'
    expect(declaredExemptionReason(tabbed)).toBeUndefined()

    // Control: 3 residual spaces — one short of the indented-code boundary — must still declare.
    const stillProse = '>   **Shelf exemption:** exactly at the padding boundary, still a real declaration.'
    expect(declaredExemptionReason(stillProse)).toBe('exactly at the padding boundary, still a real declaration.')
  })

  it('gap 3 (#484, fail open): the continuation loop applies the SAME fence/indent check as the declaration line, so quoted code never counts toward the reason', () => {
    // Fence variant, the issue's own shape, reworded.
    const fenced = '> **Shelf exemption:** -\n> ```\n> this quoted fence text must never count toward the reason\n> ```'
    expect(declaredExemptionReason(fenced)).toBeUndefined()

    // Unlisted-spelling sibling: an INDENTED continuation line, not a fence at all — proves
    // the fix is the general predicate, not a fence-shaped patch one level down.
    const indentedContinuation = '> **Shelf exemption:** x\n>     this indented continuation line must never count toward the reason either'
    expect(declaredExemptionReason(indentedContinuation)).toBeUndefined()

    // Control: a genuine multi-line PROSE continuation must still be swept in.
    const realContinuation = '> **Shelf exemption:** the reason starts here\n> and genuinely continues here, in plain quoted prose.'
    expect(declaredExemptionReason(realContinuation)).toBe('the reason starts here and genuinely continues here, in plain quoted prose.')
  })

  it('gap 4a (#484, fail open): an HTML comment with no closing "-->" anywhere swallows everything after it, including a real declaration', () => {
    const text = '<!-- a note that never actually gets closed\n\n> **Shelf exemption:** looks real but sits inside the still-open comment above'
    expect(declaredExemptionReason(text)).toBeUndefined()

    // Control: the identical declaration, with the stray unterminated opener removed, must
    // still be found — this is not a general refusal to read anything near "<!--".
    const withoutStrayOpener = '\n\n> **Shelf exemption:** looks real but sits inside the still-open comment above'
    expect(declaredExemptionReason(withoutStrayOpener)).toBe('looks real but sits inside the still-open comment above')
  })

  it('gap 4b (#484, fail closed): comment syntax written INSIDE an inline code span is not a real comment, and must not blank a real declaration around it', () => {
    const text = '> **Shelf exemption:** `<!-- this reads like a comment but is actually the whole visible reason -->`'
    expect(declaredExemptionReason(text)).toBe('`<!-- this reads like a comment but is actually the whole visible reason -->`')

    // Unlisted spelling: the fake tag sits on its OWN continuation line, not the marker's line.
    const continuationVariant = '> **Shelf exemption:** documented as\n> `<!-- an example only, never a real comment -->` in the style guide.'
    expect(declaredExemptionReason(continuationVariant)).toBe('documented as `<!-- an example only, never a real comment -->` in the style guide.')
  })

  // Round 2 (#484): a fix re-review of wave 3 found the table stating a verdict the code did not
  // produce (finding 1, table rows 9-10) and a genuine tab-arithmetic regression (finding 2, table
  // rows 30-36). Neither is a fifth spelling of the four gaps above — see the "Wave 3, round 2" doc
  // comment section for the full analysis.

  it('round 2 finding 1 (#484): a fence-looking line indented 4+ columns is ordinary indented code for that ONE line only — it opens no fence, and the line right after it is a plain, visible paragraph', () => {
    // Table row 9: the base table wrongly claimed this "hides its interior" like a real (0-3
    // column) indented fence does. It does not — CommonMark never treats a 4+-indented backtick
    // run as a fence opener at all.
    const backtick = '    ```\n**Shelf exemption:** the marker right after an over-indented fence-looking line, still visible\n    ```'
    expect(declaredExemptionReason(backtick)).toBe('the marker right after an over-indented fence-looking line, still visible')

    // Unlisted spelling: tilde instead of backtick, and a different indent depth (5, not 4).
    const tilde = '     ~~~~\n**Shelf exemption:** same shape, a wider indent and a different fence character\n     ~~~~'
    expect(declaredExemptionReason(tilde)).toBe('same shape, a wider indent and a different fence character')

    // Control: a GENUINE column-0 fence must still hide its interior — this is not "fences never
    // hide anything now".
    const genuineFence = '```\n**Shelf exemption:** inside a real fence, never visible\n```\n\nNo real declaration exists anywhere in this document.'
    expect(declaredExemptionReason(genuineFence)).toBeUndefined()
  })

  it('round 2 finding 2 (#484, fail closed, fixed): a blockquote prefix combining a literal space with a tab must be measured in COLUMNS, not characters', () => {
    // The four regressed prefixes named by the finding, each as its own declaration (no
    // continuation needed to exercise the declaration-scan side of the bug).
    const spaceThenTab = '> \t**Shelf exemption:** exactly two columns of credit, still a visible paragraph'
    expect(declaredExemptionReason(spaceThenTab)).toBe('exactly two columns of credit, still a visible paragraph')

    const twoSpacesThenTab = '>  \t**Shelf exemption:** two literal spaces then a tab, still under the threshold'
    expect(declaredExemptionReason(twoSpacesThenTab)).toBe('two literal spaces then a tab, still under the threshold')

    const spaceTabSpace = '> \t **Shelf exemption:** three columns of credit, one short of the boundary'
    expect(declaredExemptionReason(spaceTabSpace)).toBe('three columns of credit, one short of the boundary')

    const twoSpacesTabSpace = '>  \t **Shelf exemption:** the same three-column boundary, reached a different way'
    expect(declaredExemptionReason(twoSpacesTabSpace)).toBe('the same three-column boundary, reached a different way')

    // Correction to the record: a BARE tab right after `>`, with no preceding space, was already
    // correct before this round (it fully satisfies the marker's one-column allowance and leaves
    // no residual credit) — pinned here so it is never mistaken for a fifth regressed prefix.
    const bareTab = '>\t**Shelf exemption:** a bare tab consumes the marker whole, no residual indent at all'
    expect(declaredExemptionReason(bareTab)).toBe('a bare tab consumes the marker whole, no residual indent at all')

    // Controls: the arithmetic must still convict once enough columns are genuinely spent — this
    // is a corrected instrument, not a new "any prefix with a tab is exempt" rule.
    const twoBareTabs = '>\t\t**Shelf exemption:** two bare tabs reach the 4-column threshold exactly'
    expect(declaredExemptionReason(twoBareTabs)).toBeUndefined()

    const spaceThenTwoTabs = '> \t\t**Shelf exemption:** a space then two tabs clears the threshold with room to spare'
    expect(declaredExemptionReason(spaceThenTwoTabs)).toBeUndefined()
  })

  it('round 2 finding 2 (#484): the SAME tab-column arithmetic applies to the continuation loop, not only the declaration line', () => {
    // The finding's own illustration of this half of the blind spot uses `>   \t` (3 spaces then a
    // tab); this pins it with a different spelling (4 spaces) reaching the same >=4 credit, so the
    // fix is not "recognize that one continuation prefix" but the general arithmetic.
    const sweptCode = '> **Shelf exemption:** x\n>    \tthis continuation is genuinely indented code and must not count'
    expect(declaredExemptionReason(sweptCode)).toBeUndefined()

    // Control: a continuation whose tab-driven credit stays under 4 must still be swept into the
    // reason as ordinary prose — this is a corrected instrument, not "no continuation with a tab
    // ever counts again".
    const genuineContinuation = '> **Shelf exemption:** the reason begins here\n>  \tand genuinely continues here, under the threshold'
    expect(declaredExemptionReason(genuineContinuation)).toBe('the reason begins here and genuinely continues here, under the threshold')
  })
})
