/**
 * THREE PROGRAMS, AND WHY THERE ARE THREE.
 *
 * The **mark** program draws everything with vertices: ribbons, contours, glows,
 * motes, baked geometry, strokes and arcs. One vertex format, two falloff modes,
 * and the camera as a uniform rather than a `setTransform` — so the whole frame
 * is one upload and a handful of `drawArrays`.
 *
 * The **wash** and **grain** programs draw no vertices of their own. They are one
 * static unit quad each, parameterised entirely by uniforms, and they exist
 * because their two marks are panel-sized: a two-stop radial tessellated finely
 * enough not to band would have cost more vertices than the rest of the frame put
 * together, and a noise field has no vertex form at all. `paint.ts` cached a
 * `CanvasGradient` per resize and a `CanvasPattern` per tile to make these
 * affordable; here there is nothing to cache, because there is nothing to build.
 *
 * The grain's tile is the one exception: a texture, uploaded once per tile size,
 * generated by **the same xorshift walk `paint.ts` used** so the print's grain is
 * the same grain it always was rather than a new noise that merely looks similar.
 */

const MARK_VERT = `#version 300 es
precision highp float;
layout(location=0) in vec2 aPos;
layout(location=1) in vec4 aColour;
layout(location=2) in vec4 aFall;
uniform vec2 uPanel;
/** k, x, y — the camera, or (1, 0, 0) for the chrome pass. */
uniform vec3 uCam;
out vec4 vColour;
out vec4 vFall;
out vec2 vPos;
void main() {
  vColour = aColour;
  vFall = aFall;
  vPos = aPos;
  vec2 placed = aPos * uCam.x + uCam.yz;
  vec2 clip = (placed / uPanel) * 2.0 - 1.0;
  gl_Position = vec4(clip.x, -clip.y, 0.0, 1.0);
}`

const MARK_FRAG = `#version 300 es
precision highp float;
in vec4 vColour;
in vec4 vFall;
in vec2 vPos;
out vec4 outColour;
void main() {
  float a = vColour.a;
  if (vFall.w > 0.5) {
    float r = length(vPos - vFall.xy) / max(vFall.z, 0.001);
    float f = max(0.0, 1.0 - r);
    // 1 is a glow, which paint.ts drew as a two-stop gradient and is therefore
    // linear in alpha; 2 is a mote, whose sprite walks (1 - t)^2 because a linear
    // ramp has a visible edge where it reaches zero and 240 of those read as a
    // field of discs rather than a drift of light.
    a *= vFall.w > 1.5 ? f * f : f;
  }
  outColour = vec4(vColour.rgb * a, a);
}`

/** The panel, as a unit quad. Both screen-space programs share it. */
const QUAD_VERT = `#version 300 es
precision highp float;
layout(location=0) in vec2 aUnit;
uniform vec2 uPanel;
uniform vec2 uSize;
out vec2 vPx;
void main() {
  vPx = aUnit * uSize;
  vec2 clip = (vPx / uPanel) * 2.0 - 1.0;
  gl_Position = vec4(clip.x, -clip.y, 0.0, 1.0);
}`

/** Two stops, interpolated **premultiplied** — which is what a CanvasGradient does. */
const WASH_FRAG = `#version 300 es
precision highp float;
in vec2 vPx;
uniform vec2 uCentre;
uniform vec2 uRadii;
uniform vec4 uInner;
uniform vec4 uOuter;
out vec4 outColour;
void main() {
  float r = length(vPx - uCentre);
  float t = uRadii.y <= uRadii.x ? 1.0 : clamp((r - uRadii.x) / (uRadii.y - uRadii.x), 0.0, 1.0);
  outColour = mix(uInner, uOuter, t);
}`

const GRAIN_FRAG = `#version 300 es
precision highp float;
in vec2 vPx;
uniform sampler2D uNoise;
uniform float uTile;
uniform vec2 uShift;
uniform vec4 uInk;
out vec4 outColour;
void main() {
  float n = texture(uNoise, (vPx + uShift) / uTile).r;
  float a = n * uInk.a;
  outColour = vec4(uInk.rgb * a, a);
}`

export interface MarkProgram {
  program: WebGLProgram
  uPanel: WebGLUniformLocation | null
  uCam: WebGLUniformLocation | null
}

export interface WashProgram {
  program: WebGLProgram
  uPanel: WebGLUniformLocation | null
  uSize: WebGLUniformLocation | null
  uCentre: WebGLUniformLocation | null
  uRadii: WebGLUniformLocation | null
  uInner: WebGLUniformLocation | null
  uOuter: WebGLUniformLocation | null
}

export interface GrainProgram {
  program: WebGLProgram
  uPanel: WebGLUniformLocation | null
  uSize: WebGLUniformLocation | null
  uTile: WebGLUniformLocation | null
  uShift: WebGLUniformLocation | null
  uInk: WebGLUniformLocation | null
  uNoise: WebGLUniformLocation | null
}

export interface Resources {
  marks: MarkProgram
  wash: WashProgram
  grain: GrainProgram
  markVao: WebGLVertexArrayObject | null
  quadVao: WebGLVertexArrayObject | null
  pos: WebGLBuffer | null
  col: WebGLBuffer | null
  fall: WebGLBuffer | null
  quad: WebGLBuffer | null
  noise: { texture: WebGLTexture | null; tile: number }
}

/**
 * Everything the painter owns on the GPU, built in one go.
 *
 * All of it dies when the context is lost and all of it is rebuilt by calling
 * this again — which is the whole of the recovery path, and the reason the
 * painter keeps no GL handle anywhere else.
 */
export function createResources(gl: WebGL2RenderingContext): Resources {
  const marks = link(gl, MARK_VERT, MARK_FRAG)
  const wash = link(gl, QUAD_VERT, WASH_FRAG)
  const grain = link(gl, QUAD_VERT, GRAIN_FRAG)

  const pos = gl.createBuffer()
  const col = gl.createBuffer()
  const fall = gl.createBuffer()
  const markVao = gl.createVertexArray()
  gl.bindVertexArray(markVao)
  attribute(gl, pos, 0, 2)
  attribute(gl, col, 1, 4)
  attribute(gl, fall, 2, 4)

  const quad = gl.createBuffer()
  const quadVao = gl.createVertexArray()
  gl.bindVertexArray(quadVao)
  gl.bindBuffer(gl.ARRAY_BUFFER, quad)
  gl.bufferData(
    gl.ARRAY_BUFFER,
    new Float32Array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1]),
    gl.STATIC_DRAW,
  )
  gl.enableVertexAttribArray(0)
  gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 0, 0)
  gl.bindVertexArray(null)

  return {
    marks: {
      program: marks,
      uPanel: gl.getUniformLocation(marks, 'uPanel'),
      uCam: gl.getUniformLocation(marks, 'uCam'),
    },
    wash: {
      program: wash,
      uPanel: gl.getUniformLocation(wash, 'uPanel'),
      uSize: gl.getUniformLocation(wash, 'uSize'),
      uCentre: gl.getUniformLocation(wash, 'uCentre'),
      uRadii: gl.getUniformLocation(wash, 'uRadii'),
      uInner: gl.getUniformLocation(wash, 'uInner'),
      uOuter: gl.getUniformLocation(wash, 'uOuter'),
    },
    grain: {
      program: grain,
      uPanel: gl.getUniformLocation(grain, 'uPanel'),
      uSize: gl.getUniformLocation(grain, 'uSize'),
      uTile: gl.getUniformLocation(grain, 'uTile'),
      uShift: gl.getUniformLocation(grain, 'uShift'),
      uInk: gl.getUniformLocation(grain, 'uInk'),
      uNoise: gl.getUniformLocation(grain, 'uNoise'),
    },
    markVao,
    quadVao,
    pos,
    col,
    fall,
    quad,
    noise: { texture: null, tile: 0 },
  }
}

/**
 * THE GRAIN TILE — the same deterministic walk `paint.ts` wrote into an
 * `ImageData`, as one channel of a texture.
 *
 * A fixed xorshift over the pixel index rather than `Math.random`, so two panels
 * in one session and a replay on another machine carry the same grain. Only the
 * alpha varies; the colour is the mark's, applied in the shader, which is why one
 * red channel is the whole tile.
 */
export function noiseTile(size: number): Uint8Array {
  const data = new Uint8Array(size * size)
  let hash = 0x9e3779b9
  for (let i = 0; i < data.length; i += 1) {
    hash ^= hash << 13
    hash ^= hash >>> 17
    hash ^= hash << 5
    hash |= 0
    data[i] = (hash >>> 24) & 0xff
  }
  return data
}

export function uploadNoise(gl: WebGL2RenderingContext, resources: Resources, tile: number): void {
  if (resources.noise.tile === tile && resources.noise.texture !== null) return
  if (resources.noise.texture !== null) gl.deleteTexture(resources.noise.texture)

  const texture = gl.createTexture()
  gl.bindTexture(gl.TEXTURE_2D, texture)
  gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1)
  gl.texImage2D(
    gl.TEXTURE_2D,
    0,
    gl.R8,
    tile,
    tile,
    0,
    gl.RED,
    gl.UNSIGNED_BYTE,
    noiseTile(tile),
  )
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.REPEAT)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.REPEAT)
  // Linear, because `paint.ts` drew its pattern through a `dpr` transform with
  // image smoothing on: the tile was magnified and filtered there too.
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR)
  resources.noise = { texture, tile }
}

export function releaseResources(gl: WebGL2RenderingContext, resources: Resources): void {
  gl.deleteProgram(resources.marks.program)
  gl.deleteProgram(resources.wash.program)
  gl.deleteProgram(resources.grain.program)
  gl.deleteVertexArray(resources.markVao)
  gl.deleteVertexArray(resources.quadVao)
  gl.deleteBuffer(resources.pos)
  gl.deleteBuffer(resources.col)
  gl.deleteBuffer(resources.fall)
  gl.deleteBuffer(resources.quad)
  if (resources.noise.texture !== null) gl.deleteTexture(resources.noise.texture)
}

function attribute(
  gl: WebGL2RenderingContext,
  buffer: WebGLBuffer | null,
  location: number,
  size: number,
): void {
  gl.bindBuffer(gl.ARRAY_BUFFER, buffer)
  gl.enableVertexAttribArray(location)
  gl.vertexAttribPointer(location, size, gl.FLOAT, false, 0, 0)
}

function link(gl: WebGL2RenderingContext, vertex: string, fragment: string): WebGLProgram {
  const compile = (type: number, source: string): WebGLShader => {
    const shader = gl.createShader(type) as WebGLShader
    gl.shaderSource(shader, source)
    gl.compileShader(shader)
    if (gl.getShaderParameter(shader, gl.COMPILE_STATUS) !== true) {
      throw new Error(`scene shader: ${gl.getShaderInfoLog(shader)}`)
    }
    return shader
  }

  const program = gl.createProgram() as WebGLProgram
  const vs = compile(gl.VERTEX_SHADER, vertex)
  const fs = compile(gl.FRAGMENT_SHADER, fragment)
  gl.attachShader(program, vs)
  gl.attachShader(program, fs)
  gl.linkProgram(program)
  gl.deleteShader(vs)
  gl.deleteShader(fs)
  if (gl.getProgramParameter(program, gl.LINK_STATUS) !== true) {
    throw new Error(`scene program: ${gl.getProgramInfoLog(program)}`)
  }
  return program
}
